-- Generated by generate_ddl.sql.py

-- DATABASE_URL: postgresql+psycopg://smartcart_user:777@localhost:5432/smartcart



CREATE TABLE categories (
	id VARCHAR(36) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE users (
	id UUID NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	password_hash TEXT NOT NULL, 
	role user_roles NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE carts (
	id VARCHAR(36) NOT NULL, 
	user_id UUID NOT NULL, 
	subtotal NUMERIC(10, 2) NOT NULL, 
	discount NUMERIC(10, 2) NOT NULL, 
	tax NUMERIC(10, 2) NOT NULL, 
	total_amount NUMERIC(10, 2) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE orders (
	id VARCHAR(36) NOT NULL, 
	user_id UUID NOT NULL, 
	order_number VARCHAR(30) NOT NULL, 
	status order_status NOT NULL, 
	subtotal NUMERIC(10, 2) NOT NULL, 
	discount NUMERIC(10, 2) NOT NULL, 
	tax NUMERIC(10, 2) NOT NULL, 
	total_amount NUMERIC(10, 2) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE products (
	id VARCHAR(36) NOT NULL, 
	sku VARCHAR(50) NOT NULL, 
	barcode VARCHAR(50), 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	brand VARCHAR(100), 
	category_id VARCHAR(36) NOT NULL, 
	unit VARCHAR(20), 
	is_active BOOLEAN, 
	metadata JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (barcode), 
	FOREIGN KEY(category_id) REFERENCES categories (id)
);

CREATE TABLE user_addresses (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	address_type VARCHAR(20) NOT NULL, 
	line1 VARCHAR(255) NOT NULL, 
	line2 VARCHAR(255), 
	city VARCHAR(100) NOT NULL, 
	state VARCHAR(100) NOT NULL, 
	country VARCHAR(100) NOT NULL, 
	postal_code VARCHAR(20) NOT NULL, 
	is_default BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_devices (
	id UUID NOT NULL, 
	user_id UUID, 
	device_name VARCHAR(100), 
	device_type VARCHAR(50), 
	operating_system VARCHAR(50), 
	browser VARCHAR(50), 
	device_identifier VARCHAR(255), 
	trusted BOOLEAN, 
	last_seen TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (device_identifier)
);

CREATE TABLE user_notifications (
	id UUID NOT NULL, 
	user_id UUID, 
	title VARCHAR(255), 
	message TEXT, 
	notification_type VARCHAR(50), 
	is_read BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_preferences (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	theme VARCHAR(20) NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	notifications_enabled BOOLEAN NOT NULL, 
	preferences JSONB, 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	first_name VARCHAR(100), 
	last_name VARCHAR(100), 
	phone_number VARCHAR(20), 
	profile_image TEXT, 
	date_of_birth TIMESTAMP WITHOUT TIME ZONE, 
	loyalty_points INTEGER NOT NULL, 
	total_orders INTEGER NOT NULL, 
	total_spent INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_sessions (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	refresh_token TEXT NOT NULL, 
	ip_address VARCHAR(50), 
	user_agent TEXT, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_activity TIMESTAMP WITH TIME ZONE, 
	is_revoked BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
	id VARCHAR(36) NOT NULL, 
	cart_id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36) NOT NULL, 
	quantity INTEGER NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	total_price NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(cart_id) REFERENCES carts (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE inventory (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36), 
	quantity INTEGER, 
	reorder_level INTEGER, 
	max_capacity INTEGER, 
	location VARCHAR(100), 
	PRIMARY KEY (id), 
	UNIQUE (product_id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE order_items (
	id VARCHAR(36) NOT NULL, 
	order_id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36) NOT NULL, 
	product_name VARCHAR(255) NOT NULL, 
	sku VARCHAR(50) NOT NULL, 
	quantity INTEGER NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	total_price NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(order_id) REFERENCES orders (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE payments (
	id VARCHAR(36) NOT NULL, 
	order_id VARCHAR(36) NOT NULL, 
	user_id UUID NOT NULL, 
	transaction_id VARCHAR(100) NOT NULL, 
	gateway_reference VARCHAR(255), 
	payment_method paymentmethod NOT NULL, 
	status paymentstatus NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(order_id) REFERENCES orders (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (gateway_reference)
);

CREATE TABLE product_detection (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36), 
	model_name VARCHAR(100), 
	class_name VARCHAR(100), 
	confidence_threshold NUMERIC(5, 2), 
	embeddings JSON, 
	PRIMARY KEY (id), 
	UNIQUE (product_id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE product_images (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36), 
	image_url TEXT, 
	image_type VARCHAR(30), 
	is_primary BOOLEAN, 
	content_hash VARCHAR(64), 
	PRIMARY KEY (id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE reviews (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36) NOT NULL, 
	user_name VARCHAR(120), 
	rating FLOAT NOT NULL, 
	title VARCHAR(200), 
	body TEXT NOT NULL, 
	is_generated BOOLEAN NOT NULL DEFAULT TRUE, 
	verified_purchase BOOLEAN DEFAULT FALSE, 
	helpful_count INTEGER DEFAULT 0, 
	review_date TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE product_prices (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36), 
	price NUMERIC(10, 2) NOT NULL, 
	gst_percentage NUMERIC(5, 2), 
	discount_percentage NUMERIC(5, 2), 
	PRIMARY KEY (id), 
	UNIQUE (product_id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE product_weights (
	id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36), 
	expected_weight NUMERIC(10, 2), 
	tolerance NUMERIC(10, 2), 
	unit VARCHAR(20), 
	PRIMARY KEY (id), 
	UNIQUE (product_id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE inventory_transactions (
	id VARCHAR(36) NOT NULL, 
	inventory_id VARCHAR(36) NOT NULL, 
	product_id VARCHAR(36) NOT NULL, 
	transaction_type inventorytransactiontype NOT NULL, 
	quantity_change INTEGER NOT NULL, 
	quantity_before INTEGER NOT NULL, 
	quantity_after INTEGER NOT NULL, 
	reference_type VARCHAR(50), 
	reference_id VARCHAR(36), 
	remarks VARCHAR(255), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(inventory_id) REFERENCES inventory (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id)
);

CREATE TABLE transactions (
	id VARCHAR(36) NOT NULL, 
	payment_id VARCHAR(36) NOT NULL, 
	transaction_reference VARCHAR(100) NOT NULL, 
	gateway_transaction_id VARCHAR(255), 
	status transactionstatus NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	gateway_response VARCHAR(1000), 
	processed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(payment_id) REFERENCES payments (id) ON DELETE CASCADE
);
