import sys
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.schema import CreateTable

# Ensure `app` package is importable when running this script directly
BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.db.base import Base  # noqa: E402
from app.core.config import settings  # noqa: E402

# Import models so Base.metadata is populated (must include all tables referenced by FKs)
import app.models.products  # noqa: F401,E402
import app.models.user  # noqa: F401,E402
import app.models.cart.cart  # noqa: F401,E402
import app.models.cart.cart_item  # noqa: F401,E402
import app.models.order.order  # noqa: F401,E402
import app.models.order.order_item  # noqa: F401,E402
import app.models.payment  # noqa: F401,E402
import app.models.transaction  # noqa: F401,E402


def main() -> None:
    engine = create_engine(settings.DATABASE_URL, pool_pre_ping=True)

    out_path = Path(__file__).resolve().parent.parent / "ddl.sql"

    statements: list[str] = []
    statements.append("-- Generated by generate_ddl.sql.py")
    statements.append(f"-- DATABASE_URL: {settings.DATABASE_URL}")
    statements.append("")

    for table in Base.metadata.sorted_tables:
        stmt = str(CreateTable(table).compile(engine)).strip()
        if stmt:
            statements.append(stmt + ";")

    out_path.write_text("\n\n".join(statements) + "\n", encoding="utf-8")
    print(f"Wrote DDL to: {out_path}")


if __name__ == "__main__":
    main()
