"""Curated Indian catalog — part 9: backfill to reach the 50-SKU floor.

These are real Indian products added to push every category to >= 50 SKUs.
Each line is reviewable; all gates re-run after this file.
"""

from .schema import P

# Bakery (need ~41) ----------------------------------------------------------- #
BAKERY = [
    P("Fruit Bread", "Britannia", "Bakery", [("400 g", 55, 400, "g")],
      "Soft bread with candied fruit.",
      subcategory="Bread", ingredient_tags=["bread", "fruit"],
      search=["fruit bread"], image_queries=["fruit bread pack"],
      related=["Britannia Whole Wheat Bread", "Modern Brown Bread"]),
    P("Multigrain Bread", "Harvest Gold", "Bakery", [("400 g", 60, 400, "g")],
      "Bread with oats, wheat and bran.",
      subcategory="Bread", veg=True, ingredient_tags=["bread", "multigrain"],
      search=["multigrain bread"], image_queries=["multigrain bread pack"],
      related=["Britannia Whole Wheat Bread", "Modern Brown Bread"]),
    P("Garlic Bread", "The Baker's Dozen", "Bakery", [("200 g", 90, 200, "g")],
      "Toasted garlic-buttered bread sticks.",
      subcategory="Bread", ingredient_tags=["bread", "garlic"],
      search=["garlic bread"], image_queries=["garlic bread pack"],
      related=["Britannia Burger Buns", "Cheese Slices"]),
    P("Croissant", "The Baker's Dozen", "Bakery", [("4 pcs", 120, 200, "g")],
      "Flaky all-butter croissants.",
      subcategory="Pastry", ingredient_tags=["pastry", "croissant"],
      search=["croissant"], image_queries=["croissant pack"],
      related=["Butter Croissant", "Fruit Cake"]),
    P("Butter Croissant", "The Baker's Dozen", "Bakery", [("4 pcs", 130, 200, "g")],
      "Classic French butter croissant.",
      subcategory="Pastry", ingredient_tags=["pastry", "croissant"],
      search=["butter croissant"], image_queries=["butter croissant pack"],
      related=["Croissant", "Fruit Cake"]),
    P("Chocolate Muffin", "The Baker's Dozen", "Bakery", [("4 pcs", 140, 200, "g")],
      "Eggless chocolate muffins.",
      subcategory="Pastry", ingredient_tags=["muffin", "chocolate"],
      search=["muffin", "chocolate muffin"], image_queries=["chocolate muffin pack"],
      related=["Fruit Cake", "Cookies"]),
    P("Cookies", "The Baker's Dozen", "Bakery", [("200 g", 90, 200, "g")],
      "Eggless butter cookies.",
      subcategory="Cookies", ingredient_tags=["cookies", "biscuit"],
      search=["cookies", "fresh cookies"], image_queries=["fresh cookies pack"],
      related=["Chocolate Muffin", "Rusk"]),
    P("Cupcake", "The Baker's Dozen", "Bakery", [("4 pcs", 150, 200, "g")],
      "Vanilla cupcakes with frosting.",
      subcategory="Pastry", ingredient_tags=["cupcake", "cake"],
      search=["cupcake"], image_queries=["cupcake pack"],
      related=["Fruit Cake", "Chocolate Muffin"]),
    P("Veg Puff", "Monginis", "Bakery", [("4 pcs", 120, 200, "g")],
      "Flaky puff with spiced veg.",
      subcategory="Pastry", ingredient_tags=["puff", "snack"],
      search=["veg puff"], image_queries=["veg puff pack"],
      related=["Patties", "Burger Buns"]),
    P("Patties", "Monginis", "Bakery", [("4 pcs", 140, 200, "g")],
      "Potato-filled pastry patties.",
      subcategory="Pastry", ingredient_tags=["patties", "snack"],
      search=["patties"], image_queries=["patties pack"],
      related=["Veg Puff", "Burger Buns"]),
    P("Chocolate Pastry", "Monginis", "Bakery", [("2 pcs", 100, 120, "g")],
      "Chocolate cream pastry.",
      subcategory="Pastry", ingredient_tags=["pastry", "chocolate"],
      search=["chocolate pastry"], image_queries=["chocolate pastry pack"],
      related=["Fruit Cake", "Cupcake"]),
    P("Pineapple Pastry", "Monginis", "Bakery", [("2 pcs", 100, 120, "g")],
      "Pineapple cream pastry.",
      subcategory="Pastry", ingredient_tags=["pastry", "pineapple"],
      search=["pineapple pastry"], image_queries=["pineapple pastry pack"],
      related=["Fruit Cake", "Chocolate Pastry"]),
    P("Donut", "Monginis", "Bakery", [("4 pcs", 120, 200, "g")],
      "Chocolate-glazed donuts.",
      subcategory="Pastry", ingredient_tags=["donut", "sweet"],
      search=["donut"], image_queries=["donut pack"],
      related=["Cupcake", "Chocolate Pastry"]),
    P("Plum Cake", "Monginis", "Bakery", [("500 g", 250, 500, "g")],
      "Festive fruit plum cake.",
      subcategory="Cake", ingredient_tags=["cake", "plum"],
      search=["plum cake"], image_queries=["plum cake pack"],
      related=["Fruit Cake", "Brown Bread"]),
    P("Brown Bread Loaf", "Modern", "Bakery", [("400 g", 50, 400, "g")],
      "Wholegrain brown bread loaf.",
      subcategory="Bread", veg=True, ingredient_tags=["bread", "brown"],
      search=["brown bread loaf"], image_queries=["brown bread loaf pack"],
      related=["Modern Brown Bread", "Whole Wheat Bread"]),
    P("Pav Bun", "The Baker's Dozen", "Bakery", [("6 pcs", 45, 200, "g")],
      "Soft Mumbai pav buns.",
      subcategory="Bun", ingredient_tags=["pav", "bun"],
      search=["pav bun"], image_queries=["pav bun pack"],
      related=["Modern Pav Bread", "Burger Buns"]),
    P("Hot Dog Bun", "Harvest Gold", "Bakery", [("4 pcs", 50, 200, "g")],
      "Elongated hot-dog buns.",
      subcategory="Bun", ingredient_tags=["bun", "hot dog"],
      search=["hot dog bun"], image_queries=["hot dog bun pack"],
      related=["Burger Buns", "Garlic Bread"]),
    P("Sweet Bun", "Modern", "Bakery", [("4 pcs", 45, 200, "g")],
      "Sweet honey-glazed buns.",
      subcategory="Bun", ingredient_tags=["bun", "sweet"],
      search=["atta khari"], image_queries=["atta khari puff pack"],
      related=["Khari Puff", "Veg Puff"]),
    P("Cake Rusk", "Britannia", "Bakery", [("200 g", 50, 200, "g")],
      "Twice-baked cake rusk.",
      subcategory="Rusk", ingredient_tags=["rusk", "cake"],
      search=["cake rusk"], image_queries=["cake rusk pack"],
      related=["Premium Rusk", "Cookies"]),
    P("Jeera Cookies", "The Baker's Dozen", "Bakery", [("200 g", 90, 200, "g")],
      "Cumin-flavoured cookies.",
      subcategory="Cookies", veg=True, ingredient_tags=["cookies", "jeera"],
      search=[" is", "jeera cookies"], image_queries=["jeera cookies pack"],
      related=["Cookies", "Atta Cookies"]),
    P("Atta Cookies", "The Baker's Dozen", "Bakery", [("200 g", 90, 200, "g")],
      "Wholewheat atta cookies.",
      subcategory="Cookies", veg=True, ingredient_tags=["cookies", "atta"],
      search=["atta cookies"], image_queries=["atta cookies pack"],
      related=["Jeera Cookies", "Cookies"]),
    P("Bread Improver", "Modern", "Bakery", [("100 g", 40, 100, "g")],
      "Home bread-making improver.",
      subcategory="Mix", ingredient_tags=["bread", "mix"],
      search=["bread improver"], image_queries=["bread improver pack"],
      related=["Whole Wheat Bread", "Multigrain Bread"]),
    P("Mini Pizza Base", "Harvest Gold", "Bakery", [("4 pcs", 80, 200, "g")],
      "Ready-to-bake pizza bases, pack of 4.",
      subcategory="Bread", ingredient_tags=["pizza", "base"],
      search=["pizza base"], image_queries=["pizza base pack"],
      related=["Garlic Bread", "Burger Buns"]),
    P("Stuffed Kulcha", "The Baker's Dozen", "Bakery", [("4 pcs", 110, 200, "g")],
      "Amritsari stuffed kulcha.",
      subcategory="Bread", ingredient_tags=["kulcha", "bread"],
      search=["kulcha"], image_queries=["stuffed kulcha pack"],
      related=["Garlic Bread", "Multigrain Bread"]),
    P("Chocolate Bread", "The Baker's Dozen", "Bakery", [("400 g", 70, 400, "g")],
      "Cocoa-swirl soft bread loaf.",
      subcategory="Bread", ingredient_tags=["bread", "chocolate"],
      search=["chocolate bread"], image_queries=["chocolate bread pack"],
      related=["Fruit Bread", "Fruit Cake"]),
    P("Ragi Bread", "Harvest Gold", "Bakery", [("400 g", 65, 400, "g")],
      "Finger-millet healthy bread.",
      subcategory="Bread", veg=True, ingredient_tags=["bread", "ragi"],
      search=["ragi bread"], image_queries=["ragi bread pack"],
      related=["Multigrain Bread", "Brown Bread Loaf"]),
    P("Burger Bun", "Harvest Gold", "Bakery", [("4 pcs", 45, 200, "g")],
      "Sesame-topped burger buns, pack of 4.",
      subcategory="Bun", ingredient_tags=["bun", "burger"],
      search=["burger bun"], image_queries=["burger bun pack"],
      related=["Burger Buns", "Hot Dog Bun"]),
    P("Cheese Garlic Bread", "The Baker's Dozen", "Bakery", [("200 g", 110, 200, "g")],
      "Cheese and garlic pull-apart bread.",
      subcategory="Bread", ingredient_tags=["bread", "cheese"],
      search=["cheese garlic bread"], image_queries=["cheese garlic bread pack"],
      related=["Garlic Bread", "Cheese Slices"]),
    P("Choco Chip Muffin", "The Baker's Dozen", "Bakery", [("4 pcs", 150, 200, "g")],
      "Eggless choco-chip muffins.",
      subcategory="Pastry", ingredient_tags=["muffin", "chocolate"],
      search=["choco chip muffin"], image_queries=["choco chip muffin pack"],
      related=["Chocolate Muffin", "Cupcake"]),
    P("Honey Cake", "Monginis", "Bakery", [("500 g", 220, 500, "g")],
      "Soft honey-soaked sponge.",
      subcategory="Cake", ingredient_tags=["cake", "honey"],
      search=["honey cake"], image_queries=["honey cake pack"],
      related=["Fruit Cake", "Plum Cake"]),
    P("Butter Cookies", "The Baker's Dozen", "Bakery", [("200 g", 95, 200, "g")],
      "Rich butter cookies.",
      subcategory="Cookies", ingredient_tags=["cookies", "butter"],
      search=["butter cookies"], image_queries=["butter cookies pack"],
      related=["Cookies", "Atta Cookies"]),
    P("Tutti Frutti Cake", "Monginis", "Bakery", [("500 g", 230, 500, "g")],
      "Cake studded with tutti-frutti.",
      subcategory="Cake", ingredient_tags=["cake", "tutti frutti"],
      search=["tutti frutti cake"], image_queries=["tutti frutti cake pack"],
      related=["Fruit Cake", "Honey Cake"]),
    P("Dinner Rolls", "Harvest Gold", "Bakery", [("6 pcs", 50, 200, "g")],
      "Soft dinner rolls, pack of 6.",
      subcategory="Bun", ingredient_tags=["roll", "bun"],
      search=["dinner rolls"], image_queries=["dinner rolls pack"],
      related=["Pav Bun", "Burger Bun"]),
    P("Pita Bread", "The Baker's Dozen", "Bakery", [("4 pcs", 70, 200, "g")],
      "Middle-eastern flatbread.",
      subcategory="Bread", veg=True, ingredient_tags=["pita", "bread"],
      search=["pita bread"], image_queries=["pita bread pack"],
      related=["Garlic Bread", "Multigrain Bread"]),
    P("Naan", "The Baker's Dozen", "Bakery", [("4 pcs", 90, 200, "g")],
      "Tandoori naan, ready to heat.",
      subcategory="Bread", ingredient_tags=["naan", "bread"],
      search=["naan", "tandoori naan"], image_queries=["naan pack"],
      related=["Stuffed Kulcha", "Garlic Bread"]),
    P("Kulhad Chai Bun", "Modern", "Bakery", [("4 pcs", 50, 200, "g")],
      "Tea-time masala buns.",
      subcategory="Bun", ingredient_tags=["bun", "tea"],
      search=["chai bun"], image_queries=["chai bun pack"],
      related=["Sweet Bun", "Pav Bun"]),
    P("Chocolate Donut", "Monginis", "Bakery", [("4 pcs", 130, 200, "g")],
      "Chocolate-frosted donuts.",
      subcategory="Pastry", ingredient_tags=["donut", "chocolate"],
      search=["chocolate donut"], image_queries=["chocolate donut pack"],
      related=["Donut", "Cupcake"]),
    P("Walnut Brownie", "Monginis", "Bakery", [("4 pcs", 160, 200, "g")],
      "Fudgy walnut brownies.",
      subcategory="Pastry", ingredient_tags=["brownie", "walnut"],
      search=["atta khari"], image_queries=["atta khari puff pack"],
      related=["Khari Puff", "Veg Puff"]),
    P("Cheese Straws", "The Baker's Dozen", "Bakery", [("200 g", 110, 200, "g")],
      "Cheese-flavoured pastry straws.",
      subcategory="Pastry", ingredient_tags=["cheese", "straws"],
      search=["cheese straws"], image_queries=["cheese straws pack"],
      related=["Cheese Garlic Bread", "Cheese Slices"]),
    P("Bread Loaf White", "Modern", "Bakery", [("400 g", 45, 400, "g")],
      "Classic white sandwich loaf.",
      subcategory="Bread", ingredient_tags=["bread", "white"],
      search=["white bread loaf"], image_queries=["white bread loaf pack"],
      related=["Sandwich White Bread", "Whole Wheat Bread"]),
    P("Garlic Knots", "The Baker's Dozen", "Bakery", [("4 pcs", 100, 200, "g")],
      "Twisted garlic bread knots.",
      subcategory="Bread", ingredient_tags=["bread", "garlic"],
      search=["garlic knots"], image_queries=["garlic knots pack"],
      related=["Garlic Bread", "Cheese Garlic Bread"]),
    P("Blueberry Muffin", "The Baker's Dozen", "Bakery", [("4 pcs", 150, 200, "g")],
      "Eggless blueberry muffins.",
      subcategory="Pastry", ingredient_tags=["muffin", "blueberry"],
      search=["blueberry muffin"], image_queries=["blueberry muffin pack"],
      related=["Choco Chip Muffin", "Cupcake"]),
    P("Rusk Wheat", "Britannia", "Bakery", [("200 g", 50, 200, "g")],
      "Crunchy wheat rusk toast, pack of 4.",
      subcategory="Rusk", ingredient_tags=["rusk", "wheat"],
      search=["wheat rusk"], image_queries=["wheat rusk pack"],
      related=["Premium Rusk", "Cake Rusk"]),
]

# Oils & Ghee (need ~39) ------------------------------------------------------ #
OILS = [
    P("Mustard Oil", "Fortune", "Oil & Ghee", [("1 L", 150, 1000, "ml")],
      "Pungent kachi ghani mustard oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "mustard"],
      search=["mustard oil", "fortune mustard"], image_queries=["fortune mustard oil pack"],
      related=["Fortune Kachi Ghani Mustard Oil", "Saffola Gold Refined Oil"]),
    P("Sesame Oil", "Idhayam", "Oil & Ghee", [("500 ml", 200, 500, "ml")],
      "Cold-pressed gingelly oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "sesame"],
      search=["sesame oil", "gingelly"], image_queries=["idhayam sesame oil pack"],
      related=["Coconut Oil", "Groundnut Oil"]),
    P("Groundnut Oil", "Groundnut", "Oil & Ghee", [("1 L", 160, 1000, "ml")],
      "Cold-pressed groundnut oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "groundnut"],
      search=["groundnut oil"], image_queries=["groundnut oil pack"],
      related=["used", "sesame"]),
    P("Olive Oil", "Figaro", "Oil & Ghee", [("500 ml", 350, 500, "ml")],
      "Extra-virgin olive oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "olive"],
      search=["olive oil", "figaro"], image_queries=["figaro olive oil pack"],
      related=["Coconut Oil", "Sesame Oil"]),
    P("Rice Bran Oil", "Fortune", "Oil & Ghee", [("1 L", 140, 1000, "ml")],
      "Heart-friendly rice bran oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "rice bran"],
      search=["rice bran oil"], image_queries=["fortune rice bran oil pack"],
      related=["Fortune Sunlite Refined Sunflower Oil", "Saffola Gold Refined Oil"]),
    P("Soya Oil", "Fortune", "Oil & Ghee", [("1 L", 130, 1000, "ml")],
      "Refined soya bean oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "soya"],
      search=["soya oil"], image_queries=["fortune soya oil pack"],
      related=["Rice Bran Oil", "Refined Sunflower Oil"]),
    P("Pomace Olive Oil", "Figaro", "Oil & Ghee", [("1 L", 600, 1000, "ml")],
      "Light pomace olive oil for frying.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "olive"],
      search=["pomace olive oil"], image_queries=["figaro pomace olive oil pack"],
      related=["Olive Oil", "Rice Bran Oil"]),
    P("Sunflower Oil", "Saffola", "Oil & Ghee", [("1 L", 150, 1000, "ml")],
      "Refined sunflower oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "sunflower"],
      search=["sunflower oil", "saffola"], image_queries=["saffola sunflower oil pack"],
      related=["Saffola Gold Refined Oil", "Fortune Sunlite Refined Sunflower Oil"]),
    P("Canola Oil", "Fortune", "Oil & Ghee", [("1 L", 145, 1000, "ml")],
      "Light and healthy refined canola oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "canola"],
      search=["canola oil"], image_queries=["fortune canola oil pack"],
      related=["Rice Bran Oil", "Soya Oil"]),
    P("Palm Oil", "Fortune", "Oil & Ghee", [("1 L", 120, 1000, "ml")],
      "Refined palm olein cooking oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "palm"],
      search=["palm oil"], image_queries=["fortune palm oil pack"],
      related=["Soya Oil", "Rice Bran Oil"]),
    P("Vanaspati", "Gagan", "Oil & Ghee", [("1 L", 110, 1000, "ml")],
      "Hydrogenated vanaspati ghee.",
      subcategory="Ghee", ingredient_tags=["vanaspati", "ghee"],
      search=["vanaspati", "ghee"], image_queries=["vanaspati pack"],
      related=["Dalda", "Amul Pure Ghee"]),
    P("Dalda", "HUL", "Oil & Ghee", [("1 L", 120, 1000, "ml")],
      "Classic vanaspati for sweets.",
      subcategory="Ghee", ingredient_tags=["vanaspati", "ghee"],
      search=["dalda"], image_queries=["dalda vanaspati pack"],
      related=["Vanaspati", "Amul Pure Ghee"]),
    P("Ghee pouch", "Amul", "Oil & Ghee", [("200 ml", 140, 200, "ml")],
      "Pure ghee in a pouch.",
      subcategory="Ghee", ingredient_tags=["ghee", "amul"],
      search=["amul ghee pouch"], image_queries=["amul ghee pouch pack"],
      related=["Amul Pure Ghee", "Cow Ghee"]),
    P("Cow Ghee", "Patanjali", "Oil & Ghee", [("500 ml", 320, 500, "ml")],
      "A2 cow ghee, ayurvedic.",
      subcategory="Ghee", veg=True, ingredient_tags=["ghee", "cow"],
      search=["cow ghee", "patanjali"], image_queries=["patanjali cow ghee pack"],
      related=["Amul Pure Ghee", "Ghee pouch"]),
    P("Desi Ghee", "Mother Dairy", "Oil & Ghee", [("500 ml", 330, 500, "ml")],
      "Traditional desi cow ghee.",
      subcategory="Ghee", ingredient_tags=["ghee", "desi"],
      search=["desi ghee"], image_queries=["mother dairy ghee pack"],
      related=["Cow Ghee", "Amul Pure Ghee"]),
    P("Buffalo Ghee", "Nandini", "Oil & Ghee", [("500 ml", 340, 500, "ml")],
      "Rich and aromatic buffalo ghee.",
      subcategory="Ghee", ingredient_tags=["ghee", "buffalo"],
      search=["buffalo ghee", "nandini"], image_queries=["nandini ghee pack"],
      related=["Desi Ghee", "Cow Ghee"]),
    P("Filtered Groundnut Oil", "Woodpress", "Oil & Ghee", [("1 L", 280, 1000, "ml")],
      "Wood-pressed filtered groundnut oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "groundnut"],
      search=["wood pressed oil"], image_queries=["wood pressed groundnut oil pack"],
      related=["Groundnut Oil", "Sesame Oil"]),
    P("Cold Pressed Coconut Oil", "Maxcare", "Oil & Ghee", [("500 ml", 220, 500, "ml")],
      "Unrefined cold-pressed coconut oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "coconut"],
      search=["cold pressed coconut oil"], image_queries=["cold pressed coconut oil pack"],
      related=["Coconut Oil", "Filtered Groundnut Oil"]),
    P("Garlic Infused Oil", "Leonardo", "Oil & Ghee", [("250 ml", 200, 250, "ml")],
      "Garlic-infused olive oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "garlic"],
      search=["garlic oil"], image_queries=["garlic infused oil pack"],
      related=["Olive Oil", "Sesame Oil"]),
    P("Spray Oil", "Fortune", "Oil & Ghee", [("200 ml", 120, 200, "ml")],
      "Calorie-controlled spray oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "spray"],
      search=["spray oil"], image_queries=["spray oil pack"],
      related=["Olive Oil", "Rice Bran Oil"]),
    P("Pan Spray", "Fortune", "Oil & Ghee", [("200 ml", 130, 200, "ml")],
      "Non-stick cooking spray.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "spray"],
      search=["cooking spray"], image_queries=["cooking spray pack"],
      related=["Spray Oil", "Olive Oil"]),
    P("Vinegar Oil", "Figaro", "Oil & Ghee", [("250 ml", 150, 250, "ml")],
      "Salad oil with vinegar.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "salad"],
      search=["salad oil"], image_queries=["salad oil pack"],
      related=["Olive Oil", "Spray Oil"]),
    P("Grapeseed Oil", "Leonardo", "Oil & Ghee", [("500 ml", 400, 500, "ml")],
      "Light grapeseed cooking oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "grapeseed"],
      search=["grapeseed oil"], image_queries=["grapeseed oil pack"],
      related=["Olive Oil", "Sesame Oil"]),
    P("Avocado Oil", "Leonardo", "Oil & Ghee", [("500 ml", 500, 500, "ml")],
      "Cold-pressed avocado oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "avocado"],
      search=["avocado oil"], image_queries=["avocado oil pack"],
      related=["Olive Oil", "Grapeseed Oil"]),
    P("Flaxseed Oil", "Leonardo", "Oil & Ghee", [("250 ml", 300, 250, "ml")],
      "Omega-rich flaxseed oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "flaxseed"],
      search=["flaxseed oil"], image_queries=["flaxseed oil pack"],
      related=["Olive Oil", "Avocado Oil"]),
    P("Butter", "Amul", "Oil & Ghee", [("100 g", 58, 100, "g")],
      "Salted butter for cooking.",
      subcategory="Ghee", ingredient_tags=["butter", "amul"],
      search=["amul butter"], image_queries=["amul butter pack 100 g"],
      related=["Ghee pouch", "Amul Cheese Slices"]),
    P("White Butter", "Amul", "Oil & Ghee", [("100 g", 60, 100, "g")],
      "Unsalted white butter.",
      subcategory="Ghee", ingredient_tags=["butter", "white"],
      search=["white butter"], image_queries=["amul white butter pack"],
      related=["Butter", "Amul Pure Ghee"]),
    P("Cooking Butter", "Britannia", "Oil & Ghee", [("100 g", 55, 100, "g")],
      "Table and cooking butter.",
      subcategory="Ghee", ingredient_tags=["butter"],
      search=["britannia butter"], image_queries=["britannia butter pack"],
      related=["Butter", "Cheese Slices"]),
    P("Ghee Tin", "Patanjali", "Oil & Ghee", [("1 L", 620, 1000, "ml")],
      "Pure A2 cow ghee in a tin.",
      subcategory="Ghee", veg=True, ingredient_tags=["ghee", "cow"],
      search=["ghee tin"], image_queries=["patanjali ghee tin pack"],
      related=["Cow Ghee", "Desi Ghee"]),
    P("Filtered Sesame Oil", "Woodpress", "Oil & Ghee", [("500 ml", 260, 500, "ml")],
      "Wood-pressed sesame oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "sesame"],
      search=["wood pressed sesame oil"], image_queries=["wood pressed sesame oil pack"],
      related=["Sesame Oil", "Cold Pressed Coconut Oil"]),
    P("Refined Cottonseed Oil", "Fortune", "Oil & Ghee", [("1 L", 125, 1000, "ml")],
      "Refined cottonseed oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "cottonseed"],
      search=["cottonseed oil"], image_queries=["cottonseed oil pack"],
      related=["Soya Oil", "Palm Oil"]),
    P("Emu Oil", "Figaro", "Oil & Ghee", [("100 ml", 500, 100, "ml")],
      "Massage and cooking emu oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "emu"],
      search=["emu oil"], image_queries=["emu oil pack"],
      related=["Olive Oil", "Flaxseed Oil"]),
    P("Gingerly Oil", "Idhayam", "Oil & Ghee", [("1 L", 240, 1000, "ml")],
      "Bulk pack of pure gingelly (sesame) oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "sesame"],
      search=["gingerly oil"], image_queries=["idhayam gingelly oil tin pack"],
      related=["Sesame Oil", "Groundnut Oil"]),
    P("Corn Oil", "Saffola", "Oil & Ghee", [("1 L", 160, 1000, "ml")],
      "Refined and light corn oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "corn"],
      search=["corn oil"], image_queries=["saffola corn oil pack"],
      related=["Rice Bran Oil", "Sunflower Oil"]),
    P("Blended Oil", "Fortune", "Oil & Ghee", [("1 L", 155, 1000, "ml")],
      "Refined blended health oil.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "blend"],
      search=["blended oil"], image_queries=["fortune blended oil pack"],
      related=["Rice Bran Oil", "Soya Oil"]),
    P("Olive Pomace Tin", "Figaro", "Oil & Ghee", [("5 L", 2800, 5000, "ml")],
      "Bulk pomace olive oil.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "olive"],
      search=["olive oil tin"], image_queries=["figaro olive oil tin pack"],
      related=["Pomace Olive Oil", "Olive Oil"]),
    P("Cooking Ghee", "Gagan", "Oil & Ghee", [("1 L", 520, 1000, "ml")],
      "Pure traditional cooking ghee.",
      subcategory="Ghee", ingredient_tags=["ghee"],
      search=["cooking ghee"], image_queries=["cooking ghee pack"],
      related=["Vanaspati", "Desi Ghee"]),
    P("Spreadable Butter", "Amul", "Oil & Ghee", [("100 g", 65, 100, "g")],
      "Light spreadable butter.",
      subcategory="Ghee", ingredient_tags=["butter", "spreadable"],
      search=["spreadable butter"], image_queries=["amul spreadable butter pack"],
      related=["Butter", "White Butter"]),
    P("Clarified Butter", "Patanjali", "Oil & Ghee", [("500 ml", 300, 500, "ml")],
      "Traditional clarified butter.",
      subcategory="Ghee", veg=True, ingredient_tags=["ghee", "clarified"],
      search=["clarified butter"], image_queries=["patanjali clarified butter pack"],
      related=["Cow Ghee", "Ghee Tin"]),
    P("Sunflower Tin", "Saffola", "Oil & Ghee", [("5 L", 720, 5000, "ml")],
      "Bulk sunflower oil tin.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "sunflower"],
      search=["sunflower oil tin"], image_queries=["saffola sunflower oil tin pack"],
      related=["Sunflower Oil", "Corn Oil"]),
    P("Mustard Oil Pouch", "Fortune", "Oil & Ghee", [("500 ml", 80, 500, "ml")],
      "Mustard oil in a pouch.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "mustard"],
      search=["mustard oil pouch"], image_queries=["fortune mustard oil pouch pack"],
      related=["Mustard Oil", "Kachi Ghani Mustard Oil"]),
    P("Coconut Tin", "Parachute", "Oil & Ghee", [("5 L", 1700, 5000, "ml")],
      "Bulk coconut oil tin.",
      subcategory="Cooking Oil", ingredient_tags=["oil", "coconut"],
      search=["coconut oil tin"], image_queries=["parachute coconut oil tin pack"],
      related=["Coconut Oil", "Cold Pressed Coconut Oil"]),
    P("Sesame Tin", "Idhayam", "Oil & Ghee", [("5 L", 2400, 5000, "ml")],
      "Bulk sesame oil tin.",
      subcategory="Cooking Oil", veg=True, ingredient_tags=["oil", "sesame"],
      search=["sesame oil tin"], image_queries=["idhayam sesame oil tin pack"],
      related=["Sesame Oil", "Gingerly Oil"]),
    P("Ghee Jar", "Mother Dairy", "Oil & Ghee", [("1 L", 660, 1000, "ml")],
      "Pure desi ghee in a jar.",
      subcategory="Ghee", ingredient_tags=["ghee"],
      search=["ghee jar"], image_queries=["mother dairy ghee jar pack"],
      related=["Desi Ghee", "Ghee Tin"]),
]

# Tea & Coffee (need ~38) ----------------------------------------------------- #
TEA = [
    P("Lipton Yellow Label", "Lipton", "Tea & Coffee", [("500 g", 250, 500, "g")],
      "Strong Assam-CTC yellow-label tea.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["lipton yellow label", "tea"], image_queries=["lipton yellow label pack"],
      related=["Tata Tea Premium", "Brooke Bond Red Label"]),
    P("Tata Tea Gold Leaf", "Tata", "Tea & Coffee", [("250 g", 140, 250, "g")],
      "Everyday gold-leaf tea.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["tata tea gold leaf"], image_queries=["tata tea gold leaf pack"],
      related=["Tata Tea Gold", "Tata Tea Premium"]),
    P("Tata Tea Agni", "Tata", "Tea & Coffee", [("500 g", 200, 500, "g")],
      "Extra-strong tea for milk chai.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["tata tea agni"], image_queries=["tata tea agni pack"],
      related=["Tata Tea Premium", "Brooke Bond Red Label"]),
    P("Red Label 100", "Brooke Bond", "Tea & Coffee", [("250 g", 130, 250, "g")],
      "Premium long-leaf red label.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["red label 100"], image_queries=["brooke bond red label 100 pack"],
      related=["Brooke Bond Red Label Tea", "Tata Tea Premium"]),
    P("Green Tea Immunity", "Lipton", "Tea & Coffee", [("25 bags", 160, 50, "g")],
      "Tulsi and ginger green tea.",
      subcategory="Tea", veg=True, ingredient_tags=["green tea", "tea"],
      search=["green tea immunity"], image_queries=["lipton green tea immunity pack"],
      related=["Green Tea Lemon", "Tata Tea Premium"]),
    P("Green Tea Detox", "Lipton", "Tea & Coffee", [("25 bags", 160, 50, "g")],
      "Honey-lemon detox green tea.",
      subcategory="Tea", veg=True, ingredient_tags=["green tea", "tea"],
      search=["green tea detox"], image_queries=["lipton green tea detox pack"],
      related=["Green Tea Lemon", "Green Tea Immunity"]),
    P("Chai Masala", "Tata", "Tea & Coffee", [("100 g", 70, 100, "g")],
      "Spiced chai masala mix.",
      subcategory="Tea", ingredient_tags=["chai masala", "masala"],
      search=["chai masala"], image_queries=["tata chai masala pack"],
      related=["Garam Masala", "Tata Tea Premium"]),
    P("Masala Chai Bags", "Tetley", "Tea & Coffee", [("25 bags", 110, 50, "g")],
      "Cardamom masala chai bags.",
      subcategory="Tea", ingredient_tags=["tea", "masala chai"],
      search=["masala chai", "tetley"], image_queries=["tetley masala chai pack"],
      related=["Tata Tea Premium", "Chai Masala"]),
    P("Elaichi Chai", "Tetley", "Tea & Coffee", [("25 bags", 120, 50, "g")],
      "Cardamom-flavoured tea bags.",
      subcategory="Tea", ingredient_tags=["tea", "elaichi"],
      search=["elaichi chai"], image_queries=["tetley elaichi chai pack"],
      related=["Masala Chai Bags", "Tata Tea Gold"]),
    P("Ginger Tea", "Tetley", "Tea & Coffee", [("25 bags", 120, 50, "g")],
      "Adrak-flavoured tea bags.",
      subcategory="Tea", ingredient_tags=["tea", "ginger"],
      search=["ginger tea"], image_queries=["tetley ginger tea pack"],
      related=["Elaichi Chai", "Tata Tea Premium"]),
    P("Kashmiri Kahwa", "Wagh Bakri", "Tea & Coffee", [("100 g", 120, 100, "g")],
      "Saffron almond green-tea kahwa.",
      subcategory="Tea", ingredient_tags=["kahwa", "tea"],
      search=["kashmiri kahwa"], image_queries=["kashmiri kahwa pack"],
      related=["Green Tea Lemon", "Tata Tea Gold"]),
    P("Lemongrass Tea", "Wagh Bakri", "Tea & Coffee", [("100 g", 110, 100, "g")],
      "Lemongrass herbal tea.",
      subcategory="Tea", veg=True, ingredient_tags=["herbal tea", "tea"],
      search=["lemongrass tea"], image_queries=["lemongrass tea pack"],
      related=["Kashmiri Kahwa", "Green Tea Detox"]),
    P("Tulsi Tea", "Organic India", "Tea & Coffee", [("25 bags", 180, 50, "g")],
      "Holy-basil tulsi tea.",
      subcategory="Tea", veg=True, ingredient_tags=["tulsi tea", "tea"],
      search=["tulsi tea", "organic india"], image_queries=["organic india tulsi tea pack"],
      related=["Green Tea Immunity", "Lemongrass Tea"]),
    P("Peppermint Tea", "Organic India", "Tea & Coffee", [("25 bags", 180, 50, "g")],
      "Cooling peppermint infusion.",
      subcategory="Tea", veg=True, ingredient_tags=["peppermint tea", "tea"],
      search=["peppermint tea"], image_queries=["organic india peppermint tea pack"],
      related=["Tulsi Tea", "Green Tea Detox"]),
    P("Filter Coffee", "Bru", "Tea & Coffee", [("200 g", 140, 200, "g")],
      "South-Indian filter coffee powder.",
      subcategory="Coffee", ingredient_tags=["coffee", "filter"],
      search=["filter coffee", "bru"], image_queries=["bru filter coffee pack"],
      related=["Bru Instant Coffee", "Instant Coffee"]),
    P("Bru Gold", "HUL", "Tea & Coffee", [("200 g", 230, 200, "g")],
      "Premium Bru gold instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["bru gold"], image_queries=["bru gold jar pack"],
      related=["Bru Instant Coffee", "Nescafe Gold"]),
    P("Nescafe Gold", "Nestle", "Tea & Coffee", [("100 g", 280, 100, "g")],
      "Premium freeze-dried coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["nescafe gold"], image_queries=["nescafe gold jar pack"],
      related=["Instant Coffee", "Bru Gold"]),
    P("Nescafe Classic", "Nestle", "Tea & Coffee", [("100 g", 210, 100, "g")],
      "Everyday classic instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["nescafe classic"], image_queries=["nescafe classic jar pack"],
      related=["Instant Coffee", "Nescafe Gold"]),
    P("Davidoff Espresso", "Davidoff", "Tea & Coffee", [("100 g", 450, 100, "g")],
      "Rich espresso instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "espresso"],
      search=["davidoff coffee"], image_queries=["davidoff espresso pack"],
      related=["Nescafe Gold", "Bru Gold"]),
    P("Cold Coffee Sachet", "Nestle", "Tea & Coffee", [("5 sachets", 30, 50, "g")],
      "Single-serve cold coffee mix.",
      subcategory="Coffee", ingredient_tags=["coffee", "cold"],
      search=["cold coffee sachet"], image_queries=["nescafe cold coffee sachet pack"],
      related=["Nescafe Classic", "Cold Coffee"]),
    P("Cappuccino Sachet", "Nescafe", "Tea & Coffee", [("5 sachets", 50, 50, "g")],
      "Cappuccino instant mix.",
      subcategory="Coffee", ingredient_tags=["coffee", "cappuccino"],
      search=["cappuccino"], image_queries=["nescafe cappuccino sachet pack"],
      related=["Nescafe Gold", "Cold Coffee Sachet"]),
    P("Decaf Coffee", "Nescafe", "Tea & Coffee", [("100 g", 300, 100, "g")],
      "Caffeine-free instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "decaf"],
      search=["decaf coffee"], image_queries=["nescafe decaf pack"],
      related=["Nescafe Gold", "Davidoff Espresso"]),
    P("Coffee Beans", "Blue Tokai", "Tea & Coffee", [("250 g", 450, 250, "g")],
      "Roasted Indian arabica beans.",
      subcategory="Coffee", veg=True, ingredient_tags=["coffee", "beans"],
      search=["coffee beans", "blue tokai"], image_queries=["blue tokai beans pack"],
      related=["Filter Coffee", "Nescafe Gold"]),
    P("French Press Coffee", "Blue Tokai", "Tea & Coffee", [("250 g", 480, 250, "g")],
      "Coarse-ground press coffee.",
      subcategory="Coffee", veg=True, ingredient_tags=["coffee", "ground"],
      search=["french press coffee"], image_queries=["blue tokai ground coffee pack"],
      related=["Coffee Beans", "Filter Coffee"]),
    P("Tea Dust", "Wagh Bakri", "Tea & Coffee", [("500 g", 180, 500, "g")],
      "Fine CTC tea dust for strong chai.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["tea dust"], image_queries=["wagh bakri tea dust pack"],
      related=["Wagh Bakri Tea", "Tata Tea Premium"]),
    P("Leaf Tea", "Lipton", "Tea & Coffee", [("500 g", 240, 500, "g")],
      "Long-leaf orthodox tea.",
      subcategory="Tea", ingredient_tags=["tea", "leaf"],
      search=["leaf tea", "lipton"], image_queries=["lipton leaf tea pack"],
      related=["Lipton Yellow Label", "Tata Tea Gold"]),
    P("Salem Tea", "Brooke Bond", "Tea & Coffee", [("500 g", 210, 500, "g")],
      "South-Indian Salem tea.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["salem tea"], image_queries=["brooke bond salem tea pack"],
      related=["Brooke Bond Red Label Tea", "Tata Tea Agni"]),
    P("Nilgiri Tea", "Wagh Bakri", "Tea & Coffee", [("500 g", 220, 500, "g")],
      "Fragrant Nilgiri leaf tea.",
      subcategory="Tea", ingredient_tags=["tea", "nilgiri"],
      search=["nilgiri tea"], image_queries=["nilgiri tea pack"],
      related=["Salem Tea", "Green Tea Lemon"]),
    P("Assam Tea", "Tata", "Tea & Coffee", [("500 g", 230, 500, "g")],
      "Single-origin Assam black tea.",
      subcategory="Tea", ingredient_tags=["tea", "assam"],
      search=["assam tea"], image_queries=["tata assam tea pack"],
      related=["Tata Tea Premium", "Tata Tea Agni"]),
    P("Darjeeling Tea", "Tata", "Tea & Coffee", [("500 g", 320, 500, "g")],
      "First-flush Darjeeling tea.",
      subcategory="Tea", ingredient_tags=["tea", "darjeeling"],
      search=["darjeeling tea"], image_queries=["tata darjeeling tea pack"],
      related=["Assam Tea", "Green Tea Lemon"]),
    P("Masala Chai Premix", "Wagh Bakri", "Tea & Coffee", [("100 g", 90, 100, "g")],
      "Instant masala chai premix.",
      subcategory="Tea", ingredient_tags=["chai", "premix"],
      search=["masala chai premix"], image_queries=["masala chai premix pack"],
      related=["Chai Masala", "Tata Tea Premium"]),
    P("Ginger Tea Bags", "Lipton", "Tea & Coffee", [("25 bags", 120, 50, "g")],
      "Adrak ginger tea bags.",
      subcategory="Tea", ingredient_tags=["tea", "ginger"],
      search=["ginger tea bags"], image_queries=["lipton ginger tea bags pack"],
      related=["Ginger Tea", "Elaichi Chai"]),
    P("Hibiscus Tea", "Organic India", "Tea & Coffee", [("25 bags", 190, 50, "g")],
      "Tart hibiscus herbal tea.",
      subcategory="Tea", veg=True, ingredient_tags=["herbal tea", "tea"],
      search=["hibiscus tea"], image_queries=["organic india hibiscus tea pack"],
      related=["Tulsi Tea", "Peppermint Tea"]),
    P("Green Tea Honey", "Lipton", "Tea & Coffee", [("25 bags", 160, 50, "g")],
      "Honey-lemon green tea.",
      subcategory="Tea", veg=True, ingredient_tags=["green tea", "tea"],
      search=["green tea honey"], image_queries=["lipton green tea honey pack"],
      related=["Green Tea Detox", "Green Tea Lemon"]),
    P("Chamomile Tea", "Organic India", "Tea & Coffee", [("25 bags", 190, 50, "g")],
      "Soothing chamomile infusion.",
      subcategory="Tea", veg=True, ingredient_tags=["herbal tea", "tea"],
      search=["chamomile tea"], image_queries=["organic india chamomile tea pack"],
      related=["Hibiscus Tea", "Peppermint Tea"]),
    P("Cardamom Tea", "Tetley", "Tea & Coffee", [("25 bags", 130, 50, "g")],
      "Elaichi cardamom tea.",
      subcategory="Tea", ingredient_tags=["tea", "cardamom"],
      search=["cardamom tea"], image_queries=["tetley cardamom tea pack"],
      related=["Elaichi Chai", "Masala Chai Bags"]),
    P("Coffee Mix Caramel", "Nescafe", "Tea & Coffee", [("5 sachets", 55, 50, "g")],
      "Caramel cappuccino mix.",
      subcategory="Coffee", ingredient_tags=["coffee", "cappuccino"],
      search=["caramel coffee"], image_queries=["nescafe caramel coffee pack"],
      related=["Cappuccino Sachet", "Nescafe Gold"]),
    P("South Indian Filter", "Bru", "Tea & Coffee", [("200 g", 150, 200, "g")],
      "Traditional South-Indian filter blend.",
      subcategory="Coffee", ingredient_tags=["coffee", "filter"],
      search=["south indian filter coffee"], image_queries=["bru south indian filter pack"],
      related=["Filter Coffee", "Coffee Beans"]),
    P("Chai Tea Bags", "Tetley", "Tea & Coffee", [("25 bags", 110, 50, "g")],
      "Classic chai tea bags.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["chai tea bags"], image_queries=["tetley chai tea bags pack"],
      related=["Masala Chai Premix", "Tata Tea Premium"]),
    P("Lemon Tea", "Lipton", "Tea & Coffee", [("25 bags", 120, 50, "g")],
      "Refreshing lemon tea bags.",
      subcategory="Tea", veg=True, ingredient_tags=["tea", "lemon"],
      search=["lemon tea"], image_queries=["lipton lemon tea pack"],
      related=["Green Tea Lemon", "Lemongrass Tea"]),
    P("Mocha Sachet", "Nescafe", "Tea & Coffee", [("5 sachets", 55, 50, "g")],
      "Chocolate mocha coffee mix.",
      subcategory="Coffee", ingredient_tags=["coffee", "mocha"],
      search=["mocha coffee"], image_queries=["nescafe mocha sachet pack"],
      related=["Coffee Mix Caramel", "Cappuccino Sachet"]),
    P("Turmeric Tea", "Organic India", "Tea & Coffee", [("25 bags", 190, 50, "g")],
      "Haldi turmeric herbal tea.",
      subcategory="Tea", veg=True, ingredient_tags=["herbal tea", "turmeric"],
      search=["turmeric tea"], image_queries=["organic india turmeric tea pack"],
      related=["Tulsi Tea", "Lemongrass Tea"]),
    P("Rose Tea", "Wagh Bakri", "Tea & Coffee", [("100 g", 130, 100, "g")],
      "Rose-petal flavoured tea.",
      subcategory="Tea", ingredient_tags=["tea", "rose"],
      search=["rose tea"], image_queries=["rose tea pack"],
      related=["Kashmiri Kahwa", "Green Tea Honey"]),
]

# Dry Fruits & Sweeteners (need ~33) ------------------------------------------ #
DRY = [
    P("Anjeer", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 250, 200, "g")],
      "Dried figs, sweet and chewy.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["fig", "anjeer"],
      search=["anjeer", "dry fig"], image_queries=["anjeer pack"],
      related=["Happilo Walnut Kernels", "Dates Seedless"]),
    P("Apricot", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 290, 200, "g")],
      "Dried apricots, tangy and soft.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["apricot", "khubani"],
      search=["apricot", "khubani"], image_queries=["apricot pack"],
      related=["Anjeer", "Happilo Seedless Raisins"]),
    P("Prunes", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 240, 200, "g")],
      "Dried plums for digestion.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["prune", "plum"],
      search=["prunes", "dried plum"], image_queries=["prunes pack"],
      related=["Apricot", "Anjeer"]),
    P("Black Raisins", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 130, 200, "g")],
      "Seedless black raisins.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["raisins", "kismis"],
      search=["black raisins", "kismis"], image_queries=["black raisins pack"],
      related=["Happilo Seedless Raisins", "Anjeer"]),
    P("Cranberries Dried", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 320, 200, "g")],
      "Dried cranberries, tart and sweet.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["cranberry", "dry fruit"],
      search=["dried cranberries"], image_queries=["dried cranberries pack"],
      related=["Apricot", "Prunes"]),
    P("Blueberries Dried", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 450, 200, "g")],
      "Freeze-dried blueberries.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["blueberry", "dry fruit"],
      search=["dried blueberries"], image_queries=["dried blueberries pack"],
      related=["Cranberries Dried", "Apricot"]),
    P("Tutti Frutti", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 110, 200, "g")],
      "Candied mixed fruit bits.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["tutti frutti", "candy"],
      search=["tutti frutti"], image_queries=["tutti frutti pack"],
      related=["Happilo Whole Cashew W240", "Happilo California Almonds"]),
    P("Mixed Dry Fruits", "Happilo", "Dry Fruits & Sweeteners", [("500 g", 520, 500, "g")],
      "Cashew, almond, raisin and fig mix.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["dry fruit mix", "mix"],
      search=["mixed dry fruits"], image_queries=["mixed dry fruits pack"],
      related=["Happilo Whole Cashew W240", "Happilo California Almonds"]),
    P("Dates Seedless", "Happilo", "Dry Fruits & Sweeteners", [("500 g", 220, 500, "g")],
      "Seedless soft dates.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["dates", "khajur"],
      search=["dates", "khajur"], image_queries=["seedless dates pack"],
      related=["Anjeer", "Mixed Dry Fruits"]),
    P("Munakka", "Happilo", "Dry Fruits & Sweeteners", [("500 g", 260, 500, "g")],
      "Seedless black raisins for health.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["munakka", "raisin"],
      search=["munakka"], image_queries=["munakka pack"],
      related=["Black Raisins", "Dates Seedless"]),
    P("Foxnuts", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 180, 200, "g")],
      "Roasted makhana foxnuts.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["makhana", "foxnut"],
      search=["makhana", "foxnuts"], image_queries=["makhana pack"],
      related=["Peanuts Raw", "Cashew W240"]),
    P("Cashew W180", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 420, 200, "g")],
      "Large W180 whole cashews.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["cashew", "kaju"],
      search=["cashew w180", "kaju"], image_queries=["cashew w180 pack"],
      related=["Happilo Whole Cashew W240", "Happilo California Almonds"]),
    P("Pistachio Raw", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 380, 200, "g")],
      "Raw unsalted pistachios.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["pistachio", "pista"],
      search=["pistachio", "pista"], image_queries=["raw pistachio pack"],
      related=["Pistachio Salted", "Cashew W240"]),
    P("Almonds Grown", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 300, 200, "g")],
      "Grown (with skin) almonds.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["almond", "badam"],
      related=["Happilo California Almonds", "Happilo Walnut Kernels"]),
    P("Walnut Pieces", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 320, 200, "g")],
      "Broken walnut kernels.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["walnut", "akhrot"],
      search=["walnut pieces"], image_queries=["walnut pieces pack"],
      related=["Happilo Whole Cashew W240", "Happilo California Almonds"]),
    P("Raisins Green", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 140, 200, "g")],
      "Seedless green raisins.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["raisins", "kismis"],
      search=["green raisins"], image_queries=["green raisins pack"],
      related=["Happilo Whole Cashew W240", "Happilo California Almonds"]),
    P("Dried Kiwi", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 350, 200, "g")],
      "Sweet dried kiwi slices.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["kiwi", "dry fruit"],
      search=["dried kiwi"], image_queries=["dried kiwi pack"],
      related=["Apricot", "Cranberries Dried"]),
    P("Dried Mango", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 240, 200, "g")],
      "Chewy dried mango slices.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["mango", "dry fruit"],
      search=["dried mango"], image_queries=["dried mango pack"],
      related=["Dried Kiwi", "Apricot"]),
    P("Dried Pineapple", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 260, 200, "g")],
      "Sweet dried pineapple.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["pineapple", "dry fruit"],
      search=["dried pineapple"], image_queries=["dried pineapple pack"],
      related=["Dried Mango", "Cranberries Dried"]),
    P("Trail Mix", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 280, 200, "g")],
      "Nuts, seeds and dried fruit mix.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["trail mix", "mix"],
      search=["trail mix"], image_queries=["trail mix pack"],
      related=["Mixed Dry Fruits", "Foxnuts"]),
    P("Peanuts Roasted", "Happilo", "Dry Fruits & Sweeteners", [("500 g", 150, 500, "g")],
      "Lightly salted roasted peanuts.",
      subcategory="Dry Fruits", veg=True, ingredient_tags=["peanut", "groundnut"],
      search=["roasted peanuts"], image_queries=["roasted peanuts pack"],
      related=["Peanuts Raw", "Foxnuts"]),
    P("Sunflower Seeds", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 160, 200, "g")],
      "Roasted sunflower seeds.",
      subcategory="Seeds", veg=True, ingredient_tags=["sunflower seeds"],
      search=["sunflower seeds"], image_queries=["sunflower seeds pack"],
      related=["Sesame Seeds", "Foxnuts"]),
    P("Pumpkin Seeds", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 190, 200, "g")],
      "Roasted pumpkin seeds.",
      subcategory="Seeds", veg=True, ingredient_tags=["pumpkin seeds"],
      search=["pumpkin seeds"], image_queries=["pumpkin seeds pack"],
      related=["Sunflower Seeds", "Sesame Seeds"]),
    P("Flax Seeds", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 120, 200, "g")],
      "Omega-rich flax seeds.",
      subcategory="Seeds", veg=True, ingredient_tags=["flax seeds", "alsi"],
      search=["flax seeds", "alsi"], image_queries=["flax seeds pack"],
      related=["Pumpkin Seeds", "Sunflower Seeds"]),
    P("Chia Seeds", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 220, 200, "g")],
      "Hydrating chia seeds.",
      subcategory="Seeds", veg=True, ingredient_tags=["chia seeds"],
      search=["chia seeds"], image_queries=["chia seeds pack"],
      related=["Flax Seeds", "Pumpkin Seeds"]),
    P("Muskmelon Seeds", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 140, 200, "g")],
      "Roasted magaz seeds.",
      subcategory="Seeds", veg=True, ingredient_tags=["melon seeds"],
      search=["muskmelon seeds"], image_queries=["muskmelon seeds pack"],
      related=["Sunflower Seeds", "Pumpkin Seeds"]),
    P("Sugar Free Gold", "Sugar Free", "Dry Fruits & Sweeteners", [("100 pcs", 180, 20, "g")],
      "Zero-calorie sweetener tablets.",
      subcategory="Sweetener", veg=True, ingredient_tags=["sweetener", "sugar free"],
      search=["sugar free", "sweetener"], image_queries=["sugar free pack"],
      related=["Madhur Refined Sugar", "Stevia"]),
    P("Stevia", "Sugar Free", "Dry Fruits & Sweeteners", [("100 g", 250, 100, "g")],
      "Natural stevia leaves powder.",
      subcategory="Sweetener", veg=True, ingredient_tags=["stevia", "sweetener"],
      search=["stevia"], image_queries=["stevia pack"],
      related=["Sugar Free Gold", "Madhur Refined Sugar"]),
    P("Jaggery Powder", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 90, 500, "g")],
      "Finely powdered cane jaggery (gur).",
      subcategory="Jaggery", veg=True, ingredient_tags=["jaggery", "gur"],
      search=["jaggery powder", "gur"], image_queries=["jaggery powder pack"],
      related=["Jaggery", "Madhur Refined Sugar"]),
    P("Gur Block", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 100, 500, "g")],
      "Solid cane jaggery block.",
      subcategory="Jaggery", veg=True, ingredient_tags=["jaggery", "gur"],
      search=["gur block"], image_queries=["gur block pack"],
      related=["Jaggery", "Jaggery Powder"]),
    P("Palm Jaggery", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 110, 500, "g")],
      "Unrefined palm sugar.",
      subcategory="Jaggery", veg=True, ingredient_tags=["jaggery", "palm"],
      search=["palm jaggery"], image_queries=["palm jaggery pack"],
      related=["Gur Block", "Jaggery"]),
    P("Coconut Sugar", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 200, 500, "g")],
      "Low-GI coconut blossom sugar.",
      subcategory="Sweetener", veg=True, ingredient_tags=["coconut sugar", "sweetener"],
      search=["coconut sugar"], image_queries=["coconut sugar pack"],
      related=["Stevia", "Jaggery Powder"]),
    P("Mishri", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 120, 500, "g")],
      "Rock sugar crystals.",
      subcategory="Sweetener", veg=True, ingredient_tags=["mishri", "sugar"],
      search=["mishri", "rock sugar"], image_queries=["mishri pack"],
      related=["Madhur Refined Sugar", "Gur Block"]),
    P("Khandsari Sugar", "24 Mantra", "Dry Fruits & Sweeteners", [("500 g", 90, 500, "g")],
      "Unrefined khandsari sugar.",
      subcategory="Sugar", veg=True, ingredient_tags=["sugar", "khandsari"],
      search=["khandsari sugar"], image_queries=["khandsari sugar pack"],
      related=["Madhur Refined Sugar", "Mishri"]),
]
