"""The curated Indian catalog manifest — part 1: fresh produce, dairy, staples.

Every entry is a real product sold in Indian supermarkets, with its actual MRP
band as of the mid-2020s.  `ingredient_tags` are the canonical cooking
ingredients a product satisfies; the recipe gate in build.py resolves recipe
ingredients against these, so adding a recipe that needs an ingredient nobody
stocks is a build failure.
"""

from __future__ import annotations

from .schema import P

# --------------------------------------------------------------------------- #
# Fruits & Vegetables  (loose produce: sold by weight, no brand packaging)
# --------------------------------------------------------------------------- #
FRUITS_VEGETABLES = [
    # --- vegetables: the aromatics every Indian recipe starts with ---------- #
    P("Onion", "Fresh", "Fruits & Vegetables", [("500 g", 20, 500, "g"), ("1 kg", 38, 1000, "g")],
      "Everyday red onions, the base of nearly every Indian curry, sabzi and masala gravy.",
      unit="g", subcategory="Vegetables", ingredient_tags=["onion"],
      search=["pyaz", "kanda", "red onion"], shelf_life="15 days",
      image_queries=["red onion india"], related=["Tomato", "Potato", "Ginger"]),
    P("Tomato", "Fresh", "Fruits & Vegetables", [("500 g", 25, 500, "g"), ("1 kg", 45, 1000, "g")],
      "Firm ripe tomatoes for curries, dals, chutneys and salads. Naturally rich in lycopene.",
      unit="g", subcategory="Vegetables", ingredient_tags=["tomato"],
      search=["tamatar"], shelf_life="7 days",
      image_queries=["fresh tomato"], related=["Onion", "Potato"]),
    P("Potato", "Fresh", "Fruits & Vegetables", [("1 kg", 32, 1000, "g"), ("2 kg", 60, 2000, "g")],
      "All-purpose potatoes for aloo sabzi, parathas, samosas and everyday frying.",
      unit="g", subcategory="Vegetables", ingredient_tags=["potato"],
      search=["aloo", "batata"], shelf_life="30 days",
      image_queries=["potato vegetable"], related=["Onion", "Tomato"]),
    P("Ginger", "Fresh", "Fruits & Vegetables", [("100 g", 18, 100, "g"), ("250 g", 40, 250, "g")],
      "Fresh ginger root for masala bases, chai and marinades. Pungent and aromatic.",
      unit="g", subcategory="Vegetables", ingredient_tags=["ginger"],
      search=["adrak"], shelf_life="14 days",
      image_queries=["fresh ginger root"], related=["Garlic", "Green Chilli"]),
    P("Garlic", "Fresh", "Fruits & Vegetables", [("100 g", 22, 100, "g"), ("250 g", 50, 250, "g")],
      "Plump garlic bulbs for tempering, ginger-garlic paste and gravies.",
      unit="g", subcategory="Vegetables", ingredient_tags=["garlic"],
      search=["lehsun"], shelf_life="30 days",
      image_queries=["garlic bulb"], related=["Ginger", "Onion"]),
    P("Green Chilli", "Fresh", "Fruits & Vegetables", [("100 g", 15, 100, "g")],
      "Fresh green chillies for tempering, chutneys and everyday heat in Indian cooking.",
      unit="g", subcategory="Vegetables", ingredient_tags=["green chilli", "chilli"],
      search=["hari mirch"], shelf_life="10 days",
      image_queries=["green chilli india"], related=["Coriander Leaves", "Ginger"]),
    P("Coriander Leaves", "Fresh", "Fruits & Vegetables", [("100 g", 15, 100, "g")],
      "Fresh coriander (dhania patta) for garnishing dals, curries, chaat and chutneys.",
      unit="g", subcategory="Herbs", ingredient_tags=["coriander leaves", "coriander"],
      search=["dhania", "hara dhania", "cilantro"], shelf_life="5 days",
      image_queries=["coriander leaves bunch"], related=["Mint Leaves", "Green Chilli"]),
    P("Mint Leaves", "Fresh", "Fruits & Vegetables", [("100 g", 18, 100, "g")],
      "Fragrant pudina leaves for biryani, raita, chutney and summer coolers.",
      unit="g", subcategory="Herbs", ingredient_tags=["mint", "mint leaves"],
      search=["pudina"], shelf_life="5 days",
      image_queries=["mint leaves pudina"], related=["Coriander Leaves", "Curd"]),
    P("Curry Leaves", "Fresh", "Fruits & Vegetables", [("50 g", 12, 50, "g")],
      "Aromatic kadi patta, essential for South Indian tempering, sambar and rasam.",
      unit="g", subcategory="Herbs", ingredient_tags=["curry leaves"],
      search=["kadi patta", "karivepaku"], shelf_life="7 days",
      image_queries=["curry leaves fresh"], related=["Mustard Seeds", "Green Chilli"]),
    P("Spinach", "Fresh", "Fruits & Vegetables", [("250 g", 25, 250, "g")],
      "Tender palak leaves for palak paneer, dal palak and healthy everyday sabzi.",
      unit="g", subcategory="Leafy Vegetables", ingredient_tags=["spinach", "palak"],
      search=["palak"], shelf_life="4 days",
      image_queries=["spinach palak bunch"], related=["Paneer", "Methi Leaves"]),
    P("Methi Leaves", "Fresh", "Fruits & Vegetables", [("250 g", 30, 250, "g")],
      "Fresh fenugreek greens with a pleasant bitterness, for methi thepla and aloo methi.",
      unit="g", subcategory="Leafy Vegetables", ingredient_tags=["methi", "fenugreek leaves"],
      search=["methi", "fenugreek"], shelf_life="4 days",
      image_queries=["fenugreek methi leaves"], related=["Spinach", "Potato"]),
    P("Cauliflower", "Fresh", "Fruits & Vegetables", [("1 piece", 40, 800, "g")],
      "Compact white cauliflower head for gobi masala, aloo gobi and pakoras.",
      unit="piece", subcategory="Vegetables", ingredient_tags=["cauliflower"],
      search=["phool gobi", "gobi"], shelf_life="7 days",
      image_queries=["cauliflower whole"], related=["Potato", "Green Peas"]),
    P("Cabbage", "Fresh", "Fruits & Vegetables", [("1 piece", 35, 900, "g")],
      "Crisp green cabbage for stir-fried sabzi, salads and Indo-Chinese noodles.",
      unit="piece", subcategory="Vegetables", ingredient_tags=["cabbage"],
      search=["patta gobi"], shelf_life="12 days",
      image_queries=["green cabbage"], related=["Carrot", "Capsicum"]),
    P("Carrot", "Fresh", "Fruits & Vegetables", [("500 g", 30, 500, "g")],
      "Sweet red carrots for gajar halwa, pulao, salads and everyday sabzi.",
      unit="g", subcategory="Vegetables", ingredient_tags=["carrot"],
      search=["gajar"], shelf_life="14 days",
      image_queries=["carrot fresh"], related=["Green Peas", "Cabbage"]),
    P("Capsicum", "Fresh", "Fruits & Vegetables", [("250 g", 30, 250, "g")],
      "Crunchy green bell peppers for stir-fries, paneer dishes and Indo-Chinese cooking.",
      unit="g", subcategory="Vegetables", ingredient_tags=["capsicum", "bell pepper"],
      search=["shimla mirch", "bell pepper"], shelf_life="8 days",
      image_queries=["green capsicum bell pepper"], related=["Paneer", "Onion"]),
    P("Green Peas", "Fresh", "Fruits & Vegetables", [("500 g", 45, 500, "g")],
      "Sweet fresh green peas for matar paneer, pulao and winter sabzi.",
      unit="g", subcategory="Vegetables", ingredient_tags=["green peas", "peas"],
      search=["matar", "hara matar"], shelf_life="7 days",
      image_queries=["green peas pods"], related=["Paneer", "Carrot"]),
    P("Brinjal", "Fresh", "Fruits & Vegetables", [("500 g", 30, 500, "g")],
      "Glossy purple brinjal for baingan bharta, bharli vangi and sambar.",
      unit="g", subcategory="Vegetables", ingredient_tags=["brinjal", "eggplant"],
      search=["baingan", "eggplant", "vangi"], shelf_life="7 days",
      image_queries=["purple brinjal eggplant"], related=["Onion", "Tomato"]),
    P("Lady Finger", "Fresh", "Fruits & Vegetables", [("500 g", 35, 500, "g")],
      "Tender bhindi for crisp stir-fried sabzi and bharwa bhindi.",
      unit="g", subcategory="Vegetables", ingredient_tags=["okra", "lady finger"],
      search=["bhindi", "okra"], shelf_life="5 days",
      image_queries=["okra bhindi lady finger"], related=["Onion", "Besan"]),
    P("Bottle Gourd", "Fresh", "Fruits & Vegetables", [("1 piece", 35, 700, "g")],
      "Light and digestible lauki for everyday sabzi, kofta and dal.",
      unit="piece", subcategory="Vegetables", ingredient_tags=["bottle gourd", "lauki"],
      search=["lauki", "dudhi", "ghiya"], shelf_life="8 days",
      image_queries=["bottle gourd lauki"], related=["Toor Dal", "Onion"]),
    P("Cucumber", "Fresh", "Fruits & Vegetables", [("500 g", 25, 500, "g")],
      "Cool crisp cucumber for salads, raita and everyday snacking.",
      unit="g", subcategory="Vegetables", ingredient_tags=["cucumber"],
      search=["kheera", "kakdi"], shelf_life="7 days",
      image_queries=["cucumber fresh"], related=["Curd", "Tomato"]),
    P("Lemon", "Fresh", "Fruits & Vegetables", [("4 pieces", 20, 200, "g")],
      "Juicy limes for dals, salads, nimbu pani and finishing curries.",
      unit="piece", subcategory="Vegetables", ingredient_tags=["lemon", "lime"],
      search=["nimbu", "lime"], shelf_life="12 days",
      image_queries=["indian lemon lime"], related=["Green Chilli", "Coriander Leaves"]),
    P("Beetroot", "Fresh", "Fruits & Vegetables", [("500 g", 30, 500, "g")],
      "Deep red beetroot for salads, juices, poriyal and healthy everyday cooking.",
      unit="g", subcategory="Vegetables", ingredient_tags=["beetroot"],
      search=["chukandar"], shelf_life="14 days",
      image_queries=["beetroot fresh"], related=["Carrot", "Cucumber"]),
    P("Drumstick", "Fresh", "Fruits & Vegetables", [("250 g", 30, 250, "g")],
      "Tender moringa drumsticks, essential for authentic sambar and South Indian curries.",
      unit="g", subcategory="Vegetables", ingredient_tags=["drumstick"],
      search=["sahjan", "moringa", "munaga"], shelf_life="6 days",
      image_queries=["drumstick moringa vegetable"], related=["Toor Dal", "Tamarind"]),
    P("Pumpkin", "Fresh", "Fruits & Vegetables", [("500 g", 25, 500, "g")],
      "Sweet orange pumpkin for sabzi, sambar and traditional festive dishes.",
      unit="g", subcategory="Vegetables", ingredient_tags=["pumpkin"],
      search=["kaddu", "sitaphal"], shelf_life="20 days",
      image_queries=["pumpkin vegetable india"], related=["Bottle Gourd", "Toor Dal"]),
    P("Sweet Corn", "Fresh", "Fruits & Vegetables", [("2 pieces", 40, 400, "g")],
      "Juicy sweet corn cobs for bhutta, soups, salads and snacks.",
      unit="piece", subcategory="Vegetables", ingredient_tags=["corn", "sweet corn"],
      search=["bhutta", "makai"], shelf_life="6 days",
      image_queries=["sweet corn cob"], related=["Butter", "Lemon"]),

    # --- fruits ------------------------------------------------------------ #
    P("Banana", "Fresh", "Fruits & Vegetables", [("6 pieces", 40, 700, "g"), ("12 pieces", 75, 1400, "g")],
      "Ripe robusta bananas, an everyday source of instant energy and potassium.",
      unit="piece", subcategory="Fruits", ingredient_tags=["banana"],
      search=["kela"], shelf_life="5 days",
      image_queries=["banana bunch india"], related=["Milk", "Honey"]),
    P("Apple", "Fresh", "Fruits & Vegetables", [("500 g", 90, 500, "g"), ("1 kg", 175, 1000, "g")],
      "Crisp Shimla apples, sweet and juicy, ideal for eating fresh or in desserts.",
      unit="g", subcategory="Fruits", ingredient_tags=["apple"],
      search=["seb", "shimla apple"], shelf_life="15 days",
      image_queries=["red apple fruit"], related=["Banana", "Orange"]),
    P("Mango Alphonso", "Fresh", "Fruits & Vegetables", [("1 kg", 350, 1000, "g")],
      "Premium Ratnagiri Alphonso mangoes, intensely sweet with a rich saffron pulp.",
      unit="g", subcategory="Fruits", ingredient_tags=["mango"],
      search=["aam", "hapus", "alphonso"], shelf_life="6 days",
      image_queries=["alphonso mango india"], related=["Milk", "Curd"]),
    P("Pomegranate", "Fresh", "Fruits & Vegetables", [("500 g", 90, 500, "g")],
      "Ruby-red anar with juicy sweet arils, great for salads, raita and juicing.",
      unit="g", subcategory="Fruits", ingredient_tags=["pomegranate"],
      search=["anar"], shelf_life="12 days",
      image_queries=["pomegranate fruit"], related=["Apple", "Orange"]),
    P("Orange", "Fresh", "Fruits & Vegetables", [("1 kg", 80, 1000, "g")],
      "Sweet-tangy Nagpur oranges, loaded with vitamin C and easy to peel.",
      unit="g", subcategory="Fruits", ingredient_tags=["orange"],
      search=["santra", "nagpur orange"], shelf_life="10 days",
      image_queries=["nagpur orange fruit"], related=["Apple", "Banana"]),
    P("Grapes", "Fresh", "Fruits & Vegetables", [("500 g", 60, 500, "g")],
      "Seedless green grapes from Nashik, crisp and refreshingly sweet.",
      unit="g", subcategory="Fruits", ingredient_tags=["grapes"],
      search=["angoor"], shelf_life="7 days",
      image_queries=["green grapes bunch"], related=["Apple", "Pomegranate"]),
    P("Papaya", "Fresh", "Fruits & Vegetables", [("1 piece", 55, 1000, "g")],
      "Ripe red papaya, naturally sweet and rich in digestive enzymes.",
      unit="piece", subcategory="Fruits", ingredient_tags=["papaya"],
      search=["papita"], shelf_life="5 days",
      image_queries=["papaya fruit cut"], related=["Banana", "Lemon"]),
    P("Watermelon", "Fresh", "Fruits & Vegetables", [("1 piece", 70, 3000, "g")],
      "Juicy summer watermelon with crisp red flesh, perfect for beating the heat.",
      unit="piece", subcategory="Fruits", ingredient_tags=["watermelon"],
      search=["tarbooj"], shelf_life="8 days",
      image_queries=["watermelon whole"], related=["Lemon", "Grapes"]),
    P("Guava", "Fresh", "Fruits & Vegetables", [("500 g", 50, 500, "g")],
      "Crunchy Allahabadi guava, high in fibre and vitamin C. Great with chaat masala.",
      unit="g", subcategory="Fruits", ingredient_tags=["guava"],
      search=["amrud", "peru"], shelf_life="7 days",
      image_queries=["guava fruit india"], related=["Chaat Masala", "Lemon"]),
    P("Coconut", "Fresh", "Fruits & Vegetables", [("1 piece", 45, 500, "g")],
      "Whole mature coconut for chutneys, curries, festive cooking and prasad.",
      unit="piece", subcategory="Fruits", ingredient_tags=["coconut"],
      search=["nariyal", "thengai"], shelf_life="20 days",
      image_queries=["whole coconut india"], related=["Curry Leaves", "Mustard Seeds"]),
]
