"""Curated Indian catalog — part 2: dairy, staples (atta/rice/dal), oils.

Brand/MRP pairs reflect actual Indian retail: Amul and Mother Dairy for dairy,
Aashirvaad/Fortune/India Gate for staples, Fortune/Saffola/Amul for oils.
"""

from __future__ import annotations

from .schema import P

# --------------------------------------------------------------------------- #
# Dairy & Eggs
# --------------------------------------------------------------------------- #
DAIRY_EGGS = [
    P("Gold Full Cream Milk", "Amul", "Dairy & Eggs",
      [("500 ml", 34, 500, "ml"), ("1 L", 68, 1000, "ml")],
      "Homogenised full cream milk with 6% fat. Rich and creamy, ideal for chai, "
      "coffee, kheer and everyday drinking.",
      unit="ml", subcategory="Milk", ingredient_tags=["milk"],
      search=["doodh", "full cream milk", "amul gold"], shelf_life="2 days",
      image_queries=["amul gold milk pouch"], related=["Amul Butter Salted", "Amul Masti Dahi Curd"]),
    P("Taaza Toned Milk", "Amul", "Dairy & Eggs",
      [("500 ml", 28, 500, "ml"), ("1 L", 56, 1000, "ml")],
      "Toned milk with 3% fat, lighter than full cream and perfect for daily tea and coffee.",
      unit="ml", subcategory="Milk", ingredient_tags=["milk"],
      search=["doodh", "toned milk", "amul taaza"], shelf_life="2 days",
      image_queries=["amul taaza milk pouch"], related=["Amul Gold Full Cream Milk"]),
    P("Toned Milk", "Mother Dairy", "Dairy & Eggs",
      [("500 ml", 27, 500, "ml"), ("1 L", 54, 1000, "ml")],
      "Fresh toned milk, pasteurised and homogenised for consistent taste in tea and cooking.",
      unit="ml", subcategory="Milk", ingredient_tags=["milk"],
      search=["doodh", "mother dairy milk"], shelf_life="2 days",
      image_queries=["mother dairy toned milk pouch"], related=["Mother Dairy Classic Curd"]),
    P("Butter Salted", "Amul", "Dairy & Eggs",
      [("100 g", 58, 100, "g"), ("500 g", 285, 500, "g")],
      "India's classic table butter, made from fresh cream. For toast, parathas, "
      "dal makhani and rich gravies.",
      unit="g", subcategory="Butter", ingredient_tags=["butter"],
      search=["makkhan", "amul butter"], shelf_life="6 months",
      image_queries=["amul butter pack"], related=["Amul Cheese Slices", "Britannia Sandwich White Bread"]),
    P("Fresh Paneer", "Amul", "Dairy & Eggs",
      [("200 g", 95, 200, "g"), ("500 g", 225, 500, "g")],
      "Soft fresh cottage cheese block, high in protein. The base for paneer butter "
      "masala, palak paneer and tikka.",
      unit="g", subcategory="Paneer", ingredient_tags=["paneer"],
      search=["paneer", "cottage cheese"], shelf_life="7 days",
      image_queries=["amul fresh paneer pack"], related=["Spinach", "Capsicum"]),
    P("Masti Dahi Curd", "Amul", "Dairy & Eggs",
      [("400 g", 45, 400, "g"), ("1 kg", 95, 1000, "g")],
      "Thick set curd with a mild tang. For raita, lassi, kadhi and marinades.",
      unit="g", subcategory="Curd", ingredient_tags=["curd", "yogurt", "dahi"],
      search=["dahi", "curd", "yogurt"], shelf_life="7 days",
      image_queries=["amul masti dahi cup"], related=["Cucumber", "Mint Leaves"]),
    P("Classic Curd", "Mother Dairy", "Dairy & Eggs",
      [("400 g", 44, 400, "g"), ("1 kg", 92, 1000, "g")],
      "Creamy set dahi made from fresh milk, ideal for everyday meals and raita.",
      unit="g", subcategory="Curd", ingredient_tags=["curd", "yogurt", "dahi"],
      search=["dahi", "curd"], shelf_life="7 days",
      image_queries=["mother dairy curd cup"], related=["Fresh Cucumber", "Rajdhani Besan Gram Flour"]),
    P("Cheese Slices", "Amul", "Dairy & Eggs",
      [("100 g", 85, 100, "g"), ("200 g", 155, 200, "g")],
      "Processed cheese slices that melt smoothly, for sandwiches, burgers and toast.",
      unit="g", subcategory="Cheese", ingredient_tags=["cheese"],
      search=["cheese", "amul cheese"], shelf_life="6 months",
      image_queries=["amul cheese slices pack"], related=["Britannia Sandwich White Bread", "Amul Butter Salted"]),
    P("Fresh Cream", "Amul", "Dairy & Eggs", [("250 ml", 78, 250, "ml")],
      "Rich 25% fat dairy cream for gravies, desserts, soups and coffee.",
      unit="ml", subcategory="Cream", ingredient_tags=["cream", "fresh cream"],
      search=["malai", "cream"], shelf_life="4 months",
      image_queries=["amul fresh cream pack"], related=["Amul Fresh Paneer", "Tomato"]),
    P("Pure Ghee", "Amul", "Dairy & Eggs",
      [("500 ml", 340, 500, "ml"), ("1 L", 660, 1000, "ml")],
      "Aromatic cow ghee made from pure butterfat. For tempering dal, festive sweets and rotis.",
      unit="ml", subcategory="Ghee", ingredient_tags=["ghee"],
      search=["ghee", "desi ghee", "tup"], shelf_life="9 months",
      image_queries=["amul pure ghee jar"], related=["Aashirvaad Whole Wheat Atta"]),
    P("Farm Eggs", "Fresh", "Dairy & Eggs", [("6 pieces", 42, 300, "g"), ("12 pieces", 82, 600, "g")],
      "Farm-fresh table eggs, a protein staple for omelettes, bhurji and baking.",
      unit="piece", subcategory="Eggs", ingredient_tags=["egg", "eggs"], veg=False,
      search=["anda", "eggs"], shelf_life="14 days",
      image_queries=["egg tray india"], related=["Onion", "Green Chilli"]),
    P("Lassi Sweet", "Amul", "Dairy & Eggs", [("200 ml", 25, 200, "ml")],
      "Chilled sweet lassi made from fresh curd, a traditional cooling summer drink.",
      unit="ml", subcategory="Yogurt Drinks", ingredient_tags=["lassi"],
      search=["lassi", "chaas"], shelf_life="20 days",
      image_queries=["amul lassi bottle"], related=["Amul Masti Dahi Curd"]),
    P("Buttermilk Masala Chaas", "Amul", "Dairy & Eggs", [("200 ml", 15, 200, "ml")],
      "Spiced buttermilk with cumin and mint, a light and digestive everyday drink.",
      unit="ml", subcategory="Yogurt Drinks", ingredient_tags=["buttermilk", "chaas"],
      search=["chaas", "buttermilk", "majjige"], shelf_life="20 days",
      image_queries=["amul chaas buttermilk pack"], related=["Amul Masti Dahi Curd"]),
]

# --------------------------------------------------------------------------- #
# Atta, Rice & Dal
# --------------------------------------------------------------------------- #
ATTA_RICE_DAL = [
    P("Whole Wheat Atta", "Aashirvaad", "Atta, Rice & Dal",
      [("1 kg", 62, 1000, "g"), ("5 kg", 285, 5000, "g"), ("10 kg", 560, 10000, "g")],
      "100% whole wheat chakki atta with high fibre, giving soft rotis that stay "
      "fluffy for hours.",
      unit="g", subcategory="Atta", ingredient_tags=["wheat flour", "atta"],
      search=["atta", "gehu ka atta", "wheat flour"], shelf_life="6 months",
      image_queries=["aashirvaad atta pack"], related=["Amul Pure Ghee", "Fortune Sunlite Refined Sunflower Oil"]),
    P("Chakki Fresh Atta", "Fortune", "Atta, Rice & Dal",
      [("5 kg", 265, 5000, "g"), ("10 kg", 520, 10000, "g")],
      "Stone-ground whole wheat flour milled fresh, for soft everyday chapatis and parathas.",
      unit="g", subcategory="Atta", ingredient_tags=["wheat flour", "atta"],
      search=["atta", "wheat flour"], shelf_life="6 months",
      image_queries=["fortune chakki atta pack"], related=["Aashirvaad Whole Wheat Atta"]),
    P("Classic Basmati Rice", "India Gate", "Atta, Rice & Dal",
      [("1 kg", 165, 1000, "g"), ("5 kg", 790, 5000, "g")],
      "Aged long-grain basmati that cooks fluffy and separate. Ideal for biryani and pulao.",
      unit="g", subcategory="Rice", ingredient_tags=["basmati rice", "rice"],
      search=["chawal", "basmati", "rice"], shelf_life="12 months",
      image_queries=["india gate basmati rice pack"], related=["Everest Garam Masala", "Amul Pure Ghee"]),
    P("Everyday Basmati Rice", "Daawat", "Atta, Rice & Dal",
      [("1 kg", 120, 1000, "g"), ("5 kg", 570, 5000, "g")],
      "Everyday basmati with a soft texture and delicate aroma, for daily rice meals.",
      unit="g", subcategory="Rice", ingredient_tags=["basmati rice", "rice"],
      search=["chawal", "basmati", "rice"], shelf_life="12 months",
      image_queries=["daawat basmati rice pack"], related=["India Gate Classic Basmati Rice"]),
    P("Sona Masoori Rice", "24 Mantra Organic", "Atta, Rice & Dal",
      [("1 kg", 95, 1000, "g"), ("5 kg", 450, 5000, "g")],
      "Lightweight organic sona masoori rice, the everyday staple across South India.",
      unit="g", subcategory="Rice", ingredient_tags=["rice", "sona masoori"],
      search=["chawal", "sona masoori", "rice"], shelf_life="12 months",
      image_queries=["sona masoori rice pack"], related=["Toor Dal", "Tamarind"]),
    P("Toor Dal", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 95, 500, "g"), ("1 kg", 185, 1000, "g")],
      "Unpolished arhar dal rich in protein, the base of everyday dal, sambar and khichdi.",
      unit="g", subcategory="Dal", ingredient_tags=["toor dal", "arhar dal", "dal"],
      search=["toor dal", "arhar", "tuvar"], shelf_life="9 months",
      image_queries=["tata sampann toor dal pack"], related=["Turmeric Powder", "Onion"]),
    P("Moong Dal", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 88, 500, "g"), ("1 kg", 172, 1000, "g")],
      "Split yellow moong dal, light and easy to digest. For dal, khichdi and halwa.",
      unit="g", subcategory="Dal", ingredient_tags=["moong dal", "dal"],
      search=["moong dal", "mung"], shelf_life="9 months",
      image_queries=["tata sampann moong dal pack"], related=["Sona Masoori Rice", "Amul Pure Ghee"]),
    P("Chana Dal", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 78, 500, "g"), ("1 kg", 152, 1000, "g")],
      "Split bengal gram with a nutty bite, for dal, sundal and festive sweets.",
      unit="g", subcategory="Dal", ingredient_tags=["chana dal", "dal"],
      search=["chana dal", "bengal gram"], shelf_life="9 months",
      image_queries=["tata sampann chana dal pack"], related=["Coconut", "Curry Leaves"]),
    P("Masoor Dal", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 72, 500, "g"), ("1 kg", 140, 1000, "g")],
      "Quick-cooking red lentils that turn creamy, perfect for a fast weekday dal.",
      unit="g", subcategory="Dal", ingredient_tags=["masoor dal", "dal"],
      search=["masoor dal", "red lentil"], shelf_life="9 months",
      image_queries=["masoor dal red lentil pack"], related=["Onion", "Tomato"]),
    P("Urad Dal", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 98, 500, "g"), ("1 kg", 190, 1000, "g")],
      "Split black gram, essential for dosa and idli batter, dal makhani and vada.",
      unit="g", subcategory="Dal", ingredient_tags=["urad dal", "dal"],
      search=["urad dal", "black gram"], shelf_life="9 months",
      image_queries=["urad dal pack"], related=["Sona Masoori Rice", "Fenugreek Seeds"]),
    P("Rajma Chitra", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 110, 500, "g"), ("1 kg", 215, 1000, "g")],
      "Speckled kidney beans that cook soft and creamy, for classic rajma chawal.",
      unit="g", subcategory="Pulses", ingredient_tags=["rajma", "kidney beans"],
      search=["rajma", "kidney beans"], shelf_life="9 months",
      image_queries=["rajma kidney beans pack"], related=["Onion", "Everest Garam Masala"]),
    P("Kabuli Chana", "Tata Sampann", "Atta, Rice & Dal",
      [("500 g", 92, 500, "g"), ("1 kg", 180, 1000, "g")],
      "Plump white chickpeas for chole, hummus, chaat and sundal.",
      unit="g", subcategory="Pulses", ingredient_tags=["chickpeas", "chana", "kabuli chana"],
      search=["chana", "chole", "chickpeas"], shelf_life="9 months",
      image_queries=["kabuli chana chickpeas pack"], related=["Everest Chole Masala", "Onion"]),
    P("Besan Gram Flour", "Rajdhani", "Atta, Rice & Dal",
      [("500 g", 68, 500, "g"), ("1 kg", 130, 1000, "g")],
      "Finely milled gram flour for pakoras, kadhi, besan chilla and Indian sweets.",
      unit="g", subcategory="Flour", ingredient_tags=["besan", "gram flour"],
      search=["besan", "gram flour"], shelf_life="6 months",
      image_queries=["besan gram flour pack"], related=["Lady Finger", "Amul Masti Dahi Curd"]),
    P("Sooji Rava", "Rajdhani", "Atta, Rice & Dal", [("500 g", 42, 500, "g"), ("1 kg", 80, 1000, "g")],
      "Coarse semolina for upma, rava dosa, halwa and crisp coatings.",
      unit="g", subcategory="Flour", ingredient_tags=["sooji", "rava", "semolina"],
      search=["sooji", "rava", "semolina"], shelf_life="6 months",
      image_queries=["sooji rava semolina pack"], related=["Mustard Seeds", "Curry Leaves"]),
    P("Poha Thick", "Rajdhani", "Atta, Rice & Dal", [("500 g", 45, 500, "g")],
      "Thick flattened rice flakes for the classic Maharashtrian breakfast poha and chivda.",
      unit="g", subcategory="Flour", ingredient_tags=["poha", "flattened rice"],
      search=["poha", "aval", "flattened rice"], shelf_life="6 months",
      image_queries=["poha flattened rice pack"], related=["Onion", "Mustard Seeds"]),
    P("Idli Rava", "Rajdhani", "Atta, Rice & Dal", [("500 g", 52, 500, "g")],
      "Rice rava ground for soft, fluffy idlis when combined with urad dal.",
      unit="g", subcategory="Flour", ingredient_tags=["idli rava"],
      search=["idli rava", "rice rava"], shelf_life="6 months",
      image_queries=["idli rava pack"], related=["Urad Dal", "Fenugreek Seeds"]),
    P("Maida Refined Flour", "Rajdhani", "Atta, Rice & Dal", [("500 g", 38, 500, "g"), ("1 kg", 72, 1000, "g")],
      "Fine refined wheat flour for naan, bhature, cakes and Indo-Chinese batters.",
      unit="g", subcategory="Flour", ingredient_tags=["maida", "refined flour"],
      search=["maida", "all purpose flour"], shelf_life="6 months",
      image_queries=["maida refined flour pack"], related=["Amul Masti Dahi Curd", "Kabuli Chana"]),
]

# --------------------------------------------------------------------------- #
# Oil & Ghee
# --------------------------------------------------------------------------- #
OIL_GHEE = [
    P("Sunlite Refined Sunflower Oil", "Fortune", "Oil & Ghee",
      [("1 L", 145, 1000, "ml"), ("5 L", 700, 5000, "ml")],
      "Light refined sunflower oil rich in vitamin E, for everyday frying and cooking.",
      unit="ml", subcategory="Refined Oil", ingredient_tags=["oil", "cooking oil", "sunflower oil"],
      search=["tel", "sunflower oil", "cooking oil"], shelf_life="9 months",
      image_queries=["fortune sunflower oil bottle"], related=["Aashirvaad Whole Wheat Atta"]),
    P("Gold Refined Oil", "Saffola", "Oil & Ghee", [("1 L", 175, 1000, "ml")],
      "Blended refined oil designed for heart health, with a light taste for daily cooking.",
      unit="ml", subcategory="Refined Oil", ingredient_tags=["oil", "cooking oil"],
      search=["tel", "saffola", "cooking oil"], shelf_life="9 months",
      image_queries=["saffola gold oil bottle"], related=["Fortune Sunlite Refined Sunflower Oil"]),
    P("Kachi Ghani Mustard Oil", "Fortune", "Oil & Ghee",
      [("1 L", 165, 1000, "ml"), ("5 L", 810, 5000, "ml")],
      "Cold-pressed pungent mustard oil, essential for Bengali, Bihari and pickle cooking.",
      unit="ml", subcategory="Mustard Oil", ingredient_tags=["mustard oil", "oil"],
      search=["sarson ka tel", "mustard oil"], shelf_life="9 months",
      image_queries=["fortune kachi ghani mustard oil bottle"], related=["Brinjal", "Turmeric Powder"]),
    P("Groundnut Oil", "Dhara", "Oil & Ghee", [("1 L", 190, 1000, "ml")],
      "Filtered groundnut oil with a nutty aroma, favoured in Gujarati and South Indian cooking.",
      unit="ml", subcategory="Groundnut Oil", ingredient_tags=["groundnut oil", "oil"],
      search=["mungfali tel", "groundnut oil", "peanut oil"], shelf_life="9 months",
      image_queries=["dhara groundnut oil bottle"], related=["Mustard Seeds", "Curry Leaves"]),
    P("Coconut Oil", "Parachute", "Oil & Ghee", [("500 ml", 165, 500, "ml"), ("1 L", 320, 1000, "ml")],
      "Pure coconut oil for Kerala-style cooking, tempering and traditional hair care.",
      unit="ml", subcategory="Coconut Oil", ingredient_tags=["coconut oil", "oil"],
      search=["nariyal tel", "coconut oil"], shelf_life="12 months",
      image_queries=["parachute coconut oil bottle"], related=["Curry Leaves", "Mustard Seeds"]),
    P("Cow Ghee", "Mother Dairy", "Oil & Ghee", [("500 ml", 330, 500, "ml"), ("1 L", 645, 1000, "ml")],
      "Granular cow ghee with a rich aroma, for tempering, sweets and festive cooking.",
      unit="ml", subcategory="Ghee", ingredient_tags=["ghee"],
      search=["ghee", "desi ghee"], shelf_life="9 months",
      image_queries=["mother dairy cow ghee jar"], related=["Aashirvaad Whole Wheat Atta"]),
    P("Olive Oil Extra Virgin", "Figaro", "Oil & Ghee", [("500 ml", 445, 500, "ml")],
      "Cold-pressed extra virgin olive oil for salads, dressings and light sauteing.",
      unit="ml", subcategory="Olive Oil", ingredient_tags=["olive oil", "oil"],
      search=["olive oil", "jaitun tel"], shelf_life="18 months",
      image_queries=["figaro olive oil bottle"], related=["Capsicum", "Cucumber"]),
]
