"""Curated Indian catalog — part 3: masala & spices.

This is the category that makes or breaks recipe coverage: Indian recipes are
spice-dense, so every whole spice, ground powder and blended masala that the
recipe set references must live here.
"""

from __future__ import annotations

from .schema import P

MASALA_SPICES = [
    # --- ground powders: the daily four -------------------------------------#
    P("Turmeric Powder", "Everest", "Masala & Spices",
      [("100 g", 42, 100, "g"), ("200 g", 80, 200, "g"), ("500 g", 190, 500, "g")],
      "Bright haldi powder with a warm earthy flavour and natural anti-inflammatory "
      "properties. Goes into almost every Indian curry and dal.",
      unit="g", subcategory="Ground Masala", ingredient_tags=["turmeric", "haldi"],
      search=["haldi", "turmeric", "manjal"], shelf_life="12 months",
      image_queries=["everest turmeric haldi powder pack"],
      related=["Everest Red Chilli Powder", "Everest Coriander Powder"]),
    P("Red Chilli Powder", "Everest", "Masala & Spices",
      [("100 g", 55, 100, "g"), ("200 g", 105, 200, "g"), ("500 g", 250, 500, "g")],
      "Fiery lal mirch powder that delivers heat and a deep red colour to curries and marinades.",
      unit="g", subcategory="Ground Masala", ingredient_tags=["red chilli powder", "chilli powder"],
      search=["lal mirch", "chilli powder", "mirchi"], shelf_life="12 months",
      image_queries=["everest red chilli powder pack"],
      related=["Everest Turmeric Powder", "Everest Coriander Powder"]),
    P("Kashmiri Chilli Powder", "Everest", "Masala & Spices",
      [("100 g", 68, 100, "g"), ("200 g", 130, 200, "g")],
      "Mild Kashmiri chilli that gives a vivid red colour without overwhelming heat. "
      "Essential for tandoori marinades and butter masala.",
      unit="g", subcategory="Ground Masala", ingredient_tags=["kashmiri chilli", "chilli powder"],
      search=["kashmiri mirch", "degi mirch"], shelf_life="12 months",
      image_queries=["kashmiri red chilli powder pack"],
      related=["Amul Fresh Paneer", "Amul Fresh Cream"]),
    P("Coriander Powder", "Everest", "Masala & Spices",
      [("100 g", 40, 100, "g"), ("500 g", 180, 500, "g")],
      "Ground dhania with a mild citrusy sweetness. The body of most North Indian gravies.",
      unit="g", subcategory="Ground Masala", ingredient_tags=["coriander powder", "dhania powder"],
      search=["dhania powder", "coriander powder"], shelf_life="12 months",
      image_queries=["everest coriander dhania powder pack"],
      related=["Everest Cumin Powder", "Everest Turmeric Powder"]),
    P("Cumin Powder", "Everest", "Masala & Spices", [("100 g", 62, 100, "g"), ("200 g", 118, 200, "g")],
      "Roasted and ground jeera with a warm smoky aroma, for curries, raita and chaat.",
      unit="g", subcategory="Ground Masala", ingredient_tags=["cumin powder", "jeera powder"],
      search=["jeera powder", "cumin powder"], shelf_life="12 months",
      image_queries=["everest cumin jeera powder pack"],
      related=["Everest Coriander Powder", "Amul Masti Dahi Curd"]),

    # --- blended masalas ----------------------------------------------------#
    P("Garam Masala", "Everest", "Masala & Spices", [("100 g", 88, 100, "g"), ("200 g", 168, 200, "g")],
      "A warming blend of cardamom, cinnamon, clove and pepper, added at the end of "
      "cooking to finish curries with aroma.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["garam masala"],
      search=["garam masala"], shelf_life="12 months",
      image_queries=["everest garam masala pack"],
      related=["Everest Turmeric Powder", "India Gate Classic Basmati Rice"]),
    P("Chole Masala", "Everest", "Masala & Spices", [("100 g", 78, 100, "g")],
      "A tangy spice blend built for chole, with anardana and dry mango for the classic sourness.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["chole masala"],
      search=["chole masala", "chana masala"], shelf_life="12 months",
      image_queries=["everest chole masala pack"],
      related=["Tata Sampann Kabuli Chana", "Onion"]),
    P("Pav Bhaji Masala", "Everest", "Masala & Spices", [("100 g", 75, 100, "g")],
      "The signature Mumbai street-food blend for a rich, buttery pav bhaji.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["pav bhaji masala"],
      search=["pav bhaji masala"], shelf_life="12 months",
      image_queries=["everest pav bhaji masala pack"],
      related=["Amul Butter Salted", "Potato"]),
    P("Sambar Masala", "MTR", "Masala & Spices", [("100 g", 72, 100, "g"), ("200 g", 138, 200, "g")],
      "Authentic South Indian sambar powder with roasted dal, coriander and red chilli.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["sambar masala", "sambar powder"],
      search=["sambar powder", "sambar masala"], shelf_life="12 months",
      image_queries=["mtr sambar masala pack"],
      related=["Tata Sampann Toor Dal", "Tamarind"]),
    P("Rasam Powder", "MTR", "Masala & Spices", [("100 g", 70, 100, "g")],
      "Peppery rasam powder for the classic tangy South Indian soup.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["rasam powder"],
      search=["rasam powder", "rasam masala"], shelf_life="12 months",
      image_queries=["mtr rasam powder pack"], related=["Tamarind", "Tomato"]),
    P("Chaat Masala", "Everest", "Masala & Spices", [("100 g", 65, 100, "g")],
      "Tangy black salt and amchur blend, sprinkled over chaat, fruit, raita and salads.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["chaat masala"],
      search=["chaat masala"], shelf_life="12 months",
      image_queries=["everest chaat masala pack"], related=["Cucumber", "Guava"]),
    P("Kitchen King Masala", "Everest", "Masala & Spices", [("100 g", 92, 100, "g")],
      "An all-rounder masala that lifts mixed vegetable sabzi and paneer dishes.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["kitchen king masala"],
      search=["kitchen king masala"], shelf_life="12 months",
      image_queries=["everest kitchen king masala pack"], related=["Amul Fresh Paneer", "Green Peas"]),
    P("Biryani Masala", "Shan", "Masala & Spices", [("50 g", 85, 50, "g")],
      "A layered blend of whole spices for authentic dum biryani aroma.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["biryani masala"],
      search=["biryani masala"], shelf_life="12 months",
      image_queries=["shan biryani masala box"],
      related=["India Gate Classic Basmati Rice", "Mint Leaves"]),
    P("Tandoori Masala", "Everest", "Masala & Spices", [("100 g", 88, 100, "g")],
      "Smoky tandoori spice mix for paneer tikka, chicken tikka and grilled vegetables.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["tandoori masala"],
      search=["tandoori masala"], shelf_life="12 months",
      image_queries=["everest tandoori masala pack"],
      related=["Amul Fresh Paneer", "Amul Masti Dahi Curd"]),

    # --- whole spices -------------------------------------------------------#
    P("Cumin Seeds", "Catch", "Masala & Spices", [("100 g", 58, 100, "g"), ("200 g", 110, 200, "g")],
      "Whole jeera for tempering dal, rice, jeera aloo and raita.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["cumin seeds", "jeera"],
      search=["jeera", "cumin"], shelf_life="12 months",
      image_queries=["cumin seeds jeera pack"], related=["Mustard Seeds", "Asafoetida"]),
    P("Mustard Seeds", "Catch", "Masala & Spices", [("100 g", 32, 100, "g")],
      "Small black rai seeds that pop in hot oil, the first step of South Indian tempering.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["mustard seeds", "rai"],
      search=["rai", "sarson", "mustard seeds"], shelf_life="12 months",
      image_queries=["mustard seeds rai pack"], related=["Curry Leaves", "Asafoetida"]),
    P("Fenugreek Seeds", "Catch", "Masala & Spices", [("100 g", 30, 100, "g")],
      "Bitter methi dana used in tempering, pickles and dosa batter fermentation.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["fenugreek seeds", "methi seeds"],
      search=["methi dana", "fenugreek"], shelf_life="12 months",
      image_queries=["fenugreek methi seeds pack"], related=["Urad Dal", "Mustard Seeds"]),
    P("Black Pepper Whole", "Catch", "Masala & Spices", [("100 g", 135, 100, "g")],
      "Sharp Malabar peppercorns for rasam, garam masala and fresh grinding.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["black pepper", "pepper"],
      search=["kali mirch", "pepper"], shelf_life="18 months",
      image_queries=["black peppercorns pack"], related=["MTR Rasam Powder", "Cumin Seeds"]),
    P("Green Cardamom", "Catch", "Masala & Spices", [("50 g", 175, 50, "g")],
      "Fragrant elaichi pods for chai, biryani, kheer and festive sweets.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["cardamom", "elaichi"],
      search=["elaichi", "cardamom"], shelf_life="18 months",
      image_queries=["green cardamom elaichi pack"], related=["Tata Tea Premium", "Amul Gold Full Cream Milk"]),
    P("Cloves", "Catch", "Masala & Spices", [("50 g", 88, 50, "g")],
      "Intensely aromatic laung for biryani, garam masala and masala chai.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["cloves", "laung"],
      search=["laung", "cloves"], shelf_life="18 months",
      image_queries=["cloves laung spice pack"], related=["Cinnamon", "Green Cardamom"]),
    P("Cinnamon", "Catch", "Masala & Spices", [("50 g", 65, 50, "g")],
      "Warm sweet dalchini bark for pulao, garam masala and desserts.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["cinnamon", "dalchini"],
      search=["dalchini", "cinnamon"], shelf_life="18 months",
      image_queries=["cinnamon dalchini sticks pack"], related=["Cloves", "Bay Leaf"]),
    P("Bay Leaf", "Catch", "Masala & Spices", [("50 g", 40, 50, "g")],
      "Dried tej patta that lends a subtle fragrance to pulao, dal and curries.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["bay leaf", "tej patta"],
      search=["tej patta", "bay leaf"], shelf_life="18 months",
      image_queries=["bay leaf tej patta pack"], related=["Cinnamon", "Green Cardamom"]),
    P("Asafoetida Hing", "Everest", "Masala & Spices", [("50 g", 95, 50, "g")],
      "Pungent compounded hing that adds savoury depth to dal, sabzi and pickles.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["asafoetida", "hing"],
      search=["hing", "asafoetida"], shelf_life="18 months",
      image_queries=["everest hing asafoetida box"], related=["Cumin Seeds", "Mustard Seeds"]),
    P("Carom Seeds Ajwain", "Catch", "Masala & Spices", [("100 g", 48, 100, "g")],
      "Sharp thymol-scented ajwain for parathas, pakoras and digestive remedies.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["ajwain", "carom seeds"],
      search=["ajwain", "carom seeds"], shelf_life="12 months",
      image_queries=["ajwain carom seeds pack"], related=["Rajdhani Besan Gram Flour"]),
    P("Dry Red Chilli", "Catch", "Masala & Spices", [("100 g", 68, 100, "g")],
      "Whole dried red chillies for tempering, chutneys and grinding into fresh masala.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["dry red chilli", "red chilli"],
      search=["sukhi lal mirch", "dry red chilli"], shelf_life="12 months",
      image_queries=["dry red chilli whole pack"], related=["Mustard Seeds", "Curry Leaves"]),
    P("Fennel Seeds", "Catch", "Masala & Spices", [("100 g", 52, 100, "g")],
      "Sweet saunf for mouth freshener, Bengali panch phoron and pickles.",
      unit="g", subcategory="Whole Spices", ingredient_tags=["fennel", "saunf"],
      search=["saunf", "fennel"], shelf_life="12 months",
      image_queries=["fennel saunf seeds pack"], related=["Fenugreek Seeds", "Cumin Seeds"]),

    # --- salt, sour agents --------------------------------------------------#
    P("Iodised Salt", "Tata", "Masala & Spices", [("1 kg", 28, 1000, "g")],
      "Free-flowing vacuum-evaporated iodised salt for everyday cooking.",
      unit="g", subcategory="Salt", ingredient_tags=["salt"],
      search=["namak", "salt"], shelf_life="24 months",
      image_queries=["tata salt pack"], related=["Everest Turmeric Powder"]),
    P("Black Salt Kala Namak", "Tata", "Masala & Spices", [("200 g", 42, 200, "g")],
      "Sulphurous rock salt with a distinctive tang, for chaat, raita and jaljeera.",
      unit="g", subcategory="Salt", ingredient_tags=["black salt", "kala namak"],
      search=["kala namak", "black salt"], shelf_life="24 months",
      image_queries=["black salt kala namak pack"], related=["Everest Chaat Masala"]),
    P("Tamarind", "Fresh", "Masala & Spices", [("200 g", 55, 200, "g"), ("500 g", 130, 500, "g")],
      "Seedless imli pulp that gives sambar, rasam and chutneys their signature sourness.",
      unit="g", subcategory="Souring Agents", ingredient_tags=["tamarind", "imli"],
      search=["imli", "tamarind", "puli"], shelf_life="12 months",
      image_queries=["tamarind imli block pack"], related=["MTR Sambar Masala", "Jaggery"]),
    P("Dry Mango Powder Amchur", "Everest", "Masala & Spices", [("100 g", 60, 100, "g")],
      "Tart amchur powder used to add sourness to chole, chaat and dry sabzi.",
      unit="g", subcategory="Souring Agents", ingredient_tags=["amchur", "dry mango powder"],
      search=["amchur", "dry mango powder"], shelf_life="12 months",
      image_queries=["amchur dry mango powder pack"], related=["Everest Chole Masala"]),
    P("Kasuri Methi", "Everest", "Masala & Spices", [("50 g", 58, 50, "g")],
      "Dried fenugreek leaves crushed over butter masala and dal for a restaurant aroma.",
      unit="g", subcategory="Blended Masala", ingredient_tags=["kasuri methi", "dried fenugreek"],
      search=["kasuri methi", "dried fenugreek"], shelf_life="12 months",
      image_queries=["kasuri methi pack"], related=["Amul Fresh Paneer", "Amul Fresh Cream"]),
]
