"""Curated Indian catalog — part 6: biscuits & chocolates, beverages."""

from .schema import P

# Biscuits & Chocolates ------------------------------------------------------- #
BISCUITS = [
    P("Good Day Butter Cookies", "Britannia", "Biscuits & Chocolates",
      [("100 g", 20, 100, "g"), ("500 g", 90, 500, "g")],
      "Buttery cookies with a cashew crunch.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "cookies"],
      search=["good day", "butter cookies"], image_queries=["britannia good day pack"],
      related=["Marie Gold", "Bourbon"]),
    P("Marie Gold", "Britannia", "Biscuits & Chocolates",
      [("100 g", 20, 100, "g"), ("250 g", 45, 250, "g")],
      "Light tea-time biscuits, the original Marie.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "marie"],
      search=["marie gold", "tea biscuits"], image_queries=["britannia marie gold pack"],
      related=["Good Day Butter Cookies", "50-50"]),
    P("Bourbon", "Britannia", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Chocolate-cream sandwich biscuits.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["bourbon", "chocolate biscuits"], image_queries=["britannia bourbon pack"],
      related=["Little Hearts", "Chocolate Chip Cookies"]),
    P("Little Hearts", "Britannia", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Tiny heart-shaped chocolate biscuits.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["little hearts"], image_queries=["britannia little hearts pack"],
      related=["Bourbon", "Milk Bikis"]),
    P("Milk Bikis", "Britannia", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Milk-rich biscuits for dunking.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "milk"],
      search=["milk bikis"], image_queries=["britannia milk bikis pack"],
      related=["Marie Gold", "Good Day Butter Cookies"]),
    P("50-50", "Britannia", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Sweet-and-salty glucose biscuits.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "glucose"],
      search=["50-50", "glucose biscuits"], image_queries=["britannia 50-50 pack"],
      related=["Marie Gold", "Jim Jam"]),
    P("Jim Jam", "Britannia", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Jam-and-cream sandwich biscuits with sprinkles.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "jam"],
      search=["jim jam"], image_queries=["britannia jim jam pack"],
      related=["Little Hearts", "Bourbon"]),
    P("Chocolate Chip Cookies", "Britannia", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Soft cookies loaded with chocolate chips.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["chocolate chip cookies"], image_queries=["britannia chocolate chip cookies pack"],
      related=["Bourbon", "Good Day Butter Cookies"]),
    P("Digestive Biscuits", "Britannia", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Wholewheat fibre biscuits.",
      subcategory="Biscuits", veg=True, ingredient_tags=["biscuit", "digestive"],
      search=["digestive biscuits"], image_queries=["britannia digestive biscuits pack"],
      related=["Marie Gold", "Oats Biscuits"]),
    P("Oats Biscuits", "Britannia", "Biscuits & Chocolates", [("100 g", 35, 100, "g")],
      "Crunchy oats biscuits with honey.",
      subcategory="Biscuits", veg=True, ingredient_tags=["biscuit", "oats"],
      search=["oats biscuits"], image_queries=["britannia oats biscuits pack"],
      related=["Digestive Biscuits", "Marie Gold"]),
    P("Krack Jack", "Parle", "Biscuits & Chocolates",
      [("100 g", 20, 100, "g"), ("250 g", 45, 250, "g")],
      "Sweet-salty cracker biscuits.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "crackers"],
      search=["krack jack", "crackers"], image_queries=["parle krack jack pack"],
      related=["20-20", "Monaco"]),
    P("20-20", "Parle", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Energy biscuits with vitamins.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "glucose"],
      search=["parle 20-20"], image_queries=["parle 20-20 pack"],
      related=["Krack Jack", "Marie Gold"]),
    P("Monaco", "Parle", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Salty bite-size crackers.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "crackers"],
      search=["monaco", "salt crackers"], image_queries=["parle monaco pack"],
      related=["Krack Jack", "50-50"]),
    P("Parle-G", "Parle", "Biscuits & Chocolates",
      [("100 g", 20, 100, "g"), ("500 g", 90, 500, "g")],
      "The iconic childhood glucose biscuit.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "glucose"],
      search=["parle g", "glucose biscuits"], image_queries=["parle-g pack"],
      related=["Krack Jack", "Marie Gold"]),
    P("Hide & Seek", "Parle", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Chocolate-chip cream biscuits.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["hide and seek"], image_queries=["parle hide and seek pack"],
      related=["Bourbon", "Chocolate Chip Cookies"]),
    P("Kismi Bar", "Parle", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Elaichi-flavoured soft toffee bar.",
      subcategory="Toffees", ingredient_tags=["sweet", "toffee"],
      search=["kismi", "elaichi toffee"], image_queries=["parle kismi bar pack"],
      related=["Eclairs", "Mango Bite"]),
    P("Mango Bite", "Parle", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Mango-flavoured toffee.",
      subcategory="Toffees", ingredient_tags=["sweet", "toffee"],
      search=["mango bite"], image_queries=["parle mango bite pack"],
      related=["Kismi Bar", "Eclairs"]),
    P("Milk At Burst", "Parle", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Liquid-centre milk toffees.",
      subcategory="Toffees", ingredient_tags=["sweet", "toffee"],
      search=["milk at burst"], image_queries=["parle milk at burst pack"],
      related=["Eclairs", "Kismi Bar"]),
    P("Eclairs", "Cadbury", "Biscuits & Chocolates", [("100 g", 40, 100, "g")],
      "Chewy caramel-and-chocolate eclairs.",
      subcategory="Toffees", ingredient_tags=["sweet", "chocolate"],
      search=["eclairs", "cadbury eclairs"], image_queries=["cadbury eclairs pack"],
      related=["Dairy Milk", "Mango Bite"]),
    P("Dairy Milk", "Cadbury", "Biscuits & Chocolates",
      [("36 g", 20, 36, "g"), ("160 g", 90, 160, "g")],
      "The classic smooth milk chocolate bar.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate"],
      search=["dairy milk", "cadbury"], image_queries=["cadbury dairy milk bar"],
      related=["Silk", "Eclairs"]),
    P("Silk", "Cadbury", "Biscuits & Chocolates", [("60 g", 70, 60, "g")],
      "Extra-creamy milk chocolate.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate"],
      search=["cadbury silk"], image_queries=["cadbury silk bar"],
      related=["Dairy Milk", "Oreo"]),
    P("Bournville", "Cadbury", "Biscuits & Chocolates", [("80 g", 90, 80, "g")],
      "Rich dark chocolate with cocoa nibs.",
      subcategory="Chocolate", ingredient_tags=["sweet", "dark chocolate"],
      search=["bournville", "dark chocolate"], image_queries=["cadbury bournville bar"],
      related=["Silk", "KitKat"]),
    P("KitKat", "Nestle", "Biscuits & Chocolates", [("40 g", 30, 40, "g")],
      "Crispy wafer fingers in milk chocolate.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate", "wafer"],
      search=["kitkat", "nestle"], image_queries=["nestle kitkat pack"],
      related=["Munch", "Silk"]),
    P("Munch", "Nestle", "Biscuits & Chocolates", [("27 g", 20, 27, "g")],
      "Crispy wafer in milk chocolate.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate", "wafer"],
      search=["munch", "nestle"], image_queries=["nestle munch bar"],
      related=["KitKat", "Milkybar"]),
    P("Milkybar", "Nestle", "Biscuits & Chocolates", [("40 g", 30, 40, "g")],
      "White chocolate bar.",
      subcategory="Chocolate", ingredient_tags=["sweet", "white chocolate"],
      search=["milkybar", "white chocolate"], image_queries=["nestle milkybar pack"],
      related=["Munch", "Dairy Milk"]),
    P("Oreo", "Nabisco", "Biscuits & Chocolates", [("120 g", 50, 120, "g")],
      "Chocolate sandwich cookies with cream.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["oreo", "cream biscuits"], image_queries=["oreo pack"],
      related=["Silk", "Hide & Seek"]),
    P("Dark Fantasy Choco Fill", "Sunfeast", "Biscuits & Chocolates", [("100 g", 40, 100, "g")],
      "Chocolate-filled crispy rolls.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["dark fantasy", "choco fill"], image_queries=["sunfeast dark fantasy pack"],
      related=["Bourbon", "Silk"]),
    P("Marie Light", "Sunfeast", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Light tea biscuits, less sugar.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "marie"],
      search=["marie light"], image_queries=["sunfeast marie light pack"],
      related=["Marie Gold", "Digestive Biscuits"]),
    P("Nice Chocolate", "Sunfeast", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Coconut biscuits with a chocolate dip.",
      subcategory="Biscuits", ingredient_tags=["biscuit", "chocolate"],
      search=["nice chocolate biscuits"], image_queries=["sunfeast nice chocolate pack"],
      related=["Dark Fantasy Choco Fill", "Little Hearts"]),
    P("Coffee Bite", "Nestle", "Biscuits & Chocolates", [("100 g", 25, 100, "g")],
      "Coffee-flavoured toffee with a creamy centre.",
      subcategory="Toffees", ingredient_tags=["sweet", "coffee"],
      search=["coffee bite"], image_queries=["nestle coffee bite pack"],
      related=["Mango Bite", "Kismi Bar"]),
    P("Alpenliebe", "Perfetti", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Creamy caramel toffees.",
      subcategory="Toffees", ingredient_tags=["sweet", "toffee"],
      search=["alpenliebe", "caramel"], image_queries=["alpenliebe pack"],
      related=["Eclairs", "Kismi Bar"]),
    P("Center Shock", "Perfetti", "Biscuits & Chocolates", [("100 g", 30, 100, "g")],
      "Liquid-centre sour candies.",
      subcategory="Candies", ingredient_tags=["sweet", "candy"],
      search=["center shock"], image_queries=["center shock pack"],
      related=["Alpenliebe", "Mango Bite"]),
    P("Poppins", "Parry's", "Biscuits & Chocolates", [("100 g", 20, 100, "g")],
      "Assorted fruit candies.",
      subcategory="Candies", ingredient_tags=["sweet", "candy"],
      search=["poppins", "fruit candy"], image_queries=["parrys poppins pack"],
      related=["Center Shock", "Mango Bite"]),
    P("Hajmola", "Dabur", "Biscuits & Chocolates", [("120 g", 40, 120, "g")],
      "Tangy digestive candy tablets.",
      subcategory="Candies", ingredient_tags=["sweet", "tangy"],
      search=["hajmola"], image_queries=["dabur hajmola pack"],
      related=["Imli Candy", "Alpenliebe"]),
    P("Rasna", "Rasna", "Biscuits & Chocolates", [("500 g", 120, 500, "g")],
      "Instant orange squash concentrate.",
      subcategory="Drink Mix", ingredient_tags=["sweet", "squash"],
      search=["rasna", "orange drink"], image_queries=["rasna orange pack"],
      related=["Tang", "Rooh Afza"]),
    P("Tang", "Tang", "Biscuits & Chocolates", [("500 g", 130, 500, "g")],
      "Instant orange drink powder.",
      subcategory="Drink Mix", ingredient_tags=["sweet", "drink"],
      search=["tang", "orange drink"], image_queries=["tang orange pack"],
      related=["Rasna", "Complan"]),
    P("Bournvita", "Cadbury", "Biscuits & Chocolates", [("500 g", 250, 500, "g")],
      "Malt-based health drink with cocoa.",
      subcategory="Health Drink", ingredient_tags=["sweet", "health drink"],
      search=["bournvita"], image_queries=["cadbury bournvita jar"],
      related=["Complan", "Horlicks"]),
    P("Complan", "Heinz", "Biscuits & Chocolates", [("500 g", 260, 500, "g")],
      "Milk protein health drink.",
      subcategory="Health Drink", ingredient_tags=["sweet", "health drink"],
      search=["complan"], image_queries=["complan pack"],
      related=["Bournvita", "Horlicks"]),
    P("Horlicks", "GSK", "Biscuits & Chocolates", [("500 g", 240, 500, "g")],
      "Malt and wheat health drink.",
      subcategory="Health Drink", ingredient_tags=["sweet", "health drink"],
      search=["horlicks"], image_queries=["horlicks pack"],
      related=["Complan", "Bournvita"]),
    P("Boost", "Nestle", "Biscuits & Chocolates", [("500 g", 250, 500, "g")],
      "Malt and chocolate energy drink.",
      subcategory="Health Drink", ingredient_tags=["sweet", "health drink"],
      search=["boost", "energy drink"], image_queries=["nestle boost jar"],
      related=["Bournvita", "Complan"]),
    P("Chocos", "Kellogg's", "Biscuits & Chocolates", [("300 g", 150, 300, "g")],
      "Chocolate breakfast cereal.",
      subcategory="Cereal", ingredient_tags=["sweet", "cereal"],
      search=["chocos", "chocolate cereal"], image_queries=["kelloggs chocos pack"],
      related=["Corn Flakes", "Muesli"]),
    P("Corn Flakes", "Kellogg's", "Biscuits & Chocolates", [("300 g", 140, 300, "g")],
      "Classic toasted corn flakes.",
      subcategory="Cereal", ingredient_tags=["sweet", "cereal"],
      search=["corn flakes"], image_queries=["kelloggs corn flakes pack"],
      related=["Chocos", "Muesli"]),
    P("Muesli", "Kellogg's", "Biscuits & Chocolates", [("300 g", 180, 300, "g")],
      "Crunchy oats, fruits and nuts cereal.",
      subcategory="Cereal", veg=True, ingredient_tags=["sweet", "cereal"],
      search=["muesli"], image_queries=["kelloggs muesli pack"],
      related=["Corn Flakes", "Oats"]),
    P("Plain Oats", "Saffola", "Biscuits & Chocolates", [("500 g", 120, 500, "g")],
      "Rolled oats for porridge.",
      subcategory="Cereal", veg=True, ingredient_tags=["oats", "cereal"],
      search=["oats", "saffola oats"], image_queries=["saffola oats pack"],
      related=["Muesli", "Honey"]),
    P("Chocolate Wafers", "Munch", "Biscuits & Chocolates", [("27 g", 20, 27, "g")],
      "Wafer layers in milk chocolate.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate", "wafer"],
      search=["chocolate wafers"], image_queries=["nestle chocolate wafers pack"],
      related=["KitKat", "Munch"]),
    P("Gems", "Nestle", "Biscuits & Chocolates", [("40 g", 20, 40, "g")],
      "Colourful chocolate buttons.",
      subcategory="Chocolate", ingredient_tags=["sweet", "chocolate"],
      search=["gems", "chocolate buttons"], image_queries=["nestle gems pack"],
      related=["Dairy Milk", "KitKat"]),
]
