"""Curated Indian catalog — part 7: beverages, instant & frozen, pickles & papad."""

from .schema import P

# Beverages ------------------------------------------------------------------- #
BEVERAGES = [
    P("Sprite", "Coca-Cola", "Beverages", [("750 ml", 40, 750, "ml")],
      "Lemon-lime fizzy drink, no calories.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "lemon"],
      search=["sprite", "lemon soda"], image_queries=["sprite bottle pack"],
      related=["Coca-Cola", "Thums Up"]),
    P("Coca-Cola", "Coca-Cola", "Beverages", [("750 ml", 40, 750, "ml")],
      "The original Coca-Cola cola drink.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "cola"],
      search=["coca cola", "cola"], image_queries=["coca cola bottle pack"],
      related=["Thums Up", "Sprite"]),
    P("Thums Up", "Coca-Cola", "Beverages", [("750 ml", 40, 750, "ml")],
      "Bold Indian cola with a strong kick.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "cola"],
      search=["thums up", "cola"], image_queries=["thums up bottle pack"],
      related=["Coca-Cola", "Sprite"]),
    P("Fanta", "Coca-Cola", "Beverages", [("750 ml", 40, 750, "ml")],
      "Orange-flavoured fizzy soft drink.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "orange"],
      search=["fanta", "orange soda"], image_queries=["fanta bottle pack"],
      related=["Sprite", "Mirinda"]),
    P("Mirinda", "PepsiCo", "Beverages", [("750 ml", 40, 750, "ml")],
      "Orange carbonated drink.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "orange"],
      search=["mirinda", "orange soda"], image_queries=["mirinda bottle pack"],
      related=["Fanta", "Sprite"]),
    P("Pepsi", "PepsiCo", "Beverages", [("750 ml", 40, 750, "ml")],
      "Classic Pepsi cola drink.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "cola"],
      search=["pepsi", "cola"], image_queries=["pepsi bottle pack"],
      related=["7UP", "Mountain Dew"]),
    P("7UP", "PepsiCo", "Beverages", [("750 ml", 40, 750, "ml")],
      "Lemon-lime soda refresher.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "lemon"],
      search=["7up", "lemon soda"], image_queries=["7up bottle pack"],
      related=["Pepsi", "Slice"]),
    P("Mountain Dew", "PepsiCo", "Beverages", [("750 ml", 40, 750, "ml")],
      "Citrus energy soda drink.",
      subcategory="Soft Drink", ingredient_tags=["soft drink", "citrus"],
      search=["mountain dew"], image_queries=["mountain dew bottle pack"],
      related=["Pepsi", "7UP"]),
    P("Slice", "PepsiCo", "Beverages", [("750 ml", 40, 750, "ml")],
      "Mango fruit juice drink.",
      subcategory="Juice", ingredient_tags=["juice", "mango"],
      search=["slice", "mango drink"], image_queries=["slice mango bottle pack"],
      related=["Tropicana Mango", "Frooti"]),
    P("Frooti", "Parle Agro", "Beverages", [("600 ml", 35, 600, "ml")],
      "Mango fruit drink in the iconic tetra.",
      subcategory="Juice", ingredient_tags=["juice", "mango"],
      search=["frooti", "mango drink"], image_queries=["frooti pack"],
      related=["Slice", "Tropicana Mango"]),
    P("Tropicana Mango", "Tropicana", "Beverages", [("1 L", 90, 1000, "ml")],
      "100% mango fruit juice.",
      subcategory="Juice", ingredient_tags=["juice", "mango"],
      search=["tropicana mango", "mango juice"], image_queries=["tropicana mango pack"],
      related=["Tropicana Orange", "Slice"]),
    P("Tropicana Orange", "Tropicana", "Beverages", [("1 L", 90, 1000, "ml")],
      "100% pure pressed orange juice.",
      subcategory="Juice", ingredient_tags=["juice", "orange"],
      search=["tropicana orange"], image_queries=["tropicana orange pack"],
      related=["Tropicana Mango", "Real Orange"]),
    P("Real Orange", "Dabur", "Beverages", [("1 L", 95, 1000, "ml")],
      "Orange fruit juice with pulp.",
      subcategory="Juice", ingredient_tags=["juice", "orange"],
      search=["real orange", "juice"], image_queries=["dabur real orange pack"],
      related=["Real Mixed Fruit", "Tropicana Orange"]),
    P("Real Mixed Fruit", "Dabur", "Beverages", [("1 L", 95, 1000, "ml")],
      "Mixed fruit juice with pulp.",
      subcategory="Juice", ingredient_tags=["juice", "mixed fruit"],
      search=["real mixed fruit"], image_queries=["dabur real mixed fruit pack"],
      related=["Real Orange", "Tropicana Mango"]),
    P("Fresh Apple Juice", "Raw Pressery", "Beverages", [("1 L", 150, 1000, "ml")],
      "Cold-pressed apple juice, no added sugar.",
      subcategory="Juice", veg=True, ingredient_tags=["juice", "apple"],
      search=["apple juice", "raw pressery"], image_queries=["raw pressery apple juice pack"],
      related=["Fresh Orange Juice", "Tropicana Apple"]),
    P("Fresh Orange Juice", "Raw Pressery", "Beverages", [("1 L", 150, 1000, "ml")],
      "Cold-pressed orange juice.",
      subcategory="Juice", veg=True, ingredient_tags=["juice", "orange"],
      search=["orange juice"], image_queries=["raw pressery orange juice pack"],
      related=["Fresh Apple Juice", "Real Orange"]),
    P("Tropicana Apple", "Tropicana", "Beverages", [("1 L", 90, 1000, "ml")],
      "100% pure pressed apple juice.",
      subcategory="Juice", ingredient_tags=["juice", "apple"],
      search=["tropicana apple"], image_queries=["tropicana apple pack"],
      related=["Tropicana Orange", "Fresh Apple Juice"]),
    P("Minute Maid Pulpy Orange", "Coca-Cola", "Beverages", [("600 ml", 45, 600, "ml")],
      "Orange drink with fruit pulp.",
      subcategory="Juice", ingredient_tags=["juice", "orange"],
      search=["minute maid", "pulpy orange"], image_queries=["minute maid pulpy orange pack"],
      related=["Real Orange", "Tropicana Orange"]),
    P("Bisleri Mineral Water", "Bisleri", "Beverages", [("1 L", 20, 1000, "ml")],
      "Packaged drinking water.",
      subcategory="Water", ingredient_tags=["water"],
      search=["bisleri", "water"], image_queries=["bisleri 1 litre pack"],
      related=["Kinley Water", "Aquafina"]),
    P("Kinley Water", "Coca-Cola", "Beverages", [("1 L", 20, 1000, "ml")],
      "Packaged drinking water.",
      subcategory="Water", ingredient_tags=["water"],
      search=["kinley", "water"], image_queries=["kinley water pack"],
      related=["Bisleri Mineral Water", "Aquafina"]),
    P("Aquafina", "PepsiCo", "Beverages", [("1 L", 20, 1000, "ml")],
      "Purified drinking water.",
      subcategory="Water", ingredient_tags=["water"],
      search=["aquafina", "water"], image_queries=["aquafina pack"],
      related=["Bisleri Mineral Water", "Kinley Water"]),
    P("Himalayan Still Water", "Tata", "Beverages", [("1 L", 40, 1000, "ml")],
      "Natural mineral water from the Himalayas.",
      subcategory="Water", ingredient_tags=["water"],
      search=["himalayan water"], image_queries=["tata himalayan water pack"],
      related=["Bisleri Mineral Water", "Kinley Water"]),
    P("Tata Gluco Plus", "Tata", "Beverages", [("750 ml", 35, 750, "ml")],
      "Glucose and electrolyte drink.",
      subcategory="Energy", ingredient_tags=["energy drink"],
      search=["gluco plus", "electral"], image_queries=["tata gluco plus pack"],
      related=["Electral Powder", "Bisleri Mineral Water"]),
    P("Electral Powder", "FDC", "Beverages", [("21.8 g", 35, 21.8, "g")],
      "Oral rehydration salt.",
      subcategory="ORS", ingredient_tags=["ors", "electrolyte"],
      search=["electral", "ors"], image_queries=["electral powder pack"],
      related=["Tata Gluco Plus", "Bisleri Mineral Water"]),
    P("Rooh Afza", "Hamdard", "Beverages", [("750 ml", 175, 750, "ml")],
      "Rose-flavoured syrup concentrate.",
      subcategory="Syrup", ingredient_tags=["syrup", "rose"],
      search=["rooh afza", "rose syrup"], image_queries=["rooh afza bottle pack"],
      related=["Rasna", "Tang"]),
    P("Kokam Sherbet", "Mapro", "Beverages", [("750 ml", 150, 750, "ml")],
      "Kokam fruit squash concentrate.",
      subcategory="Syrup", ingredient_tags=["syrup", "kokam"],
      search=["kokam", "sherbet"], image_queries=["mapro kokam squash pack"],
      related=["Rooh Afza", "Rasna"]),
    P("Jaljeera", "Catch", "Beverages", [("200 ml", 30, 200, "ml")],
      "Tangy cumin-spiced cooler.",
      subcategory="Syrup", ingredient_tags=["syrup", "jaljeera"],
      search=["jaljeera", "catch jaljeera"], image_queries=["catch jaljeera pack"],
      related=["Rooh Afza", "Kokam Sherbet"]),
    P("Bournvita Milk Mix", "Cadbury", "Beverages", [("200 g", 110, 200, "g")],
      "Single-serve malt drink mix.",
      subcategory="Health Drink", ingredient_tags=["sweet", "health drink"],
      search=["bournvita sachet"], image_queries=["bournvita small pack"],
      related=["Bournvita", "Complan"]),
    P("Lassi Mango", "Amul", "Beverages", [("200 ml", 30, 200, "ml")],
      "Mango lassi yoghurt drink.",
      subcategory="Dairy Drink", ingredient_tags=["lassi", "mango"],
      search=["mango lassi", "amul lassi"], image_queries=["amul mango lassi pack"],
      related=["Amul Lassi Sweet", "Amul Buttermilk"]),
    P("Cold Coffee", "Amul", "Beverages", [("200 ml", 35, 200, "ml")],
      "Ready-to-drink coffee milkshake.",
      subcategory="Dairy Drink", ingredient_tags=["coffee", "milk"],
      search=["cold coffee", "amul coffee"], image_queries=["amul cold coffee pack"],
      related=["Nestle Cold Coffee", "Bournvita"]),
    P("Nestle Cold Coffee", "Nestle", "Beverages", [("180 ml", 30, 180, "ml")],
      "Coffee-flavoured milk drink.",
      subcategory="Dairy Drink", ingredient_tags=["coffee", "milk"],
      search=["nestle cold coffee"], image_queries=["nestle cold coffee pack"],
      related=["Cold Coffee", "Bournvita"]),
    P("Tender Coconut Water", "Raw Pressery", "Beverages", [("200 ml", 40, 200, "ml")],
      "100% tender coconut water.",
      subcategory="Juice", veg=True, ingredient_tags=["coconut water"],
      search=["coconut water"], image_queries=["raw pressery coconut water pack"],
      related=["Fresh Orange Juice", "Bisleri Mineral Water"]),
    P("Lemon Drink", "Local", "Beverages", [("200 ml", 15, 200, "ml")],
      "Fresh nimbu pani, salted or sweet.",
      subcategory="Juice", veg=True, ingredient_tags=["lemon", "nimbu"],
      search=["nimbu pani", "lemon juice"], image_queries=["nimbu pani glass"],
      related=["Jaljeera", "Rooh Afza"]),
    P("Buttermilk Spiced", "Amul", "Beverages", [("200 ml", 15, 200, "ml")],
      "Masala chaas buttermilk.",
      subcategory="Dairy Drink", ingredient_tags=["buttermilk", "chaas"],
      search=["chaas", "buttermilk"], image_queries=["amul buttermilk pack"],
      related=["Amul Lassi Sweet", "Amul Masti Dahi"]),
    P("Soda Water", "Bisleri", "Beverages", [("750 ml", 30, 750, "ml")],
      "Carbonated club soda.",
      subcategory="Water", ingredient_tags=["soda"],
      search=["soda", "club soda"], image_queries=["bisleri soda pack"],
      related=["Bisleri Mineral Water", "Kinley Water"]),
    P("Energy Drink Red", "Monster", "Beverages", [("500 ml", 120, 500, "ml")],
      "High-caffeine energy drink.",
      subcategory="Energy", ingredient_tags=["energy drink"],
      search=["monster", "energy"], image_queries=["monster energy can pack"],
      related=["Tata Gluco Plus", "Sting"]),
    P("Sting", "PepsiCo", "Beverages", [("250 ml", 50, 250, "ml")],
      "Berry-flavoured energy drink.",
      subcategory="Energy", ingredient_tags=["energy drink"],
      search=["sting", "energy"], image_queries=["sting energy can pack"],
      related=["Monster", "Tata Gluco Plus"]),
    P("Tropicana Cranberry", "Tropicana", "Beverages", [("1 L", 130, 1000, "ml")],
      "Cranberry and apple juice.",
      subcategory="Juice", ingredient_tags=["juice", "cranberry"],
      search=["tropicana cranberry"], image_queries=["tropicana cranberry pack"],
      related=["Tropicana Apple", "Real Mixed Fruit"]),
    P("Ganne Ka Ras", "Local", "Beverages", [("500 ml", 40, 500, "ml")],
      "Fresh sugarcane juice.",
      subcategory="Juice", veg=True, ingredient_tags=["sugarcane", "juice"],
      search=["ganne ka ras", "sugarcane juice"], image_queries=["sugarcane juice glass"],
      related=["Lemon Drink", "Tender Coconut Water"]),
    P("Masala Chaas", "Amul", "Beverages", [("200 ml", 15, 200, "ml")],
      "Spiced buttermilk in a bottle.",
      subcategory="Dairy Drink", ingredient_tags=["buttermilk", "chaas"],
      search=["masala chaas"], image_queries=["amul masala chaas pack"],
      related=["Buttermilk Spiced", "Amul Lassi Sweet"]),
    P("Green Tea Lemon", "Lipton", "Beverages", [("25 bags", 150, 50, "g")],
      "Lemon-flavoured green tea bags.",
      subcategory="Tea", veg=True, ingredient_tags=["green tea", "tea"],
      search=["green tea", "lipton green"], image_queries=["lipton green tea pack"],
      related=["Tata Tea Gold", "Tata Tea Premium"]),
    P("Ice Tea Lemon", "Lipton", "Beverages", [("750 ml", 40, 750, "ml")],
      "Ready-to-drink lemon iced tea.",
      subcategory="Tea", ingredient_tags=["ice tea", "tea"],
      search=["ice tea", "lipton"], image_queries=["lipton ice tea bottle pack"],
      related=["Green Tea Lemon", "Tata Tea Premium"]),
    P("Lassi Sweet", "Mother Dairy", "Beverages", [("200 ml", 25, 200, "ml")],
      "Sweet yoghurt lassi.",
      subcategory="Dairy Drink", ingredient_tags=["lassi"],
      search=["lassi", "mother dairy lassi"], image_queries=["mother dairy lassi pack"],
      related=["Amul Lassi Sweet", "Amul Masti Dahi"]),
    P("Tata Tea Gold", "Tata", "Beverages", [("500 g", 270, 500, "g")],
      "Premium leaf tea with golden tips.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["tata tea gold", "tea"], image_queries=["tata tea gold pack"],
      related=["Tata Tea Premium", "Brooke Bond Red Label"]),
    P("Wagh Bakri Tea", "Wagh Bakri", "Beverages", [("500 g", 230, 500, "g")],
      "Gujarati-Maharashtrian strong tea.",
      subcategory="Tea", ingredient_tags=["tea", "chai"],
      search=["wagh bakri", "tea"], image_queries=["wagh bakri tea pack"],
      related=["Tata Tea Premium", "Brooke Bond Red Label"]),
]
