"""Curated Indian catalog — part 4: bakery, beverages, tea/coffee, sweeteners.

Closes the recipe-coverage gaps from parts 1-3 (bread, tea, sugar, cashew,
raisins) and fills out the everyday shelves.
"""

from __future__ import annotations

from .schema import P

# --------------------------------------------------------------------------- #
# Bakery
# --------------------------------------------------------------------------- #
BAKERY = [
    P("Whole Wheat Bread", "Britannia", "Bakery", [("400 g", 55, 400, "g")],
      "Soft whole wheat sandwich bread with added fibre, ideal for toast and sandwiches.",
      unit="g", subcategory="Bread", ingredient_tags=["bread", "wheat bread"],
      search=["bread", "brown bread", "double roti"], shelf_life="4 days",
      image_queries=["britannia whole wheat bread pack"], related=["Amul Butter Salted"]),
    P("Sandwich White Bread", "Britannia", "Bakery", [("400 g", 45, 400, "g")],
      "Classic soft white bread with a fine crumb, the everyday breakfast staple.",
      unit="g", subcategory="Bread", ingredient_tags=["bread", "white bread"],
      search=["bread", "safed bread"], shelf_life="4 days",
      image_queries=["britannia sandwich bread pack"], related=["Amul Cheese Slices"]),
    P("Pav Bread", "Modern", "Bakery", [("6 pieces", 35, 300, "g")],
      "Soft ladi pav buns, the essential partner for pav bhaji and vada pav.",
      unit="piece", subcategory="Bread", ingredient_tags=["pav", "bread"],
      search=["pav", "ladi pav", "bun"], shelf_life="3 days",
      image_queries=["ladi pav bread buns"], related=["Everest Pav Bhaji Masala", "Amul Butter Salted"]),
    P("Brown Bread", "Modern", "Bakery", [("400 g", 50, 400, "g")],
      "Wholesome brown bread with a nutty flavour and higher fibre than white bread.",
      unit="g", subcategory="Bread", ingredient_tags=["bread", "brown bread"],
      search=["brown bread", "bread"], shelf_life="4 days",
      image_queries=["modern brown bread pack"], related=["Amul Butter Salted"]),
    P("Burger Buns", "Britannia", "Bakery", [("4 pieces", 40, 240, "g")],
      "Soft sesame-topped burger buns for homemade veg and aloo tikki burgers.",
      unit="piece", subcategory="Bread", ingredient_tags=["burger bun", "bread"],
      search=["burger bun", "bun"], shelf_life="4 days",
      image_queries=["burger buns pack"], related=["Amul Cheese Slices", "Potato"]),
    P("Premium Rusk", "Britannia", "Bakery", [("200 g", 42, 200, "g"), ("600 g", 115, 600, "g")],
      "Crisp twice-baked toast rusk, the classic companion to chai.",
      unit="g", subcategory="Rusk", ingredient_tags=["rusk", "toast"],
      search=["rusk", "toast", "papa"], shelf_life="6 months",
      image_queries=["britannia rusk pack"], related=["Tata Tea Premium"]),
    P("Fruit Cake", "Britannia", "Bakery", [("250 g", 75, 250, "g")],
      "Moist tea cake studded with tutti frutti, an everyday bakery favourite.",
      unit="g", subcategory="Cakes", ingredient_tags=["cake"],
      search=["cake", "tea cake"], shelf_life="3 months",
      image_queries=["britannia fruit cake pack"], related=["Tata Tea Premium"]),
    P("Atta Khari Puff", "Monginis", "Bakery", [("200 g", 60, 200, "g")],
      "Flaky layered khari biscuit made with wheat, perfect with morning tea.",
      unit="g", subcategory="Rusk", ingredient_tags=["khari", "puff"],
      search=["khari", "puff biscuit"], shelf_life="3 months",
      image_queries=["khari puff biscuit pack"], related=["Tata Tea Premium"]),
]

# --------------------------------------------------------------------------- #
# Tea & Coffee
# --------------------------------------------------------------------------- #
TEA_COFFEE = [
    P("Premium Leaf Tea", "Tata Tea", "Tea & Coffee",
      [("250 g", 145, 250, "g"), ("500 g", 285, 500, "g"), ("1 kg", 555, 1000, "g")],
      "Strong Assam leaf tea that brews a rich, full-bodied cup with milk and masala.",
      unit="g", subcategory="Black Tea", ingredient_tags=["tea", "chai patti"],
      search=["chai", "chai patti", "tea"], shelf_life="18 months",
      image_queries=["tata tea premium pack"],
      related=["Amul Gold Full Cream Milk", "Green Cardamom"]),
    P("Red Label Tea", "Brooke Bond", "Tea & Coffee",
      [("250 g", 140, 250, "g"), ("500 g", 275, 500, "g")],
      "Everyday blended tea with natural care ingredients, brewing a strong aromatic chai.",
      unit="g", subcategory="Black Tea", ingredient_tags=["tea", "chai patti"],
      search=["chai", "red label", "tea"], shelf_life="18 months",
      image_queries=["red label tea pack"], related=["Amul Taaza Toned Milk"]),
    P("Taj Mahal Tea", "Brooke Bond", "Tea & Coffee", [("250 g", 175, 250, "g")],
      "Premium Assam and Darjeeling blend with a rich aroma, for a refined cup of chai.",
      unit="g", subcategory="Black Tea", ingredient_tags=["tea", "chai patti"],
      search=["chai", "taj mahal tea"], shelf_life="18 months",
      image_queries=["taj mahal tea pack"], related=["Green Cardamom"]),
    P("Green Tea Bags", "Tetley", "Tea & Coffee", [("25 bags", 155, 50, "g")],
      "Light antioxidant-rich green tea bags for a refreshing caffeine-light brew.",
      unit="pack", subcategory="Green Tea", ingredient_tags=["green tea", "tea"],
      search=["green tea", "chai"], shelf_life="18 months",
      image_queries=["tetley green tea box"], related=["Honey"]),
    P("Cardamom Masala Chai", "Wagh Bakri", "Tea & Coffee", [("250 g", 165, 250, "g")],
      "Pre-blended masala chai with cardamom and spices for an instant authentic cup.",
      unit="g", subcategory="Masala Chai", ingredient_tags=["tea", "masala chai"],
      search=["masala chai", "elaichi chai"], shelf_life="18 months",
      image_queries=["wagh bakri masala tea pack"], related=["Amul Gold Full Cream Milk"]),
    P("Classic Instant Coffee", "Nescafe", "Tea & Coffee",
      [("50 g", 185, 50, "g"), ("100 g", 350, 100, "g")],
      "Rich freeze-dried instant coffee that dissolves fast, for hot coffee and cold brews.",
      unit="g", subcategory="Instant Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["coffee", "nescafe"], shelf_life="18 months",
      image_queries=["nescafe classic coffee jar"], related=["Amul Gold Full Cream Milk"]),
    P("Sunrise Instant Coffee", "Bru", "Tea & Coffee", [("50 g", 165, 50, "g")],
      "Chicory-blended instant coffee with a strong South Indian style flavour.",
      unit="g", subcategory="Instant Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["coffee", "bru"], shelf_life="18 months",
      image_queries=["bru instant coffee pack"], related=["Amul Taaza Toned Milk"]),
    P("Filter Coffee Powder", "Cothas", "Tea & Coffee", [("250 g", 195, 250, "g")],
      "Traditional South Indian filter coffee blend with chicory, for authentic degree coffee.",
      unit="g", subcategory="Filter Coffee", ingredient_tags=["coffee", "filter coffee"],
      search=["filter coffee", "kaapi", "coffee"], shelf_life="9 months",
      image_queries=["cothas filter coffee pack"], related=["Amul Gold Full Cream Milk"]),
]

# --------------------------------------------------------------------------- #
# Dry Fruits & Sweeteners
# --------------------------------------------------------------------------- #
DRYFRUITS_SWEETENERS = [
    P("Refined Sugar", "Madhur", "Dry Fruits & Sweeteners",
      [("1 kg", 52, 1000, "g"), ("5 kg", 250, 5000, "g")],
      "Fine sparkling white sugar crystals for tea, coffee, sweets and baking.",
      unit="g", subcategory="Sugar", ingredient_tags=["sugar"],
      search=["cheeni", "shakkar", "sugar"], shelf_life="24 months",
      image_queries=["madhur sugar pack"], related=["Tata Tea Premium"]),
    P("Jaggery", "24 Mantra Organic", "Dry Fruits & Sweeteners",
      [("500 g", 95, 500, "g"), ("1 kg", 180, 1000, "g")],
      "Unrefined cane gur with a deep caramel flavour, a traditional sugar alternative.",
      unit="g", subcategory="Jaggery", ingredient_tags=["jaggery", "gur"],
      search=["gud", "gur", "jaggery", "bella"], shelf_life="12 months",
      image_queries=["organic jaggery gur block"], related=["Tamarind", "Sesame Seeds"]),
    P("Pure Honey", "Dabur", "Dry Fruits & Sweeteners",
      [("250 g", 165, 250, "g"), ("500 g", 310, 500, "g")],
      "Natural multi-floral honey, tested for purity. For toast, tea and wellness drinks.",
      unit="g", subcategory="Honey", ingredient_tags=["honey"],
      search=["shahad", "honey"], shelf_life="24 months",
      image_queries=["dabur honey bottle"], related=["Tetley Green Tea Bags", "Lemon"]),
    P("Whole Cashew W240", "Happilo", "Dry Fruits & Sweeteners",
      [("200 g", 285, 200, "g"), ("500 g", 680, 500, "g")],
      "Premium whole cashews, creamy and crunchy. For gravies, halwa, sweets and snacking.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["cashew", "kaju"],
      search=["kaju", "cashew"], shelf_life="9 months",
      image_queries=["happilo cashew nuts pack"], related=["Carrot", "Amul Pure Ghee"]),
    P("California Almonds", "Happilo", "Dry Fruits & Sweeteners",
      [("200 g", 265, 200, "g"), ("500 g", 620, 500, "g")],
      "Crunchy whole almonds rich in vitamin E and protein, for soaking, snacking and sweets.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["almond", "badam"],
      search=["badam", "almond"], shelf_life="9 months",
      image_queries=["happilo almonds pack"], related=["Amul Gold Full Cream Milk"]),
    P("Seedless Raisins", "Happilo", "Dry Fruits & Sweeteners",
      [("200 g", 120, 200, "g"), ("500 g", 275, 500, "g")],
      "Sweet golden kishmish for halwa, kheer, pulao and everyday snacking.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["raisins", "kishmish"],
      search=["kishmish", "raisins", "dry grapes"], shelf_life="9 months",
      image_queries=["seedless raisins kishmish pack"], related=["Carrot", "Whole Cashew W240"]),
    P("Pistachio Salted", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 340, 200, "g")],
      "Roasted and lightly salted pista, a premium snack and dessert garnish.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["pistachio", "pista"],
      search=["pista", "pistachio"], shelf_life="9 months",
      image_queries=["pistachio pista pack"], related=["California Almonds"]),
    P("Dates Seedless", "Lion", "Dry Fruits & Sweeteners", [("500 g", 185, 500, "g")],
      "Soft seedless khajur, naturally sweet and iron-rich, for snacking and shakes.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["dates", "khajur"],
      search=["khajur", "dates"], shelf_life="12 months",
      image_queries=["seedless dates khajur pack"], related=["Amul Gold Full Cream Milk"]),
    P("Walnut Kernels", "Happilo", "Dry Fruits & Sweeteners", [("200 g", 375, 200, "g")],
      "Light-coloured walnut halves rich in omega-3, for baking and healthy snacking.",
      unit="g", subcategory="Dry Fruits", ingredient_tags=["walnut", "akhrot"],
      search=["akhrot", "walnut"], shelf_life="9 months",
      image_queries=["walnut kernels pack"], related=["California Almonds"]),
    P("Sesame Seeds", "Catch", "Dry Fruits & Sweeteners", [("100 g", 45, 100, "g")],
      "White til seeds for chikki, laddoo, chutney powders and tempering.",
      unit="g", subcategory="Seeds", ingredient_tags=["sesame seeds", "til"],
      search=["til", "sesame"], shelf_life="12 months",
      image_queries=["sesame seeds til pack"], related=["Jaggery"]),
    P("Peanuts Raw", "Fresh", "Dry Fruits & Sweeteners", [("500 g", 95, 500, "g")],
      "Raw groundnuts for chutney, poha, chikki and roasted snacking.",
      unit="g", subcategory="Seeds", ingredient_tags=["peanut", "groundnut"],
      search=["mungfali", "peanut", "groundnut"], shelf_life="6 months",
      image_queries=["raw peanuts groundnut pack"], related=["Poha Thick", "Jaggery"]),
]
