"""Curated Indian catalog — part 5: snacks & namkeen, biscuits & chocolates."""

from .schema import P

# Snacks & Namkeen ------------------------------------------------------------ #
SNACKS = [
    P("Aloo Bhujia", "Haldiram's", "Snacks & Namkeen",
      [("200 g", 30, 200, "g"), ("1 kg", 145, 1000, "g")],
      "Crispy gram-flour noodles with potato, spiced the Haldiram's way.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "bhujia"],
      search=["bhujia", "aloo bhujia"], image_queries=["haldiram aloo bhujia pack"],
      related=["Khatta Meetha", "Moong Dal"]),
    P("Khatta Meetha", "Haldiram's", "Snacks & Namkeen", [("200 g", 32, 200, "g")],
      "Sweet-and-sour mix of sev, lentils and dried mango.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "khatta meetha"],
      search=["khatta meetha"], image_queries=["haldiram khatta meetha pack"],
      related=["Aloo Bhujia", "Navratan Mix"]),
    P("Navratan Mix", "Haldiram's", "Snacks & Namkeen", [("200 g", 34, 200, "g")],
      "Royal mix of nine savouries, nuts and raisins.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "mix"],
      search=["navratan", "mix"], image_queries=["haldiram navratan mix pack"],
      related=["Khatta Meetha", "Dal Moth"]),
    P("Moong Dal", "Haldiram's", "Snacks & Namkeen",
      [("200 g", 33, 200, "g"), ("1 kg", 160, 1000, "g")],
      "Crunchy roasted moong lentils dusted with black salt.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "moong dal"],
      search=["moong dal"], image_queries=["haldiram moong dal pack"],
      related=["Aloo Bhujia", "Chana Jor Garam"]),
    P("Dal Moth", "Haldiram's", "Snacks & Namkeen", [("200 g", 32, 200, "g")],
      "Spicy moth-bean and sev mixture from Rajasthan.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "dal moth"],
      search=["dal moth"], image_queries=["haldiram dal moth pack"],
      related=["Navratan Mix", "Chana Dal"]),
    P("Chana Jor Garam", "Haldiram's", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Tangy flattened-chickpea chaat, ready to eat.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "chana"],
      search=["chana jor garam"], image_queries=["haldiram chana jor garam pack"],
      related=["Moong Dal", "Aloo Bhujia"]),
    P("Mathri", "Haldiram's", "Snacks & Namkeen", [("200 g", 36, 200, "g")],
      "Flaky puri-style crackers with carom and black pepper.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "mathri"],
      search=["mathri"], image_queries=["haldiram mathri pack"],
      related=["Shakarpara", "Gathiya"]),
    P("Shakarpara", "Haldiram's", "Snacks & Namkeen", [("200 g", 38, 200, "g")],
      "Sweet diamond-shaped fried pastry, festive favourite.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "shakarpara"],
      search=["shakarpara"], image_queries=["haldiram shakarpara pack"],
      related=["Mathri", "Soan Cake"]),
    P("Gathiya", "Haldiram's", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Soft chickpea-flour sticks, a Gujarati staple.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "gathiya"],
      search=["gathiya"], image_queries=["haldiram gathiya pack"],
      related=["Mathri", "Bhakarwadi"]),
    P("Bhujiya", "Bikaji", "Snacks & Namkeen",
      [("200 g", 28, 200, "g"), ("1 kg", 135, 1000, "g")],
      "Bikaner's signature spicy bhujia, light and crunchy.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "bhujia"],
      search=["bhujia", "bikaji bhujiya"], image_queries=["bikaji bhujiya pack"],
      related=["Moong Dal", "Chana Dal"]),
    P("Chana Dal", "Bikaji", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Roasted chana dal with a peppery kick.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "chana dal"],
      search=["chana dal"], image_queries=["bikaji chana dal pack"],
      related=["Moong Dal", "Bhujiya"]),
    P("Kaju Katli", "Haldiram's", "Snacks & Namkeen", [("200 g", 240, 200, "g")],
      "Silver-leaf cashew fudge, the classic mithai.",
      subcategory="Sweets", ingredient_tags=["sweet", "kaju katli"],
      search=["kaju katli", "cashew burfi"], image_queries=["haldiram kaju katli box"],
      related=["Kaju Anjeer Roll", "Soan Papdi"]),
    P("Soan Papdi", "Haldiram's", "Snacks & Namkeen", [("200 g", 90, 200, "g")],
      "Flaky gram-flour sweet with cardamom and pistachio.",
      subcategory="Sweets", ingredient_tags=["sweet", "soan papdi"],
      search=["soan papdi"], image_queries=["haldiram soan papdi box"],
      related=["Kaju Katli", "Soan Cake"]),
    P("Rasgulla", "Haldiram's", "Snacks & Namkeen", [("1 kg", 180, 1000, "g")],
      "Spongy cottage-cheese balls in light rose syrup.",
      subcategory="Sweets", ingredient_tags=["sweet", "rasgulla"],
      search=["rasgulla"], image_queries=["haldiram rasgulla tin"],
      related=["Gulab Jamun", "Bengal Gram Laddu"]),
    P("Gulab Jamun", "Haldiram's", "Snacks & Namkeen", [("1 kg", 190, 1000, "g")],
      "Khoya dumplings in cardamom-scented sugar syrup.",
      subcategory="Sweets", ingredient_tags=["sweet", "gulab jamun"],
      search=["gulab jamun"], image_queries=["haldiram gulab jamun tin"],
      related=["Rasgulla", "Kaju Katli"]),
    P("Aloo Bhujia", "Patanjali", "Snacks & Namkeen", [("200 g", 25, 200, "g")],
      "Ayurvedic-style bhujia with less oil and spice.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "bhujia"],
      search=["bhujia", "patanjali bhujia"], image_queries=["patanjali aloo bhujia pack"],
      related=["Moong Dal", "Murukku"]),
    P("Murukku", "Patanjali", "Snacks & Namkeen", [("200 g", 40, 200, "g")],
      "South Indian rice-flour spiral, crunchy and savoury.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "murukku"],
      search=["murukku", "chakli"], image_queries=["patanjali murukku pack"],
      related=["Chakli", "Aloo Bhujia"]),
    P("Chakli", "MTR", "Snacks & Namkeen", [("200 g", 45, 200, "g")],
      "Spiralled rice-and-lentil snack fried to a crisp.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "chakli"],
      search=["chakli", "murukku"], image_queries=["mtr chakli pack"],
      related=["Murukku", "Gathiya"]),
    P("Plain Salted Wafers", "Balaji", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Thin potato wafers with just salt.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["wafers", "potato chips"], image_queries=["balaji plain wafers pack"],
      related=["Masala Wafers", "Classic Salted Lay's"]),
    P("Masala Wafers", "Balaji", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Gujarat's favourite spicy potato wafers.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["masala wafers"], image_queries=["balaji masala wafers pack"],
      related=["Plain Salted Wafers", "Magic Masala Lay's"]),
    P("Masala Munch", "Kurkure", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Puffed curls in tangy masala flavour.",
      subcategory="Extruded", ingredient_tags=["namkeen", "kurkure"],
      search=["kurkure", "masala munch"], image_queries=["kurkure masala munch pack"],
      related=["Chilli Chatka", "Puffcorn"]),
    P("Chilli Chatka", "Kurkure", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Fiery puffed snack with a hit of green chilli.",
      subcategory="Extruded", ingredient_tags=["namkeen", "kurkure"],
      search=["kurkure", "chilli"], image_queries=["kurkure chilli chatka pack"],
      related=["Masala Munch", "Magic Masala Lay's"]),
    P("Classic Salted Lay's", "Lay's", "Snacks & Namkeen", [("52 g", 10, 52, "g")],
      "Thin crisps with the original salted taste.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["lays", "chips"], image_queries=["lays classic salted pack"],
      related=["Magic Masala Lay's", "Plain Salted Wafers"]),
    P("Magic Masala Lay's", "Lay's", "Snacks & Namkeen", [("52 g", 10, 52, "g")],
      "India's iconic masala potato chips.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["lays magic masala"], image_queries=["lays magic masala pack"],
      related=["Tomato Tango Lay's", "Classic Salted Lay's"]),
    P("Tomato Tango Lay's", "Lay's", "Snacks & Namkeen", [("52 g", 10, 52, "g")],
      "Sweet-tangy tomato chips.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["lays tomato"], image_queries=["lays tomato tango pack"],
      related=["Magic Masala Lay's", "Cream & Onion Uncle Chips"]),
    P("Nawab's Choice Uncle Chips", "Uncle Chips", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Royal masala potato chips.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["uncle chips"], image_queries=["uncle chips nawabs choice pack"],
      related=["Mumbai Masti Uncle Chips", "Magic Masala Lay's"]),
    P("Mumbai Masti Uncle Chips", "Uncle Chips", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Chatpata Mumbai-style chips.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["uncle chips mumbai"], image_queries=["uncle chips mumbai masti pack"],
      related=["Nawab's Choice Uncle Chips", "Chilli Chatka"]),
    P("Achari Masti Mad Angles", "Mad Angles", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Triangle crisps with a pickle masala.",
      subcategory="Extruded", ingredient_tags=["namkeen", "mad angles"],
      search=["mad angles", "achari"], image_queries=["mad angles achari masti pack"],
      related=["Pizza Masti Mad Angles", "Masala Munch"]),
    P("Pizza Masti Mad Angles", "Mad Angles", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Cheesy triangle crisps.",
      subcategory="Extruded", ingredient_tags=["namkeen", "mad angles"],
      search=["mad angles pizza"], image_queries=["mad angles pizza masti pack"],
      related=["Achari Masti Mad Angles", "Masala Munch"]),
    P("Multigrain Chips", "Too Yumm", "Snacks & Namkeen", [("70 g", 30, 70, "g")],
      "Baked multigrain chips, 30% less fat.",
      subcategory="Chips", veg=True, ingredient_tags=["chips", "healthy"],
      search=["too yumm", "multigrain chips"], image_queries=["too yumm multigrain chips pack"],
      related=["Quinoa Chips", "Beetroot Chips"]),
    P("Quinoa Chips", "Too Yumm", "Snacks & Namkeen", [("70 g", 35, 70, "g")],
      "Baked quinoa crisps with herbs.",
      subcategory="Chips", veg=True, ingredient_tags=["chips", "healthy"],
      search=["too yumm quinoa"], image_queries=["too yumm quinoa chips pack"],
      related=["Multigrain Chips", "Beetroot Chips"]),
    P("Beetroot Chips", "Too Yumm", "Snacks & Namkeen", [("70 g", 35, 70, "g")],
      "Baked beetroot crisps, naturally pink.",
      subcategory="Chips", veg=True, ingredient_tags=["chips", "healthy"],
      search=["too yumm beetroot"], image_queries=["too yumm beetroot chips pack"],
      related=["Quinoa Chips", "Multigrain Chips"]),
    P("Sev Murmura", "Balaji", "Snacks & Namkeen", [("200 g", 28, 200, "g")],
      "Puffed-rice and sev namkeen, light and crunchy.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "sev murmura"],
      search=["sev murmura", "bhel mix"], image_queries=["balaji sev murmura pack"],
      related=["Chana Chor Garam", "Bhujiya"]),
    P("Chana Chor Garam", "Balaji", "Snacks & Namkeen", [("200 g", 28, 200, "g")],
      "Spicy flattened-chickpea snack.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "chana"],
      search=["chana chor garam"], image_queries=["balaji chana chor garam pack"],
      related=["Sev Murmura", "Moong Dal"]),
    P("Pudina Chips", "Haldiram's", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Haldiram's mint-flavoured potato chips.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["pudina chips"], image_queries=["haldiram pudina chips pack"],
      related=["Aloo Bhujia", "Classic Salted Lay's"]),
    P("Wafer Style Lay's", "Lay's", "Snacks & Namkeen", [("90 g", 20, 90, "g")],
      "Extra-thin ripple wafers.",
      subcategory="Chips", ingredient_tags=["chips", "wafers"],
      search=["lays wafers"], image_queries=["lays wafer style pack"],
      related=["Magic Masala Lay's", "Plain Salted Wafers"]),
    P("Puffcorn", "Kurkure", "Snacks & Namkeen", [("55 g", 10, 55, "g")],
      "Airy puffed corn in cheese flavour.",
      subcategory="Extruded", ingredient_tags=["namkeen", "puffcorn"],
      search=["kurkure puffcorn"], image_queries=["kurkure puffcorn pack"],
      related=["Masala Munch", "Chilli Chatka"]),
    P("Aam Chulbul", "Haldiram's", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Sweet mango-flavoured chewy candy.",
      subcategory="Sweets", ingredient_tags=["sweet", "candy"],
      search=["aam chulbul", "mango candy"], image_queries=["haldiram aam chulbul pack"],
      related=["Imli Candy", "Soan Papdi"]),
    P("Imli Candy", "Haldiram's", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Tangy tamarind sweet balls.",
      subcategory="Sweets", ingredient_tags=["sweet", "candy"],
      search=["imli candy"], image_queries=["haldiram imli candy pack"],
      related=["Aam Chulbul", "Khatta Meetha"]),
    P("Cheesling", "Haldiram's", "Snacks & Namkeen", [("200 g", 30, 200, "g")],
      "Tiny cheese crackers.",
      subcategory="Extruded", ingredient_tags=["namkeen", "crackers"],
      search=["cheesling"], image_queries=["haldiram cheesling pack"],
      related=["Pudina Chips", "Mathri"]),
    P("Fried Peanuts", "Haldiram's", "Snacks & Namkeen", [("200 g", 40, 200, "g")],
      "Salt-and-pepper fried peanuts.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "peanut"],
      search=["fried peanuts"], image_queries=["haldiram fried peanuts pack"],
      related=["Masala Peanuts", "Moong Dal"]),
    P("Masala Peanuts", "Haldiram's", "Snacks & Namkeen", [("200 g", 42, 200, "g")],
      "Chatpata roasted peanuts.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "peanut"],
      search=["masala peanuts"], image_queries=["haldiram masala peanuts pack"],
      related=["Fried Peanuts", "Moong Dal"]),
    P("Bikaneri Papad", "Bikaji", "Snacks & Namkeen", [("200 g", 45, 200, "g")],
      "Moong papad from Bikaner.",
      subcategory="Papad", ingredient_tags=["papad"],
      search=["bikaneri papad", "papad"], image_queries=["bikaji bikaneri papad pack"],
      related=["Masala Papad", "Moong Dal"]),
    P("Mawa Kachori", "Bikaji", "Snacks & Namkeen", [("200 g", 120, 200, "g")],
      "Rajasthani sweet kachori filled with mawa.",
      subcategory="Sweets", ingredient_tags=["sweet", "kachori"],
      search=["mawa kachori"], image_queries=["bikaji mawa kachori pack"],
      related=["Kaju Katli", "Soan Cake"]),
    P("Bengal Gram Laddu", "Haldiram's", "Snacks & Namkeen", [("500 g", 160, 500, "g")],
      "Besan laddus with ghee and raisins.",
      subcategory="Sweets", ingredient_tags=["sweet", "laddu"],
      search=["besan laddu", "laddu"], image_queries=["haldiram besan laddu box"],
      related=["Kaju Katli", "Rasgulla"]),
    P("Kaju Anjeer Roll", "Haldiram's", "Snacks & Namkeen", [("200 g", 250, 200, "g")],
      "Cashew and fig rolls with cardamom.",
      subcategory="Sweets", ingredient_tags=["sweet", "kaju"],
      search=["kaju anjeer roll"], image_queries=["haldiram kaju anjeer roll box"],
      related=["Kaju Katli", "Soan Papdi"]),
    P("Soan Cake", "Haldiram's", "Snacks & Namkeen", [("200 g", 80, 200, "g")],
      "Soft cardamom-soan cake.",
      subcategory="Sweets", ingredient_tags=["sweet", "soan"],
      search=["soan cake"], image_queries=["haldiram soan cake pack"],
      related=["Soan Papdi", "Shakarpara"]),
    P("Bhakarwadi", "Haldiram's", "Snacks & Namkeen", [("200 g", 50, 200, "g")],
      "Maharashtrian pinwheel snack, sweet and spicy.",
      subcategory="Namkeen", ingredient_tags=["namkeen", "bhakarwadi"],
      search=["bhakarwadi"], image_queries=["haldiram bhakarwadi pack"],
      related=["Gathiya", "Chakli"]),
]
