"""Curated Indian catalog - part 10: second backfill (push laggards to 50+).

Targets: Dairy 23->50, Atta/Rice/Dal 33->50, Home 39->50, Pickles 40->50,
Fruits & Veg 42->50, Masala 42->50, Beverages 45->50, Personal 47->50,
Instant & Frozen 49->50.
"""

from .schema import P

# Dairy & Eggs (need ~27) ----------------------------------------------------- #
DAIRY2 = [
    P("Amul Cheese Spreads", "Amul", "Dairy & Eggs", [("200 g", 95, 200, "g")],
      "Cheese spread in a tub, plain.",
      subcategory="Cheese", ingredient_tags=["cheese", "spread"],
      search=["amul cheese spread"], image_queries=["amul cheese spread pack"],
      related=["Amul Cheese Slices", "Cheese Spread"]),
    P("Amul Pro", "Amul", "Dairy & Eggs", [("500 g", 280, 500, "g")],
      "Milk protein health drink.",
      subcategory="Health Drink", ingredient_tags=["health drink", "milk"],
      search=["amul pro"], image_queries=["amul pro pack"],
      related=["Bournvita", "Complan"]),
    P("Amul Kool", "Amul", "Dairy & Eggs", [("200 ml", 30, 200, "ml")],
      "Flavoured milk, strawberry.",
      subcategory="Dairy Drink", ingredient_tags=["milk", "flavoured"],
      search=["amul kool", "flavoured milk"], image_queries=["amul kool pack"],
      related=["Amul Gold Full Cream Milk", "Amul Lassi Sweet"]),
    P("Amul Masti Buttermilk", "Amul", "Dairy & Eggs", [("200 ml", 15, 200, "ml")],
      "Spiced buttermilk, masala chaas.",
      subcategory="Dairy Drink", ingredient_tags=["buttermilk", "chaas"],
      search=["amul masti buttermilk"], image_queries=["amul masti buttermilk pack"],
      related=["Amul Buttermilk Masala Chaas", "Amul Masti Dahi"]),
    P("Mother Dairy Turmeric Milk", "Mother Dairy", "Dairy & Eggs", [("200 ml", 30, 200, "ml")],
      "Haldi doodh turmeric milk.",
      subcategory="Dairy Drink", ingredient_tags=["milk", "turmeric"],
      search=["turmeric milk", "haldi doodh"], image_queries=["turmeric milk pack"],
      related=["Amul Gold Full Cream Milk", "Amul Kool"]),
    P("Nandini Milk", "Nandini", "Dairy & Eggs", [("500 ml", 26, 500, "ml")],
      "Pasteurised toned milk in a pouch.",
      subcategory="Milk", ingredient_tags=["milk"],
      search=["nandini milk"], image_queries=["nandini milk pack"],
      related=["Amul Taaza Toned Milk", "Mother Dairy Toned Milk"]),
    P("Nandini Curd", "Nandini", "Dairy & Eggs", [("400 g", 45, 400, "g")],
      "Set curd, South-Indian style.",
      subcategory="Curd", ingredient_tags=["curd", "dahi"],
      search=["nandini curd"], image_queries=["nandini curd pack"],
      related=["Amul Masti Dahi Curd", "Mother Dairy Classic Curd"]),
    P("Nandini Paneer", "Nandini", "Dairy & Eggs", [("200 g", 92, 200, "g")],
      "Fresh cottage cheese.",
      subcategory="Paneer", ingredient_tags=["paneer"],
      search=["nandini paneer"], image_queries=["nandini paneer pack"],
      related=["Amul Fresh Paneer", "Mother Dairy Paneer"]),
    P("Mother Dairy Paneer", "Mother Dairy", "Dairy & Eggs", [("200 g", 95, 200, "g")],
      "Fresh cottage cheese block, soft.",
      subcategory="Paneer", ingredient_tags=["paneer"],
      search=["mother dairy paneer"], image_queries=["mother dairy paneer pack"],
      related=["Amul Fresh Paneer", "Nandini Paneer"]),
    P("Go Cheese Slices", "Go", "Dairy & Eggs", [("100 g", 80, 100, "g")],
      "Processed cheese slices.",
      subcategory="Cheese", ingredient_tags=["cheese", "slice"],
      search=["go cheese"], image_queries=["go cheese slices pack"],
      related=["Amul Cheese Slices", "Amul Cheese Spreads"]),
    P("Go Cheese Spread", "Go", "Dairy & Eggs", [("100 g", 75, 100, "g")],
      "Cheese spread in a tub for sandwiches.",
      subcategory="Cheese", ingredient_tags=["cheese", "spread"],
      search=["go cheese spread"], image_queries=["go cheese spread pack"],
      related=["Amul Cheese Spreads", "Go Cheese Slices"]),
    P("Britannia Cheese", "Britannia", "Dairy & Eggs", [("100 g", 78, 100, "g")],
      "Block processed cheese.",
      subcategory="Cheese", ingredient_tags=["cheese", "block"],
      search=["britannia cheese"], image_queries=["britannia cheese pack"],
      related=["Amul Cheese Slices", "Go Cheese Slices"]),
    P("Nilgiri Yogurt", "Nilgiri", "Dairy & Eggs", [("400 g", 50, 400, "g")],
      "Creamy set yogurt in a cup.",
      subcategory="Curd", ingredient_tags=["curd", "yogurt"],
      search=["yogurt", "nilgiri"], image_queries=["nilgiri yogurt pack"],
      related=["Amul Masti Dahi Curd", "Mother Dairy Classic Curd"]),
    P("Epigam Milk", "Epigam", "Dairy & Eggs", [("500 ml", 27, 500, "ml")],
      "Full-cream rich dairy milk.",
      subcategory="Milk", ingredient_tags=["milk"],
      search=["epigam milk"], image_queries=["epigam milk pack"],
      related=["Amul Gold Full Cream Milk", "Nandini Milk"]),
    P("Double Tonned Milk", "Amul", "Dairy & Eggs", [("500 ml", 25, 500, "ml")],
      "Double-toned milk, low fat.",
      subcategory="Milk", ingredient_tags=["milk", "toned"],
      search=["double toned milk"], image_queries=["amul double toned milk pack"],
      related=["Amul Taaza Toned Milk", "Mother Dairy Toned Milk"]),
    P("Skimmed Milk", "Mother Dairy", "Dairy & Eggs", [("500 ml", 26, 500, "ml")],
      "Fat-free skimmed milk.",
      subcategory="Milk", ingredient_tags=["milk", "skimmed"],
      search=["skimmed milk"], image_queries=["mother dairy skimmed milk pack"],
      related=["Double Tonned Milk", "Amul Taaza Toned Milk"]),
    P("Condensed Milk", "Nestle", "Dairy & Eggs", [("400 g", 110, 400, "g")],
      "Sweetened condensed milk.",
      subcategory="Milk", ingredient_tags=["condensed milk", "milk"],
      search=["condensed milk", "milkmaid"], image_queries=["nestle condensed milk pack"],
      related=["Fresh Cream", "Khoya"]),
    P("Khoya", "Fresh", "Dairy & Eggs", [("200 g", 90, 200, "g")],
      "Reduced-milk khoya for sweets.",
      subcategory="Milk", ingredient_tags=["khoya", "mawa"],
      search=["khoya", "mawa"], image_queries=["khoya pack"],
      related=["Condensed Milk", "Amul Pure Ghee"]),
    P("Fresh Paneer Homemade", "Fresh", "Dairy & Eggs", [("200 g", 85, 200, "g")],
      "Soft homemade-style paneer.",
      subcategory="Paneer", ingredient_tags=["paneer"],
      search=["fresh paneer"], image_queries=["fresh paneer pack"],
      related=["Amul Fresh Paneer", "Nandini Paneer"]),
    P("Boiled Eggs", "Fresh Farm", "Dairy & Eggs", [("6 pieces", 48, 300, "g")],
      "Pre-boiled eggs, ready to eat.",
      subcategory="Eggs", ingredient_tags=["egg", "boiled"],
      search=["boiled eggs"], image_queries=["boiled eggs pack"],
      related=["Fresh Farm Eggs", "Egg White"]),
    P("Egg White", "Fresh Farm", "Dairy & Eggs", [("6 pieces", 50, 300, "g")],
      "Separated egg whites, pack of 6.",
      subcategory="Eggs", ingredient_tags=["egg", "white"],
      search=["egg white"], image_queries=["egg white pack"],
      related=["Fresh Farm Eggs", "Boiled Eggs"]),
    P("Brown Eggs", "Fresh Farm", "Dairy & Eggs", [("6 pieces", 46, 300, "g")],
      "Omega-rich brown eggs.",
      subcategory="Eggs", ingredient_tags=["egg", "brown"],
      search=["brown eggs"], image_queries=["brown eggs pack"],
      related=["Fresh Farm Eggs", "Boiled Eggs"]),
    P("Cheese Cubes", "Amul", "Dairy & Eggs", [("200 g", 95, 200, "g")],
      "Diced processed cheese cubes.",
      subcategory="Cheese", ingredient_tags=["cheese", "cube"],
      search=["cheese cubes"], image_queries=["amul cheese cubes pack"],
      related=["Amul Cheese Slices", "Go Cheese Slices"]),
    P("Curd Set", "Amul", "Dairy & Eggs", [("1 kg", 95, 1000, "g")],
      "Large set curd for the family.",
      subcategory="Curd", ingredient_tags=["curd", "dahi"],
      search=["amul curd", "dahi"], image_queries=["amul curd pack"],
      related=["Amul Masti Dahi Curd", "Mother Dairy Classic Curd"]),
    P("Flavoured Yogurt Mango", "Amul", "Dairy & Eggs", [("90 g", 30, 90, "g")],
      "Mango-flavoured yogurt cup.",
      subcategory="Curd", ingredient_tags=["yogurt", "mango"],
      search=["flavoured yogurt"], image_queries=["amul mango yogurt pack"],
      related=["Nilgiri Yogurt", "Amul Masti Dahi Curd"]),
    P("Probiotic Curd", "Mother Dairy", "Dairy & Eggs", [("400 g", 48, 400, "g")],
      "Curd with active cultures.",
      subcategory="Curd", ingredient_tags=["curd", "probiotic"],
      search=["probiotic curd"], image_queries=["mother dairy probiotic curd pack"],
      related=["Mother Dairy Classic Curd", "Amul Masti Dahi Curd"]),
    P("Butter Unsalted", "Amul", "Dairy & Eggs", [("100 g", 55, 100, "g")],
      "Unsalted white butter.",
      subcategory="Butter", ingredient_tags=["butter", "unsalted"],
      search=["unsalted butter"], image_queries=["amul unsalted butter pack"],
      related=["Amul Butter Salted", "Amul Cheese Slices"]),
    P("Cream Cheese", "Britannia", "Dairy & Eggs", [("100 g", 90, 100, "g")],
      "Spreadable cream cheese.",
      subcategory="Cheese", ingredient_tags=["cheese", "cream"],
      search=["cream cheese"], image_queries=["britannia cream cheese pack"],
      related=["Amul Cheese Spreads", "Go Cheese Spread"]),
]

# Atta, Rice & Dal (need ~17) ------------------------------------------------- #
ATTA2 = [
    P("Patanjali Whole Wheat Atta", "Patanjali", "Atta, Rice & Dal", [("1 kg", 55, 1000, "g")],
      "Stone-ground whole wheat atta.",
      subcategory="Atta", veg=True, ingredient_tags=["atta", "wheat"],
      search=["patanjali atta"], image_queries=["patanjali atta pack"],
      related=["Aashirvaad Whole Wheat Atta", "Fortune Chakki Fresh Atta"]),
    P("Shakti Bhog Atta", "Shakti Bhog", "Atta, Rice & Dal", [("1 kg", 50, 1000, "g")],
      "Multi-grain wheat flour.",
      subcategory="Atta", veg=True, ingredient_tags=["atta", "wheat"],
      search=["shakti bhog atta"], image_queries=["shakti bhog atta pack"],
      related=["Aashirvaad Whole Wheat Atta", "Patanjali Whole Wheat Atta"]),
    P("Pillsbury Chakki Atta", "Pillsbury", "Atta, Rice & Dal", [("1 kg", 58, 1000, "g")],
      "Chakki-fresh wheat flour.",
      subcategory="Atta", veg=True, ingredient_tags=["atta", "wheat"],
      search=["pillsbury atta"], image_queries=["pillsbury chakki atta pack"],
      related=["Fortune Chakki Fresh Atta", "Aashirvaad Whole Wheat Atta"]),
    P("Wheat Flour Maida", "Rajdhani", "Atta, Rice & Dal", [("1 kg", 42, 1000, "g")],
      "Refined all-purpose flour.",
      subcategory="Flour", veg=True, ingredient_tags=["maida", "flour"],
      search=["maida", "refined flour"], image_queries=["maida pack"],
      related=["Rajdhani Maida Refined Flour", "Rajdhani Sooji Rava"]),
    P("Bajra Flour", "Rajdhani", "Atta, Rice & Dal", [("1 kg", 55, 1000, "g")],
      "Pearl millet flour for rotla.",
      subcategory="Flour", veg=True, ingredient_tags=["bajra", "flour"],
      search=["bajra flour", "pearl millet"], image_queries=["bajra flour pack"],
      related=["Jowar Flour", "Rajdhani Besan Gram Flour"]),
    P("Jowar Flour", "Rajdhani", "Atta, Rice & Dal", [("1 kg", 52, 1000, "g")],
      "Sorghum flour for bhakri.",
      subcategory="Flour", veg=True, ingredient_tags=["jowar", "flour"],
      search=["jowar flour", "sorghum"], image_queries=["jowar flour pack"],
      related=["Bajra Flour", "Rajdhani Besan Gram Flour"]),
    P("Ragi Flour", "Rajdhani", "Atta, Rice & Dal", [("1 kg", 60, 1000, "g")],
      "Finger-millet flour, iron-rich.",
      subcategory="Flour", veg=True, ingredient_tags=["ragi", "flour"],
      search=["ragi flour", "finger millet"], image_queries=["ragi flour pack"],
      related=["Jowar Flour", "Bajra Flour"]),
    P("Kuttu Atta", "Rajdhani", "Atta, Rice & Dal", [("500 g", 70, 500, "g")],
      "Buckwheat flour for fasting.",
      subcategory="Flour", veg=True, ingredient_tags=["kuttu", "buckwheat"],
      search=["kuttu atta", "buckwheat flour"], image_queries=["kuttu atta pack"],
      related=["Singhara Atta", "Rajdhani Besan Gram Flour"]),
    P("Singhara Atta", "Rajdhani", "Atta, Rice & Dal", [("500 g", 65, 500, "g")],
      "Water-chestnut flour for vrat.",
      subcategory="Flour", veg=True, ingredient_tags=["singhara", "flour"],
      search=["singhara atta"], image_queries=["singhara atta pack"],
      related=["Kuttu Atta", "Rajdhani Besan Gram Flour"]),
    P("Sabudana", "Rajdhani", "Atta, Rice & Dal", [("500 g", 60, 500, "g")],
      "Tapioca pearls for khichdi.",
      subcategory="Flour", veg=True, ingredient_tags=["sabudana", "tapioca"],
      search=["sabudana"], image_queries=["sabudana pack"],
      related=["Kuttu Atta", "Singhara Atta"]),
    P("Samba Rice", "India Gate", "Atta, Rice & Dal", [("1 kg", 110, 1000, "g")],
      "Short-grain South-Indian rice.",
      subcategory="Rice", veg=True, ingredient_tags=["rice", "samba"],
      search=["samba rice"], image_queries=["samba rice pack"],
      related=["India Gate Classic Basmati Rice", "Ponni Rice"]),
    P("Ponni Rice", "India Gate", "Atta, Rice & Dal", [("1 kg", 95, 1000, "g")],
      "Tamil Nadu parboiled rice.",
      subcategory="Rice", veg=True, ingredient_tags=["rice", "ponni"],
      search=["ponni rice"], image_queries=["ponni rice pack"],
      related=["Samba Rice", "Daawat Everyday Basmati Rice"]),
    P("Jeera Rice", "Tata Sampann", "Atta, Rice & Dal", [("1 kg", 130, 1000, "g")],
      "Cumin-flavoured ready rice.",
      subcategory="Rice", veg=True, ingredient_tags=["rice", "jeera"],
      search=["jeera rice"], image_queries=["jeera rice pack"],
      related=["India Gate Classic Basmati Rice", "Samba Rice"]),
    P("Kolam Rice", "Daawat", "Atta, Rice & Dal", [("1 kg", 85, 1000, "g")],
      "Everyday medium-grain rice.",
      subcategory="Rice", veg=True, ingredient_tags=["rice", "kolam"],
      search=["kolam rice"], image_queries=["kolam rice pack"],
      related=["Daawat Everyday Basmati Rice", "Ponni Rice"]),
    P("Brown Rice", "24 Mantra", "Atta, Rice & Dal", [("1 kg", 140, 1000, "g")],
      "Unpolished organic brown rice.",
      subcategory="Rice", veg=True, ingredient_tags=["rice", "brown"],
      search=["brown rice", "organic"], image_queries=["brown rice pack"],
      related=["24 Mantra Organic Sona Masoori Rice", "Kolam Rice"]),
    P("Poha Red", "Rajdhani", "Atta, Rice & Dal", [("500 g", 48, 500, "g")],
      "Red flattened rice for poha.",
      subcategory="Flattened Rice", veg=True, ingredient_tags=["poha", "rice"],
      search=["red poha"], image_queries=["red poha pack"],
      related=["Poha Thick", "Poha Thin"]),
    P("Poha Thin", "Rajdhani", "Atta, Rice & Dal", [("500 g", 46, 500, "g")],
      "Thin flattened rice.",
      subcategory="Flattened Rice", veg=True, ingredient_tags=["poha", "rice"],
      search=["thin poha"], image_queries=["thin poha pack"],
      related=["Poha Thick", "Poha Red"]),
    P("Vermicelli Roasted", "Rajdhani", "Atta, Rice & Dal", [("500 g", 50, 500, "g")],
      "Roasted semia for sevai.",
      subcategory="Flour", veg=True, ingredient_tags=["vermicelli", "sevai"],
      search=["vermicelli", "sevai"], image_queries=["roasted vermicelli pack"],
      related=["Sooji Rava", "Idli Rava"]),
    P("Rajma Red", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 90, 500, "g")],
      "Dark red kidney beans.",
      subcategory="Dal", veg=True, ingredient_tags=["rajma", "beans"],
      search=["rajma", "kidney beans"], image_queries=["rajma red pack"],
      related=["Tata Sampann Rajma Chitra", "Tata Sampann Kabuli Chana"]),
    P("Lobia", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 80, 500, "g")],
      "Black-eyed beans, also called lobia.",
      subcategory="Dal", veg=True, ingredient_tags=["lobia", "beans"],
      search=["lobia", "black eyed beans"], image_queries=["lobia pack"],
      related=["Tata Sampann Moong Dal", "Tata Sampann Rajma Red"]),
    P("Green Moong Whole", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 80, 500, "g")],
      "Whole green gram, also called sabut moong.",
      subcategory="Dal", veg=True, ingredient_tags=["moong", "dal"],
      search=["whole moong", "sabut moong"], image_queries=["whole green moong pack"],
      related=["Tata Sampann Moong Dal", "Tata Sampann Urad Dal"]),
    P("Chana Whole", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 75, 500, "g")],
      "Whole brown chickpeas.",
      subcategory="Dal", veg=True, ingredient_tags=["chana", "chickpea"],
      search=["whole chana"], image_queries=["whole chana pack"],
      related=["Tata Sampann Kabuli Chana", "Tata Sampann Chana Dal"]),
    P("Toor Dal Fine", "Tata Sampann", "Atta, Rice & Dal", [("1 kg", 190, 1000, "g")],
      "Fine-polyished toor dal.",
      subcategory="Dal", veg=True, ingredient_tags=["toor", "dal"],
      search=["toor dal fine"], image_queries=["toor dal fine pack"],
      related=["Tata Sampann Toor Dal", "Tata Sampann Moong Dal"]),
    P("Soya Chunks", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 90, 500, "g")],
      "Protein-rich soya chunks.",
      subcategory="Dal", veg=True, ingredient_tags=["soya", "chunk"],
      search=["soya chunks", "meal maker"], image_queries=["soya chunks pack"],
      related=["Soya Granules", "Tata Sampann Moong Dal"]),
    P("Soya Granules", "Tata Sampann", "Atta, Rice & Dal", [("500 g", 85, 500, "g")],
      "Fine soya granules for curry.",
      subcategory="Dal", veg=True, ingredient_tags=["soya", "granule"],
      search=["soya granules"], image_queries=["soya granules pack"],
      related=["Soya Chunks", "Tata Sampann Kabuli Chana"]),
]

# Masala & Spices (need ~8) --------------------------------------------------- #
MASALA2 = [
    P("Sambhar Masala", "MTR", "Masala & Spices", [("200 g", 85, 200, "g")],
      "South-Indian sambhar blend.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["sambhar", "masala"],
      search=["sambhar masala"], image_queries=["mtr sambhar masala pack"],
      related=["Sambar Powder", "Rasam Powder"]),
    P("Biryani Masala", "Everest", "Masala & Spices", [("100 g", 50, 100, "g")],
      "Whole-spice blend for biryani.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["biryani", "masala"],
      search=["biryani masala"], image_queries=["everest biryani masala pack"],
      related=["Garam Masala", "India Gate Classic Basmati Rice"]),
    P("Meat Masala", "Everest", "Masala & Spices", [("100 g", 52, 100, "g")],
      "Spice blend for non-veg curries.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["meat masala", "masala"],
      search=["meat masala"], image_queries=["everest meat masala pack"],
      related=["Garam Masala", "Coriander Powder"]),
    P("Fish Fry Masala", "Everest", "Masala & Spices", [("100 g", 50, 100, "g")],
      "Coating masala for fried fish.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["fish fry", "masala"],
      search=["fish fry masala"], image_queries=["everest fish fry masala pack"],
      related=["Meat Masala", "Red Chilli Powder"]),
    P("Kitchen King Masala", "MDH", "Masala & Spices", [("100 g", 55, 100, "g")],
      "All-round vegetable masala.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["kitchen king", "masala"],
      search=["kitchen king masala"], image_queries=["mdh kitchen king masala pack"],
      related=["Garam Masala", "Coriander Powder"]),
    P("Shahi Paneer Masala", "MDH", "Masala & Spices", [("100 g", 58, 100, "g")],
      "Rich masala for shahi paneer.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["shahi paneer", "masala"],
      search=["shahi paneer masala"], image_queries=["mdh shahi paneer masala pack"],
      related=["Garam Masala", "Amul Fresh Paneer"]),
    P("Tandoori Masala", "MDH", "Masala & Spices", [("100 g", 56, 100, "g")],
      "Spice mix for tandoori dishes.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["tandoori", "masala"],
      search=["tandoori masala"], image_queries=["mdh tandoori masala pack"],
      related=["Garam Masala", "Meat Masala"]),
    P("Chana Masala", "MDH", "Masala & Spices", [("100 g", 52, 100, "g")],
      "Spice blend for chole.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["chana masala", "masala"],
      search=["chana masala"], image_queries=["mdh chana masala pack"],
      related=["Garam Masala", "Everest Dry Mango Powder Amchur"]),
    P("Goda Masala", "MDH", "Masala & Spices", [("100 g", 54, 100, "g")],
      "Maharashtrian sweet spice blend.",
      subcategory="Spice Blend", veg=True, ingredient_tags=["goda", "masala"],
      search=["goda masala"], image_queries=["mdh goda masala pack"],
      related=["Garam Masala", "Pav Bhaji Masala"]),
    P("Black Pepper", "Everest", "Masala & Spices", [("100 g", 95, 100, "g")],
      "Whole black peppercorns.",
      subcategory="Whole Spice", veg=True, ingredient_tags=["black pepper", "pepper"],
      search=["black pepper", "kali mirch"], image_queries=["everest black pepper pack"],
      related=["Cumin Seeds", "Cloves"]),
    P("Cinnamon", "Everest", "Masala & Spices", [("50 g", 80, 50, "g")],
      "Whole cinnamon sticks.",
      subcategory="Whole Spice", veg=True, ingredient_tags=["cinnamon", "dalchini"],
      search=["cinnamon", "dalchini"], image_queries=["cinnamon sticks pack"],
      related=["Cloves", "Catch Green Cardamom"]),
]

# Fruits & Vegetables (need ~8) ----------------------------------------------- #
FRESH2 = [
    P("Fresh Garlic", "Fresh", "Fruits & Vegetables", [("500 g", 35, 500, "g")],
      "Pungent white garlic bulbs.",
      subcategory="Vegetables", veg=True, ingredient_tags=["garlic", "lehsun"],
      search=["garlic", "lehsun"], image_queries=["fresh garlic pack"],
      related=["Fresh Ginger", "Fresh Onion"]),
    P("Fresh Ginger", "Fresh", "Fruits & Vegetables", [("500 g", 40, 500, "g")],
      "Fresh knobby ginger root for cooking.",
      subcategory="Vegetables", veg=True, ingredient_tags=["ginger", "adrak"],
      search=["ginger", "adrak"], image_queries=["fresh ginger pack"],
      related=["Fresh Garlic", "Fresh Turmeric"]),
    P("Fresh Turmeric", "Fresh", "Fruits & Vegetables", [("500 g", 30, 500, "g")],
      "Raw turmeric rhizome.",
      subcategory="Vegetables", veg=True, ingredient_tags=["turmeric", "haldi"],
      search=["raw turmeric", "haldi"], image_queries=["fresh turmeric pack"],
      related=["Fresh Ginger", "Everest Turmeric Powder"]),
    P("Green Chilli", "Fresh", "Fruits & Vegetables", [("500 g", 25, 500, "g")],
      "Fresh hot green chillies, spicy.",
      subcategory="Vegetables", veg=True, ingredient_tags=["green chilli", "mirchi"],
      search=["green chilli", "hari mirch"], image_queries=["green chilli pack"],
      related=["Fresh Garlic", "Fresh Ginger"]),
    P("Curry Leaves", "Fresh", "Fruits & Vegetables", [("100 g", 15, 100, "g")],
      "Aromatic curry patta.",
      subcategory="Vegetables", veg=True, ingredient_tags=["curry leaves", "kadi patta"],
      search=["curry leaves", "kadi patta"], image_queries=["curry leaves pack"],
      related=["Fresh Coriander", "Fresh Mint Leaves"]),
    P("Fresh Lemon", "Fresh", "Fruits & Vegetables", [("500 g", 30, 500, "g")],
      "Tart juicy lemons for garnish.",
      subcategory="Fruits", veg=True, ingredient_tags=["lemon", "nimbu"],
      search=["lemon", "nimbu"], image_queries=["fresh lemon pack"],
      related=["Green Chilli", "Fresh Coriander"]),
    P("Drumstick", "Fresh", "Fruits & Vegetables", [("500 g", 35, 500, "g")],
      "Moringa drumsticks for sambar.",
      subcategory="Vegetables", veg=True, ingredient_tags=["drumstick", "moringa"],
      search=["drumstick", "moringa"], image_queries=["drumstick pack"],
      related=["Fresh Tomato", "Brinjal"]),

    P("Bottle Gourd", "Fresh", "Fruits & Vegetables", [("500 g", 22, 500, "g")],
      "Lauki bottle gourd for sabzi.",
      subcategory="Vegetables", veg=True, ingredient_tags=["bottle gourd", "lauki"],
      search=["bottle gourd", "lauki"], image_queries=["bottle gourd pack"],
      related=["Drumstick", "Ridge Gourd"]),
    P("Bitter Gourd", "Fresh", "Fruits & Vegetables", [("500 g", 28, 500, "g")],
      "Karela bitter gourd.",
      subcategory="Vegetables", veg=True, ingredient_tags=["bitter gourd", "karela"],
      search=["bitter gourd", "karela"], image_queries=["bitter gourd pack"],
      related=["Bottle Gourd", "Ridge Gourd"]),
    P("Raw Banana", "Fresh", "Fruits & Vegetables", [("500 g", 25, 500, "g")],
      "Green cooking bananas.",
      subcategory="Vegetables", veg=True, ingredient_tags=["raw banana", "kaccha kela"],
      search=["raw banana", "kaccha kela"], image_queries=["raw banana pack"],
      related=["Fresh Banana", "Potato"]),
]
