"""Curated Indian catalog - part 11: third backfill (final laggards to 50+).

Targets: Beverages 45->50, Home Care 39->50, Instant & Frozen 49->50,
Personal Care 47->50, Pickles/Papad/Sauces 40->50.
"""

from .schema import P

# Beverages (need ~5) --------------------------------------------------------- #
BEV2 = [
    P("Lemon Soda", "Bisleri", "Beverages", [("750 ml", 40, 750, "ml")],
      "Tangy lemon-flavoured soda.",
      subcategory="Fizzy", veg=True, ingredient_tags=["lemon soda", "soda"],
      search=["lemon soda"], image_queries=["lemon soda pack"],
      related=["Bisleri Soda", "Bisleri Limonata"]),
    P("Club Soda", "Bisleri", "Beverages", [("750 ml", 35, 750, "ml")],
      "Plain carbonated club soda.",
      subcategory="Fizzy", veg=True, ingredient_tags=["soda", "club soda"],
      search=["club soda"], image_queries=["club soda pack"],
      related=["Bisleri Soda", "Lemon Soda"]),
    P("Mango Frooti", "Parle", "Beverages", [("600 ml", 35, 600, "ml")],
      "Mango fruit drink, Frooti.",
      subcategory="Juice", veg=True, ingredient_tags=["mango drink", "juice"],
      search=["frooti", "mango drink"], image_queries=["frooti pack"],
      related=["Parle Appy Fizz", "Tropicana Mango"]),
    P("Maaza", "Coca-Cola", "Beverages", [("600 ml", 40, 600, "ml")],
      "Mango fruit beverage, Maaza.",
      subcategory="Juice", veg=True, ingredient_tags=["mango", "juice"],
      search=["maaza"], image_queries=["maaza pack"],
      related=["Mango Frooti", "Tropicana Mango"]),
    P("Iced Tea Peach", "Lipton", "Beverages", [("500 ml", 50, 500, "ml")],
      "Ready peach iced tea.",
      subcategory="Tea Drink", veg=True, ingredient_tags=["iced tea", "tea"],
      search=["iced tea"], image_queries=["lipton iced tea pack"],
      related=["Lipton Green Tea", "Lipton Lemon Tea"]),
    P("Coconut Water", "Tender", "Beverages", [("200 ml", 45, 200, "ml")],
      "Natural tender coconut water.",
      subcategory="Juice", veg=True, ingredient_tags=["coconut water", "juice"],
      search=["coconut water"], image_queries=["coconut water pack"],
      related=["Bisleri Soda", "Real Coconut Water"]),
]

# Home Care (need ~11) -------------------------------------------------------- #
HOME2 = [
    P("Dishwash Bar", "Vim", "Home Care", [("4 pcs", 40, 200, "g")],
      "Lemon dishwash cleaning bar.",
      subcategory="Dishwash", ingredient_tags=["dishwash", "bar"],
      search=["dishwash bar", "vim"], image_queries=["vim dishwash bar pack"],
      related=["Vim Dishwash Gel", "Dishwash Gel Lemon"]),
    P("Dishwash Liquid", "Fortune", "Home Care", [("500 ml", 90, 500, "ml")],
      "Grease-cutting dishwash liquid.",
      subcategory="Dishwash", ingredient_tags=["dishwash", "liquid"],
      search=["dishwash liquid"], image_queries=["dishwash liquid pack"],
      related=["Vim Dishwash Gel", "Dishwash Bar"]),
    P("Floor Cleaner Rose", "Lizol", "Home Care", [("975 ml", 199, 975, "ml")],
      "Rose-scented disinfectant floor cleaner.",
      subcategory="Floor Cleaner", ingredient_tags=["floor cleaner", "rose"],
      search=["floor cleaner rose"], image_queries=["lizol rose pack"],
      related=["Lizol Floor Cleaner", "Dettol Disinfectant Liquid"]),
    P("Toilet Cleaner", "Harpic", "Home Care", [("500 ml", 110, 500, "ml")],
      "Thick bleach toilet cleaner.",
      subcategory="Bathroom", ingredient_tags=["toilet cleaner", "bathroom"],
      search=["toilet cleaner", "harpic"], image_queries=["harpic toilet cleaner pack"],
      related=["Harpic Toilet Cleaner", "Bathroom Cleaner"]),
    P("Glass Cleaner", "Harpic", "Home Care", [("500 ml", 120, 500, "ml")],
      "Streak-free glass cleaner.",
      subcategory="Surface", ingredient_tags=["glass cleaner"],
      search=["glass cleaner"], image_queries=["glass cleaner pack"],
      related=["Surface Cleaner", "Floor Cleaner Rose"]),
    P("Phenyl", "Domex", "Home Care", [("1 L", 130, 1000, "ml")],
      "Black phenyl floor disinfectant.",
      subcategory="Floor Cleaner", ingredient_tags=["phenyl", "disinfectant"],
      search=["phenyl"], image_queries=["phenyl pack"],
      related=["Floor Cleaner Rose", "Lizol Floor Cleaner"]),
    P("Laundry Detergent Powder", "Tide", "Home Care", [("1 kg", 160, 1000, "g")],
      "Stain-removing detergent powder.",
      subcategory="Laundry", ingredient_tags=["detergent", "powder"],
      search=["detergent powder"], image_queries=["tide powder pack"],
      related=["Tide Detergent Powder", "Surf Excel Easy Wash"]),
    P("Laundry Detergent Liquid", "Surf", "Home Care", [("1 L", 180, 1000, "ml")],
      "Concentrated liquid detergent.",
      subcategory="Laundry", ingredient_tags=["detergent", "liquid"],
      search=["detergent liquid"], image_queries=["surf liquid pack"],
      related=["Laundry Detergent Powder", "Surf Excel Easy Wash"]),
    P("Fabric Softener", "Comfort", "Home Care", [("860 ml", 190, 860, "ml")],
      "Fragrant fabric conditioner.",
      subcategory="Laundry", ingredient_tags=["fabric softener"],
      search=["fabric softener", "comfort"], image_queries=["comfort softener pack"],
      related=["Laundry Detergent Powder", "Laundry Detergent Liquid"]),
    P("Cockroach Gel", "Raid", "Home Care", [("20 g", 90, 20, "g")],
      "Roach-killing bait gel.",
      subcategory="Pest Control", ingredient_tags=["cockroach", "pest"],
      search=["cockroach gel"], image_queries=["raid gel pack"],
      related=["Mosquito Repellent Coil", "All Out Refill"]),
    P("Garbage Bag", "Origami", "Home Care", [("90 pcs", 90, 450, "g")],
      "Large dustbin garbage bags.",
      subcategory="Waste", ingredient_tags=["garbage bag"],
      search=["garbage bag"], image_queries=["garbage bag pack"],
      related=["Floor Cleaner Rose", "Phenyl"]),
]

# Instant & Frozen (need ~1) -------------------------------------------------- #
INST2 = [
    P("Maggi Atta Noodles", "Nestle", "Instant & Frozen", [("280 g", 80, 280, "g")],
      "Whole-wheat masala atta noodles.",
      subcategory="Instant Noodles", ingredient_tags=["noodles", "atta"],
      search=["atta noodles", "maggi"], image_queries=["maggi atta noodles pack"],
      related=["Maggi 2-Minute Noodles", "Maggi Masala Ae Magic"]),
    P("Pasta Macaroni", "Knorr", "Instant & Frozen", [("250 g", 70, 250, "g")],
      "Elbow macaroni pasta.",
      subcategory="Pasta", ingredient_tags=["pasta", "macaroni"],
      search=["macaroni", "pasta"], image_queries=["knorr macaroni pack"],
      related=["Pasta Penne", "Pasta Bows"]),
    P("Frozen Mixed Veg", "McCain", "Instant & Frozen", [("400 g", 130, 400, "g")],
      "Diced frozen mixed vegetables.",
      subcategory="Frozen", ingredient_tags=["mixed veg", "frozen"],
      search=["frozen mixed veg"], image_queries=["mccain mixed veg pack"],
      related=["Frozen French Fries", "Frozen Veggie Burger"]),
    P("Instant Upma", "MTR", "Instant & Frozen", [("200 g", 60, 200, "g")],
      "Ready-to-cook rava upma mix.",
      subcategory="Ready Meal", ingredient_tags=["upma", "instant"],
      search=["instant upma"], image_queries=["mtr upma pack"],
      related=["Instant Poha", "Poha Thick"]),
    P("Instant Khichdi", "MTR", "Instant & Frozen", [("200 g", 65, 200, "g")],
      "Ready-to-cook moong khichdi.",
      subcategory="Ready Meal", ingredient_tags=["khichdi", "instant"],
      search=["instant khichdi"], image_queries=["mtr khichdi pack"],
      related=["Instant Upma", "Tata Sampann Moong Dal"]),
]

# Personal Care (need ~3) ----------------------------------------------------- #
PERS2 = [
    P("Shampoo Anti-Dandruff", "Head & Shoulders", "Personal Care", [("340 ml", 250, 340, "ml")],
      "Anti-dandruff clarifying shampoo.",
      subcategory="Hair Care", ingredient_tags=["shampoo", "dandruff"],
      search=["anti dandruff shampoo"], image_queries=["head shoulders pack"],
      related=["Dove Shampoo", "Sunsilk Shampoo"]),
    P("Face Wash", "Himalaya", "Personal Care", [("150 ml", 130, 150, "ml")],
      "Neem purifying face wash.",
      subcategory="Skin Care", ingredient_tags=["face wash", "neem"],
      search=["face wash", "himalaya"], image_queries=["himalaya face wash pack"],
      related=["Neem Face Wash", "Dettol Original Soap"]),
    P("Body Lotion", "Nivea", "Personal Care", [("400 ml", 250, 400, "ml")],
      "Nourishing body lotion.",
      subcategory="Skin Care", ingredient_tags=["body lotion"],
      search=["body lotion", "nivea"], image_queries=["nivea lotion pack"],
      related=["Dove Body Wash", "Dettol Original Soap"]),
    P("Toothpaste Herbal", "Dabur", "Personal Care", [("200 g", 90, 200, "g")],
      "Herbal clove toothpaste.",
      subcategory="Oral Care", ingredient_tags=["toothpaste", "herbal"],
      search=["herbal toothpaste"], image_queries=["dabur toothpaste pack"],
      related=["Red Toothpaste", "Colgate Strong Teeth"]),
    P("Sunscreen", "Lakme", "Personal Care", [("50 g", 299, 50, "g")],
      "SPF-50 sun protection cream.",
      subcategory="Skin Care", ingredient_tags=["sunscreen"],
      search=["sunscreen", "spf 50"], image_queries=["lakme sunscreen pack"],
      related=["Body Lotion", "Face Wash"]),
]

# Pickles, Papad & Sauces (need ~10) ------------------------------------------ #
PICK2 = [
    P("Lime Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 120, 500, "g")],
      "Spicy and tangy nimbu achar.",
      subcategory="Pickle", ingredient_tags=["lime pickle", "achar"],
      search=["lime pickle", "nimbu achar"], image_queries=["priya lime pickle pack"],
      related=["Mango Pickle", "Mixed Pickle"]),
    P("Chilli Pickle", "Mother's Recipe", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Hot and spicy mirchi achar.",
      subcategory="Pickle", ingredient_tags=["chilli pickle", "achar"],
      search=["chilli pickle"], image_queries=["mothers recipe chilli pickle pack"],
      related=["Lime Pickle", "Mango Pickle"]),
    P("Soy Sauce", "Ching's Secret", "Pickles, Papad & Sauces", [("200 ml", 80, 200, "ml")],
      "Dark soy sauce for stir-fry.",
      subcategory="Sauce", ingredient_tags=["soy sauce"],
      search=["soy sauce"], image_queries=["chings soy sauce pack"],
      related=["Red Chilli Sauce", "Green Chilli Sauce"]),
    P("Green Chutney", "MTR", "Pickles, Papad & Sauces", [("300 g", 90, 300, "g")],
      "Mint-coriander chutney.",
      subcategory="Sauce", ingredient_tags=["chutney", "mint"],
      search=["green chutney"], image_queries=["mtr green chutney pack"],
      related=["Tomato Ketchup", "Mixed Pickle"]),
    P("Tamarind Chutney", "MTR", "Pickles, Papad & Sauces", [("300 g", 90, 300, "g")],
      "Sweet-sour imli chutney.",
      subcategory="Sauce", ingredient_tags=["chutney", "tamarind"],
      search=["tamarind chutney"], image_queries=["mtr tamarind chutney pack"],
      related=["Green Chutney", "Tomato Ketchup"]),
    P("Papad Khichiya", "MTR", "Pickles, Papad & Sauces", [("200 g", 70, 200, "g")],
      "Rice khichiya papad.",
      subcategory="Papad", ingredient_tags=["papad", "khichiya"],
      search=["khichiya papad"], image_queries=["mtr khichiya papad pack"],
      related=["Moong Dal Khasta Papad", "Udad Papad"]),
    P("Punjabi Papad", "MTR", "Pickles, Papad & Sauces", [("200 g", 75, 200, "g")],
      "Masala Punjabi papad.",
      subcategory="Papad", ingredient_tags=["papad", "punjabi"],
      search=["punjabi papad"], image_queries=["mtr punjabi papad pack"],
      related=["Masala Papad", "Papad Khichiya"]),
]
