"""Curated Indian catalog — part 8: instant & frozen, pickles & papad,
personal & home care."""

from .schema import P

# Instant & Frozen ------------------------------------------------------------- #
INSTANT = [
    P("Maggi 2-Minute Noodles", "Nestle", "Instant & Frozen",
      [("70 g", 14, 70, "g"), ("140 g", 28, 140, "g")],
      "The iconic masala instant noodles.",
      subcategory="Noodles", ingredient_tags=["noodles", "maggi"],
      search=["maggi", "noodles"], image_queries=["maggi 2 minute noodles pack"],
      related=["Maggi Masala Ae Magic", "Top Ramen"]),
    P("Maggi Masala Ae Magic", "Nestle", "Instant & Frozen", [("70 g", 14, 70, "g")],
      "Single-serve masala noodles with the tastemaker.",
      subcategory="Noodles", ingredient_tags=["noodles", "maggi"],
      search=["maggi masala ae magic"], image_queries=["maggi masala ae magic pack"],
      related=["Maggi 2-Minute Noodles", "Yippee Magic Masala"]),
    P("Top Ramen Masala", "Nissin", "Instant & Frozen", [("90 g", 20, 90, "g")],
      "Masala instant noodles.",
      subcategory="Noodles", ingredient_tags=["noodles", "ramen"],
      search=["top ramen", "noodles"], image_queries=["top ramen masala pack"],
      related=["Maggi 2-Minute Noodles", "Yippee Magic Masala"]),
    P("Yippee Magic Masala", "ITC", "Instant & Frozen", [("70 g", 14, 70, "g")],
      "Long, non-sticky masala noodles.",
      subcategory="Noodles", ingredient_tags=["noodles", "yippee"],
      search=["yippee", "noodles"], image_queries=["yippee magic masala pack"],
      related=["Maggi 2-Minute Noodles", "Top Ramen Masala"]),
    P("Schezwan Chutney", "Ching's Secret", "Instant & Frozen", [("250 g", 95, 250, "g")],
      "Spicy Indo-Chinese schezwan dip.",
      subcategory="Sauce", ingredient_tags=["chutney", "schezwan"],
      search=["schezwan chutney", "ching's"], image_queries=["chings schezwan chutney pack"],
      related=["Schezwan Sauce", "Hakka Noodles"]),
    P("Schezwan Sauce", "Ching's Secret", "Instant & Frozen", [("250 g", 99, 250, "g")],
      "Schezwan stir-fry sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "schezwan"],
      search=["schezwan sauce"], image_queries=["chings schezwan sauce pack"],
      related=["Schezwan Chutney", "Green Chilli Sauce"]),
    P("Hakka Noodles", "Ching's Secret", "Instant & Frozen", [("150 g", 60, 150, "g")],
      "Chinese-style hakka noodles.",
      subcategory="Noodles", ingredient_tags=["noodles", "hakka"],
      search=["hakka noodles", "chings"], image_queries=["chings hakka noodles pack"],
      related=["Schezwan Sauce", "Maggi 2-Minute Noodles"]),
    P("Manchurian Sauce", "Ching's Secret", "Instant & Frozen", [("250 g", 99, 250, "g")],
      "Gravy base for veg manchurian.",
      subcategory="Sauce", ingredient_tags=["sauce", "manchurian"],
      search=["manchurian sauce"], image_queries=["chings manchurian sauce pack"],
      related=["Schezwan Sauce", "Soya Sauce"]),
    P("Soya Sauce", "Ching's Secret", "Instant & Frozen", [("200 ml", 80, 200, "ml")],
      "Light soya sauce for stir-fries.",
      subcategory="Sauce", ingredient_tags=["sauce", "soya"],
      search=["soya sauce"], image_queries=["chings soya sauce pack"],
      related=["Schezwan Sauce", "Vinegar"]),
    P("Vinegar", "Ching's Secret", "Instant & Frozen", [("200 ml", 60, 200, "ml")],
      "White distilled vinegar.",
      subcategory="Sauce", ingredient_tags=["vinegar"],
      search=["vinegar"], image_queries=["vinegar bottle pack"],
      related=["Soya Sauce", "Green Chilli Sauce"]),
    P("Green Chilli Sauce", "Ching's Secret", "Instant & Frozen", [("250 g", 95, 250, "g")],
      "Hot green chilli dipping sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "chilli"],
      search=["green chilli sauce"], image_queries=["green chilli sauce pack"],
      related=["Schezwan Sauce", "Red Chilli Sauce"]),
    P("Red Chilli Sauce", "Ching's Secret", "Instant & Frozen", [("250 g", 95, 250, "g")],
      "Sweet-red-chilli sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "chilli"],
      search=["red chilli sauce"], image_queries=["red chilli sauce pack"],
      related=["Green Chilli Sauce", "Schezwan Sauce"]),
    P("Tomato Ketchup", "Kissan", "Instant & Frozen",
      [("450 g", 95, 450, "g"), ("900 g", 180, 900, "g")],
      "Classic tomato ketchup.",
      subcategory="Sauce", ingredient_tags=["ketchup", "tomato"],
      search=["ketchup", "tomato ketchup"], image_queries=["kissan tomato ketchup pack"],
      related=["Tomato Sauce", "Mayonnaise"]),
    P("Tomato Sauce", "Maggi", "Instant & Frozen", [("450 g", 90, 450, "g")],
      "No-onion-no-garlic tomato sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "tomato"],
      search=["maggi tomato sauce"], image_queries=["maggi tomato sauce pack"],
      related=["Tomato Ketchup", "Pasta Sauce"]),
    P("Mayonnaise", "FunFoods", "Instant & Frozen", [("250 g", 95, 250, "g")],
      "Creamy eggless mayonnaise.",
      subcategory="Sauce", ingredient_tags=["mayonnaise"],
      search=["mayonnaise"], image_queries=["funfoods mayonnaise pack"],
      related=["Tomato Ketchup", "Cheese Spread"]),
    P("Cheese Spread", "Britannia", "Instant & Frozen", [("200 g", 90, 200, "g")],
      "Spreadable cheese in a tub.",
      subcategory="Spread", ingredient_tags=["cheese", "spread"],
      search=["cheese spread"], image_queries=["britannia cheese spread pack"],
      related=["Mayonnaise", "Amul Cheese Slices"]),
    P("Pasta Macaroni", "Bambino", "Instant & Frozen", [("500 g", 70, 500, "g")],
      "Wheat macaroni for pasta.",
      subcategory="Pasta", ingredient_tags=["pasta", "macaroni"],
      search=["pasta", "macaroni"], image_queries=["bambino macaroni pack"],
      related=["Pasta Sauce", "Maggi 2-Minute Noodles"]),
    P("Pasta Sauce", "Del Monte", "Instant & Frozen", [("400 g", 110, 400, "g")],
      "Italian tomato pasta sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "pasta"],
      search=["pasta sauce"], image_queries=["del monte pasta sauce pack"],
      related=["Tomato Sauce", "Pasta Macaroni"]),
    P("Upma Mix", "MTR", "Instant & Frozen", [("200 g", 55, 200, "g")],
      "Ready mix for south-Indian upma.",
      subcategory="Instant Mix", ingredient_tags=["upma", "instant mix"],
      search=["upma mix", "mtr"], image_queries=["mtr upma mix pack"],
      related=["Poha Mix", "Bisi Bele Bath Mix"]),
    P("Poha Mix", "MTR", "Instant & Frozen", [("200 g", 55, 200, "g")],
      "Flattened-rice mix for poha.",
      subcategory="Instant Mix", ingredient_tags=["poha", "instant mix"],
      search=["poha mix"], image_queries=["mtr poha mix pack"],
      related=["Upma Mix", "Rava Idli Mix"]),
    P("Bisi Bele Bath Mix", "MTR", "Instant & Frozen", [("200 g", 60, 200, "g")],
      "Sambar-rice mix from Karnataka.",
      subcategory="Instant Mix", ingredient_tags=["bisi bele bath", "instant mix"],
      search=["bisi bele bath mix"], image_queries=["mtr bisi bele bath mix pack"],
      related=["Upma Mix", "Puliyogare Mix"]),
    P("Puliyogare Mix", "MTR", "Instant & Frozen", [("200 g", 60, 200, "g")],
      "Tamarind rice instant mix.",
      subcategory="Instant Mix", ingredient_tags=["puliyogare", "instant mix"],
      search=["puliyogare mix"], image_queries=["mtr puliyogare mix pack"],
      related=["Bisi Bele Bath Mix", "Poha Mix"]),
    P("Rava Idli Mix", "MTR", "Instant & Frozen", [("500 g", 90, 500, "g")],
      "Semolina idli instant mix.",
      subcategory="Instant Mix", ingredient_tags=["idli", "instant mix"],
      search=["rava idli mix"], image_queries=["mtr rava idli mix pack"],
      related=["Upma Mix", "Dosa Mix"]),
    P("Dosa Mix", "MTR", "Instant & Frozen", [("500 g", 100, 500, "g")],
      "Ready dosa batter mix.",
      subcategory="Instant Mix", ingredient_tags=["dosa", "instant mix"],
      search=["dosa mix"], image_queries=["mtr dosa mix pack"],
      related=["Rava Idli Mix", "Uttapam Mix"]),
    P("Uttapam Mix", "MTR", "Instant & Frozen", [("200 g", 55, 200, "g")],
      "Vegetable uttapam mix.",
      subcategory="Instant Mix", ingredient_tags=["uttapam", "instant mix"],
      search=["uttapam mix"], image_queries=["mtr uttapam mix pack"],
      related=["Dosa Mix", "Rava Idli Mix"]),
    P("Gulab Jamun Mix", "MTR", "Instant & Frozen", [("200 g", 65, 200, "g")],
      "Instant gulab jamun mix.",
      subcategory="Instant Mix", ingredient_tags=["gulab jamun", "mix"],
      search=["gulab jamun mix"], image_queries=["mtr gulab jamun mix pack"],
      related=["Rasgulla", "Kaju Katli"]),
    P("Rava Kesari Mix", "MTR", "Instant & Frozen", [("200 g", 60, 200, "g")],
      "Semolina sweet instant mix.",
      subcategory="Instant Mix", ingredient_tags=["kesari", "mix"],
      search=["rava kesari mix"], image_queries=["mtr rava kesari mix pack"],
      related=["Gulab Jamun Mix", "Soan Papdi"]),
    P("Pongal Mix", "MTR", "Instant & Frozen", [("200 g", 60, 200, "g")],
      "Tamil ven pongal mix.",
      subcategory="Instant Mix", ingredient_tags=["pongal", "instant mix"],
      search=["pongal mix"], image_queries=["mtr pongal mix pack"],
      related=["Upma Mix", "Bisi Bele Bath Mix"]),
    P("Sambar Powder", "MTR", "Instant & Frozen", [("200 g", 90, 200, "g")],
      "South-Indian sambar spice blend.",
      subcategory="Spice Blend", ingredient_tags=["sambar", "masala"],
      search=["sambar powder", "mtr"], image_queries=["mtr sambar powder pack"],
      related=["Rasam Powder", "Garam Masala"]),
    P("Rasam Powder", "MTR", "Instant & Frozen", [("200 g", 90, 200, "g")],
      "Tangy rasam spice blend.",
      subcategory="Spice Blend", ingredient_tags=["rasam", "masala"],
      search=["rasam powder"], image_queries=["mtr rasam powder pack"],
      related=["Sambar Powder", "Garam Masala"]),
    P("Vermicelli", "MTR", "Instant & Frozen", [("200 g", 45, 200, "g")],
      "Roasted semia for sevai and payasam.",
      subcategory="Pasta", ingredient_tags=["vermicelli", "sevai"],
      search=["vermicelli", "sevai"], image_queries=["mtr vermicelli pack"],
      related=["Pasta Macaroni", "Rava Kesari Mix"]),
    P("Frozen Mixed Vegetables", "Mother Dairy", "Instant & Frozen", [("500 g", 110, 500, "g")],
      "Carrot, beans, peas and corn mix.",
      subcategory="Frozen", ingredient_tags=["frozen veg", "vegetables"],
      search=["frozen vegetables"], image_queries=["mother dairy frozen veg pack"],
      related=["Fresh Onion", "Fresh Tomato"]),
    P("Frozen Peas", "Mother Dairy", "Instant & Frozen", [("500 g", 95, 500, "g")],
      "Green peas, frozen at source.",
      subcategory="Frozen", ingredient_tags=["peas", "frozen"],
      search=["frozen peas"], image_queries=["mother dairy frozen peas pack"],
      related=["Frozen Corn", "Fresh Green Peas"]),
    P("Frozen Corn", "Mother Dairy", "Instant & Frozen", [("500 g", 100, 500, "g")],
      "Sweet corn kernels, frozen.",
      subcategory="Frozen", ingredient_tags=["corn", "frozen"],
      search=["frozen corn"], image_queries=["mother dairy frozen corn pack"],
      related=["Frozen Peas", "Frozen Mixed Vegetables"]),
    P("Frozen French Fries", "McCain", "Instant & Frozen", [("500 g", 150, 500, "g")],
      "Crispy potato fries, oven-ready.",
      subcategory="Frozen", ingredient_tags=["fries", "potato"],
      search=["french fries", "mccain"], image_queries=["mccain french fries pack"],
      related=["Frozen Corn", "Frozen Mixed Vegetables"]),
    P("Frozen Aloo Tikki", "McCain", "Instant & Frozen", [("500 g", 170, 500, "g")],
      "Potato patties, ready to fry.",
      subcategory="Frozen", ingredient_tags=["tikki", "potato"],
      search=["aloo tikki", "mccain"], image_queries=["mccain aloo tikki pack"],
      related=["Frozen French Fries", "Frozen Mixed Vegetables"]),
    P("Frozen Chicken Nuggets", "McCain", "Instant & Frozen", [("500 g", 220, 500, "g")],
      "Crispy veg/chicken-style nuggets.",
      subcategory="Frozen", veg=False, ingredient_tags=["nuggets"],
      search=["chicken nuggets", "mccain"], image_queries=["mccain nuggets pack"],
      related=["Frozen Aloo Tikki", "Frozen French Fries"]),
    P("Instant Coffee", "Nescafe", "Instant & Frozen", [("100 g", 210, 100, "g")],
      "Spray-dried instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["nescafe", "instant coffee"], image_queries=["nescafe classic jar"],
      related=["Bru Instant Coffee", "Tata Tea Gold"]),
    P("Bru Instant Coffee", "HUL", "Instant & Frozen", [("100 g", 200, 100, "g")],
      "South-Indian blend instant coffee.",
      subcategory="Coffee", ingredient_tags=["coffee", "instant coffee"],
      search=["bru", "instant coffee"], image_queries=["bru instant jar"],
      related=["Instant Coffee", "Nescafe Classic"]),
    P("Rasgulla Tin", "Mother Dairy", "Instant & Frozen", [("1 kg", 150, 1000, "g")],
      "Canned rasgulla in syrup.",
      subcategory="Sweets", ingredient_tags=["sweet", "rasgulla"],
      search=["rasgulla tin"], image_queries=["mother dairy rasgulla tin"],
      related=["Rasgulla", "Gulab Jamun"]),
    P("Kulfi Mix", "Vadilal", "Instant & Frozen", [("500 ml", 120, 500, "ml")],
      "Mango kulfi ice-cream.",
      subcategory="Frozen Dessert", veg=True, ingredient_tags=["kulfi", "ice cream"],
      search=["kulfi", "vadilal"], image_queries=["vadilal kulfi pack"],
      related=["Ice Cream Vanilla", "Gulab Jamun"]),
    P("Ice Cream Vanilla", "Amul", "Instant & Frozen", [("1 L", 220, 1000, "ml")],
      "Rich vanilla ice cream.",
      subcategory="Frozen Dessert", ingredient_tags=["ice cream", "vanilla"],
      search=["amul ice cream", "vanilla"], image_queries=["amul vanilla ice cream pack"],
      related=["Kulfi Mix", "Rasgulla"]),
    P("Custard Powder", "Weikfield", "Instant & Frozen", [("100 g", 60, 100, "g")],
      "Vanilla custard mix.",
      subcategory="Dessert Mix", ingredient_tags=["custard", "mix"],
      search=["custard powder"], image_queries=["weikfield custard powder pack"],
      related=["Rava Kesari Mix", "Kulfi Mix"]),
    P("Jelly Crystals", "Weikfield", "Instant & Frozen", [("100 g", 50, 100, "g")],
      "Fruit-flavour jelly mix.",
      subcategory="Dessert Mix", ingredient_tags=["jelly", "mix"],
      search=["jelly crystals"], image_queries=["weikfield jelly crystals pack"],
      related=["Custard Powder", "Rasna"]),
    P("Ready Meal Rajma", "MTR", "Instant & Frozen", [("300 g", 110, 300, "g")],
      "Retort-packed rajma curry, just heat.",
      subcategory="Ready Meal", ingredient_tags=["rajma", "ready meal"],
      search=["rajma ready meal", "mtr"], image_queries=["mtr rajma ready meal pack"],
      related=["Ready Meal Dal Makhani", "Tata Sampann Rajma Chitra"]),
    P("Ready Meal Dal Makhani", "MTR", "Instant & Frozen", [("300 g", 120, 300, "g")],
      "Retort-packed dal makhani.",
      subcategory="Ready Meal", ingredient_tags=["dal makhani", "ready meal"],
      search=["dal makhani ready meal"], image_queries=["mtr dal makhani ready meal pack"],
      related=["Ready Meal Rajma", "Ready Meal Paneer Butter Masala"]),
    P("Ready Meal Paneer Butter Masala", "MTR", "Instant & Frozen", [("300 g", 140, 300, "g")],
      "Retort-packed paneer butter masala.",
      subcategory="Ready Meal", ingredient_tags=["paneer", "ready meal"],
      search=["paneer butter masala ready meal"], image_queries=["mtr paneer butter masala ready meal pack"],
      related=["Ready Meal Dal Makhani", "Amul Fresh Paneer"]),
]

# Pickles, Papad & Sauces ----------------------------------------------------- #
PICKLES = [
    P("Mango Pickle", "Mother's Recipe", "Pickles, Papad & Sauces",
      [("500 g", 130, 500, "g"), ("1 kg", 250, 1000, "g")],
      "Tangy raw-mango pickle with mustard and chilli.",
      subcategory="Pickle", ingredient_tags=["pickle", "mango"],
      search=["mango pickle", "aam ka achar"], image_queries=["mango pickle jar pack"],
      related=["Lemon Pickle", "Mixed Pickle"]),
    P("Lemon Pickle", "Mother's Recipe", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Whole-lemon pickle with oil and spices.",
      subcategory="Pickle", ingredient_tags=["pickle", "lemon"],
      search=["lemon pickle", "nimbu achar"], image_queries=["lemon pickle jar pack"],
      related=["Mango Pickle", "Ginger Pickle"]),
    P("Mixed Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 120, 500, "g")],
      "Assorted veg pickle in mustard oil.",
      subcategory="Pickle", ingredient_tags=["pickle", "mixed"],
      search=["mixed pickle", "achar"], image_queries=["mixed pickle jar pack"],
      related=["Mango Pickle", "Lemon Pickle"]),
    P("Ginger Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 125, 500, "g")],
      "Shredded ginger pickle, spicy and sour.",
      subcategory="Pickle", ingredient_tags=["pickle", "ginger"],
      search=["ginger pickle", "adrak achar"], image_queries=["ginger pickle jar pack"],
      related=["Lemon Pickle", "Garlic Pickle"]),
    P("Garlic Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Whole-garlic pickle in oil.",
      subcategory="Pickle", ingredient_tags=["pickle", "garlic"],
      search=["garlic pickle", "lehsun achar"], image_queries=["garlic pickle jar pack"],
      related=["Ginger Pickle", "Mixed Pickle"]),
    P("Chilli Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Green chilli pickle.",
      subcategory="Pickle", ingredient_tags=["pickle", "chilli"],
      search=["chilli pickle"], image_queries=["chilli pickle jar pack"],
      related=["Ginger Pickle", "Mango Pickle"]),
    P("Gongura Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 150, 500, "g")],
      "Andhra sorrel-leaf pickle.",
      subcategory="Pickle", ingredient_tags=["pickle", "gongura"],
      search=["gongura pickle"], image_queries=["gongura pickle jar pack"],
      related=["Mixed Pickle", "Mango Pickle"]),
    P("Sweet Mango Chunda", "Mother's Recipe", "Pickles, Papad & Sauces", [("500 g", 140, 500, "g")],
      "Gujarati sweet mango pickle.",
      subcategory="Pickle", ingredient_tags=["pickle", "mango", "sweet"],
      search=["mango chunda"], image_queries=["mango chunda jar pack"],
      related=["Mango Pickle", "Lemon Pickle"]),
    P("Tomato Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Andhra tomato pickle.",
      subcategory="Pickle", ingredient_tags=["pickle", "tomato"],
      search=["tomato pickle"], image_queries=["tomato pickle jar pack"],
      related=["Mango Pickle", "Gongura Pickle"]),
    P("Amla Pickle", "Priya", "Pickles, Papad & Sauces", [("500 g", 130, 500, "g")],
      "Indian-gooseberry pickle, good for immunity.",
      subcategory="Pickle", ingredient_tags=["pickle", "amla"],
      search=["amla pickle"], image_queries=["amla pickle jar pack"],
      related=["Mixed Pickle", "Lemon Pickle"]),
    P("Urad Papad", "Mother's Recipe", "Pickles, Papad & Sauces", [("200 g", 60, 200, "g")],
      "Crisp urad-dal papad.",
      subcategory="Papad", ingredient_tags=["papad", "urad"],
      search=["urad papad", "papad"], image_queries=["urad papad pack"],
      related=["Moong Papad", "Masala Papad"]),
    P("Moong Papad", "Bikaji", "Pickles, Papad & Sauces", [("200 g", 60, 200, "g")],
      "Light moong-dal papad.",
      subcategory="Papad", ingredient_tags=["papad", "moong"],
      search=["moong papad"], image_queries=["moong papad pack"],
      related=["Urad Papad", "Bikaneri Papad"]),
    P("Punjabi Papad", "Bikaji", "Pickles, Papad & Sauces", [("200 g", 65, 200, "g")],
      "Spiced Punjabi papad.",
      subcategory="Papad", ingredient_tags=["papad"],
      search=["punjabi papad"], image_queries=["punjabi papad pack"],
      related=["Moong Papad", "Masala Papad"]),
    P("Masala Papad", "Haldiram's", "Pickles, Papad & Sauces", [("200 g", 65, 200, "g")],
      "Roasted masala papad.",
      subcategory="Papad", ingredient_tags=["papad", "masala"],
      search=["masala papad"], image_queries=["haldiram masala papad pack"],
      related=["Moong Papad", "Urad Papad"]),
    P("Khichiya Papad", "Bikaji", "Pickles, Papad & Sauces", [("200 g", 60, 200, "g")],
      "Rice khichiya papad, Gujarati favourite.",
      subcategory="Papad", ingredient_tags=["papad", "khichiya"],
      search=["khichiya papad"], image_queries=["khichiya papad pack"],
      related=["Moong Papad", "Punjabi Papad"]),
    P("Masala Khakra", "Haldiram's", "Pickles, Papad & Sauces", [("200 g", 70, 200, "g")],
      "Gujarati masala khakra crisps.",
      subcategory="Papad", ingredient_tags=["khakra", "crisps"],
      search=["khakra", "masala khakra"], image_queries=["haldiram masala khakra pack"],
      related=["Masala Papad", "Mathri"]),
    P("Tomato Sauce", "Kissan", "Pickles, Papad & Sauces", [("900 g", 180, 900, "g")],
      "Family pack tomato sauce.",
      subcategory="Sauce", ingredient_tags=["ketchup", "tomato"],
      search=["tomato sauce", "ketchup"], image_queries=["kissan tomato sauce pack"],
      related=["Tomato Ketchup", "Mayonnaise"]),
    P("Chilli Garlic Sauce", "Veeba", "Pickles, Papad & Sauces", [("250 g", 99, 250, "g")],
      "Chilli-garlic dipping sauce.",
      subcategory="Sauce", ingredient_tags=["sauce", "chilli"],
      search=["chilli garlic sauce", "veeba"], image_queries=["veeba chilli garlic sauce pack"],
      related=["Green Chilli Sauce", "Schezwan Sauce"]),
    P("Peri Peri Masala", "Veeba", "Pickles, Papad & Sauces", [("100 g", 99, 100, "g")],
      "Portuguese-style spice sprinkle.",
      subcategory="Sauce", ingredient_tags=["peri peri", "masala"],
      search=["peri peri", "veeba"], image_queries=["veeba peri peri pack"],
      related=["Chilli Garlic Sauce", "Tandoori Mayo"]),
    P("Tandoori Mayo", "Veeba", "Pickles, Papad & Sauces", [("250 g", 120, 250, "g")],
      "Tandoori mayonnaise.",
      subcategory="Sauce", ingredient_tags=["mayonnaise", "tandoori"],
      search=["tandoori mayo", "veeba"], image_queries=["veeba tandoori mayo pack"],
      related=["Mayonnaise", "Peri Peri Masala"]),
    P("Hakka Noodles Family", "Ching's Secret", "Pickles, Papad & Sauces", [("340 g", 110, 340, "g")],
      "Family pack hakka noodles.",
      subcategory="Noodles", ingredient_tags=["noodles", "hakka"],
      search=["hakka noodles"], image_queries=["chings hakka noodles family pack"],
      related=["Hakka Noodles", "Schezwan Sauce"]),
    P("Sandwich Spread", "Veeba", "Pickles, Papad & Sauces", [("250 g", 110, 250, "g")],
      "Eggless sandwich mayo with veggies.",
      subcategory="Spread", ingredient_tags=["mayonnaise", "spread"],
      search=["sandwich spread"], image_queries=["veeba sandwich spread pack"],
      related=["Mayonnaise", "Cheese Spread"]),
    P("Mango Thokku", "Priya", "Pickles, Papad & Sauces", [("500 g", 140, 500, "g")],
      "Tamil grated-mango pickle.",
      subcategory="Pickle", ingredient_tags=["pickle", "mango"],
      search=["mango thokku"], image_queries=["mango thokku jar pack"],
      related=["Mango Pickle", "Tomato Pickle"]),
    P("Garlic Mayo", "Veeba", "Pickles, Papad & Sauces", [("250 g", 120, 250, "g")],
      "Garlic mayonnaise dip.",
      subcategory="Sauce", ingredient_tags=["mayonnaise", "garlic"],
      search=["garlic mayo"], image_queries=["veeba garlic mayo pack"],
      related=["Tandoori Mayo", "Sandwich Spread"]),
    P("Dry Mango Powder", "Everest", "Pickles, Papad & Sauces", [("100 g", 48, 100, "g")],
      "Amchur for tang in curries and chutneys.",
      subcategory="Spice", ingredient_tags=["amchur", "masala"],
      search=["amchur", "dry mango powder"], image_queries=["everest amchur pack"],
      related=["Chaat Masala", "Mango Pickle"]),
    P("Imli Chutney", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 70, 200, "g")],
      "Tamarind-date chutney.",
      subcategory="Chutney", ingredient_tags=["imli", "chutney"],
      search=["tamarind chutney", "imli"], image_queries=["tamarind chutney pack"],
      related=["Mint Chutney", "Green Chutney"]),
    P("Mint Chutney", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 70, 200, "g")],
      "Mint-coriander chutney.",
      subcategory="Chutney", ingredient_tags=["mint", "chutney"],
      search=["mint chutney", "pudina"], image_queries=["mint chutney pack"],
      related=["Imli Chutney", "Green Chutney"]),
    P("Green Chutney", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 70, 200, "g")],
      "Coriander-mint chutney.",
      subcategory="Chutney", ingredient_tags=["chutney", "green"],
      search=["green chutney"], image_queries=["green chutney pack"],
      related=["Mint Chutney", "Imli Chutney"]),
    P("Ready Salsa", "Veeba", "Pickles, Papad & Sauces", [("250 g", 110, 250, "g")],
      "Mexican-style tomato salsa.",
      subcategory="Sauce", ingredient_tags=["salsa", "sauce"],
      search=["salsa"], image_queries=["veeba salsa pack"],
      related=["Tomato Ketchup", "Cheese Spread"]),
    P("Coconut Chutney", "MTR", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "South-Indian coconut chutney mix.",
      subcategory="Chutney", ingredient_tags=["coconut", "chutney"],
      search=["coconut chutney"], image_queries=["mtr coconut chutney pack"],
      related=["Mint Chutney", "Imli Chutney"]),
    P("Tomato Chutney", "MTR", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "Spicy tomato chutney.",
      subcategory="Chutney", ingredient_tags=["tomato", "chutney"],
      search=["tomato chutney"], image_queries=["mtr tomato chutney pack"],
      related=["Coconut Chutney", "Imli Chutney"]),
    P("Peanut Chutney", "MTR", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "Roasted-peanut chutney.",
      subcategory="Chutney", ingredient_tags=["peanut", "chutney"],
      search=["peanut chutney"], image_queries=["mtr peanut chutney pack"],
      related=["Coconut Chutney", "Green Chutney"]),
    P("Pudina Chutney", "MTR", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "Mint-coriander chutney mix.",
      subcategory="Chutney", ingredient_tags=["mint", "chutney"],
      search=["pudina chutney"], image_queries=["mtr pudina chutney pack"],
      related=["Mint Chutney", "Imli Chutney"]),
    P("Sweet Chutney", "MTR", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "Date-tamarind sweet chutney.",
      subcategory="Chutney", ingredient_tags=["chutney", "sweet"],
      search=["sweet chutney", "meethi chutney"], image_queries=["mtr sweet chutney pack"],
      related=["Imli Chutney", "Mango Thokku"]),
    P("Garlic Paste", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 75, 200, "g")],
      "Ready garlic paste for cooking.",
      subcategory="Paste", ingredient_tags=["garlic", "paste"],
      search=["garlic paste"], image_queries=["garlic paste pack"],
      related=["Ginger Paste", "Ginger Garlic Paste"]),
    P("Ginger Paste", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 75, 200, "g")],
      "Ready ginger paste for cooking.",
      subcategory="Paste", ingredient_tags=["ginger", "paste"],
      search=["ginger paste"], image_queries=["ginger paste pack"],
      related=["Garlic Paste", "Ginger Garlic Paste"]),
    P("Ginger Garlic Paste", "Tata Sampann", "Pickles, Papad & Sauces", [("200 g", 80, 200, "g")],
      "Ready ginger-garlic paste.",
      subcategory="Paste", ingredient_tags=["ginger", "garlic", "paste"],
      search=["ginger garlic paste"], image_queries=["ginger garlic paste pack"],
      related=["Garlic Paste", "Ginger Paste"]),
    P("Boondi", "Haldiram's", "Pickles, Papad & Sauces", [("200 g", 45, 200, "g")],
      "Tiny fried gram-flour pearls for raita.",
      subcategory="Namkeen", ingredient_tags=["boondi", "namkeen"],
      search=["boondi"], image_queries=["haldiram boondi pack"],
      related=["Raita Mix", "Moong Dal"]),
    P("Raita Mix", "Tata Sampann", "Pickles, Papad & Sauces", [("100 g", 60, 100, "g")],
      "Spiced mix to stir into curd for raita.",
      subcategory="Spice Blend", ingredient_tags=["raita", "masala"],
      search=["raita mix"], image_queries=["raita mix pack"],
      related=["Boondi", "Curd"]),
]

# Personal & Home Care -------------------------------------------------------- #
PERSONAL = [
    P("Lifebuoy Total 10 Soap", "HUL", "Personal Care",
      [("125 g", 28, 125, "g"), ("4x125 g", 110, 500, "g")],
      "Antiseptic germ-protection soap.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["lifebuoy", "soap"], image_queries=["lifebuoy soap pack"],
      related=["Savlon Soap", "Dove Cream Bar"]),
    P("Dettol Original Soap", "Reckitt", "Personal Care",
      [("125 g", 30, 125, "g"), ("4x125 g", 115, 500, "g")],
      "Dettol-clean antiseptic soap.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["dettol soap"], image_queries=["dettol soap pack"],
      related=["Lifebuoy Total 10 Soap", "Savlon Soap"]),
    P("Dove Cream Bar", "HUL", "Personal Care", [("100 g", 45, 100, "g")],
      "Cream moisturising beauty bar.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["dove", "soap"], image_queries=["dove cream bar pack"],
      related=["Pears Pure Soap", "Lifebuoy Total 10 Soap"]),
    P("Pears Pure Soap", "HUL", "Personal Care", [("100 g", 40, 100, "g")],
      "Transparent glycerin soap.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["pears soap"], image_queries=["pears soap pack"],
      related=["Dove Cream Bar", "Savlon Soap"]),
    P("Savlon Soap", "ITC", "Personal Care", [("125 g", 30, 125, "g")],
      "Antimicrobial protection soap.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["savlon soap"], image_queries=["savlon soap pack"],
      related=["Lifebuoy Total 10 Soap", "Savlon Handwash"]),
    P("Lux Beauty Soap", "HUL", "Personal Care", [("100 g", 35, 100, "g")],
      "Floral fragrance beauty soap.",
      subcategory="Soap", ingredient_tags=["soap", "bath"],
      search=["lux soap"], image_queries=["lux soap pack"],
      related=["Dove Cream Bar", "Pears Pure Soap"]),
    P("Head & Shoulders Anti-Dandruff", "P&G", "Personal Care", [("340 ml", 230, 340, "ml")],
      "Anti-dandruff shampoo.",
      subcategory="Shampoo", ingredient_tags=["shampoo", "hair"],
      search=["head and shoulders", "shampoo"], image_queries=["head and shoulders shampoo pack"],
      related=["Clinic Plus", "Dove Shampoo"]),
    P("Clinic Plus Strong", "HUL", "Personal Care", [("340 ml", 160, 340, "ml")],
      "Strength-and-shine shampoo.",
      subcategory="Shampoo", ingredient_tags=["shampoo", "hair"],
      search=["clinic plus", "shampoo"], image_queries=["clinic plus shampoo pack"],
      related=["Head & Shoulders Anti-Dandruff", "Sunsilk"]),
    P("Sunsilk Black Shine", "HUL", "Personal Care", [("340 ml", 170, 340, "ml")],
      "Shine shampoo for black hair.",
      subcategory="Shampoo", ingredient_tags=["shampoo", "hair"],
      search=["sunsilk", "shampoo"], image_queries=["sunsilk shampoo pack"],
      related=["Clinic Plus Strong", "Dove Shampoo"]),
    P("Dove Shampoo", "HUL", "Personal Care", [("340 ml", 250, 340, "ml")],
      "Nutritive repair shampoo.",
      subcategory="Shampoo", ingredient_tags=["shampoo", "hair"],
      search=["dove shampoo"], image_queries=["dove shampoo pack"],
      related=["Dove Cream Bar", "Head & Shoulders Anti-Dandruff"]),
    P("Pantene Pro-V", "P&G", "Personal Care", [("340 ml", 260, 340, "ml")],
      "Pro-vitamin moisture shampoo.",
      subcategory="Shampoo", ingredient_tags=["shampoo", "hair"],
      search=["pantene", "shampoo"], image_queries=["pantene shampoo pack"],
      related=["Dove Shampoo", "Clinic Plus Strong"]),
    P("Chyawanprash", "Dabur", "Personal Care", [("500 g", 200, 500, "g")],
      "Ayurvedic immunity jam.",
      subcategory="Ayurveda", veg=True, ingredient_tags=["ayurveda", "immunity"],
      search=["chyawanprash", "dabur"], image_queries=["dabur chyawanprash jar"],
      related=["Giloy Juice", "Amla Juice"]),
    P("Giloy Juice", "Patanjali", "Personal Care", [("500 ml", 150, 500, "ml")],
      "Immunity-boosting giloy juice.",
      subcategory="Ayurveda", veg=True, ingredient_tags=["ayurveda", "juice"],
      search=["giloy juice", "patanjali"], image_queries=["patanjali giloy juice pack"],
      related=["Amla Juice", "Chyawanprash"]),
    P("Amla Juice", "Patanjali", "Personal Care", [("500 ml", 140, 500, "ml")],
      "Raw amla juice for immunity.",
      subcategory="Ayurveda", veg=True, ingredient_tags=["ayurveda", "amla"],
      search=["amla juice"], image_queries=["patanjali amla juice pack"],
      related=["Giloy Juice", "Chyawanprash"]),
    P("Aloe Vera Gel", "Patanjali", "Personal Care", [("150 ml", 90, 150, "ml")],
      "Multipurpose aloe gel for skin and hair.",
      subcategory="Skin", veg=True, ingredient_tags=["aloe", "gel"],
      search=["aloe vera gel", "patanjali"], image_queries=["patanjali aloe vera gel pack"],
      related=["Rose Water", "Multani Mitti"]),
    P("Rose Water", "Dabur", "Personal Care", [("200 ml", 80, 200, "ml")],
      "Pure rose water toner.",
      subcategory="Skin", veg=True, ingredient_tags=["rose water", "toner"],
      search=["rose water", "dabur gulabari"], image_queries=["dabur rose water pack"],
      related=["Aloe Vera Gel", "Cucumber Face Wash"]),
    P("Cucumber Face Wash", "Himalaya", "Personal Care", [("100 ml", 90, 100, "ml")],
      "Cucumber and aloe face wash.",
      subcategory="Skin", veg=True, ingredient_tags=["face wash", "skin"],
      search=["face wash", "himalaya"], image_queries=["himalaya face wash pack"],
      related=["Rose Water", "Moisturising Lotion"]),
    P("Moisturising Lotion", "Nivea", "Personal Care", [("200 ml", 160, 200, "ml")],
      "48h moisturising body lotion.",
      subcategory="Skin", ingredient_tags=["lotion", "skin"],
      search=["nivea lotion", "body lotion"], image_queries=["nivea lotion pack"],
      related=["Cucumber Face Wash", "Sunscreen SPF 50"]),
    P("Sunscreen SPF 50", "Lakme", "Personal Care", [("50 g", 300, 50, "g")],
      "Broad-spectrum SPF 50 sunscreen.",
      subcategory="Skin", ingredient_tags=["sunscreen", "skin"],
      search=["sunscreen", "spf 50"], image_queries=["lakme sunscreen pack"],
      related=["Moisturising Lotion", "Rose Water"]),
    P("Fairness Cream", "Fair & Lovely", "Personal Care", [("50 g", 90, 50, "g")],
      "Brightening face cream.",
      subcategory="Skin", ingredient_tags=["cream", "face"],
      search=["fairness cream", "fair and lovely"], image_queries=["fair and lovely cream pack"],
      related=["Moisturising Lotion", "Cucumber Face Wash"]),
    P("Colgate Strong Teeth", "Colgate", "Personal Care", [("200 g", 95, 200, "g")],
      "Calcium-clean toothpaste.",
      subcategory="Oral", ingredient_tags=["toothpaste", "oral"],
      search=["colgate", "toothpaste"], image_queries=["colgate toothpaste pack"],
      related=["Pepsodent", "Dant Kanti"]),
    P("Pepsodent Germicheck", "HUL", "Personal Care", [("200 g", 90, 200, "g")],
      "Cloves-and-germicheck toothpaste.",
      subcategory="Oral", ingredient_tags=["toothpaste", "oral"],
      search=["pepsodent", "toothpaste"], image_queries=["pepsodent toothpaste pack"],
      related=["Colgate Strong Teeth", "Dant Kanti"]),
    P("Dant Kanti", "Patanjali", "Personal Care", [("200 g", 95, 200, "g")],
      "Ayurvedic clove toothpaste.",
      subcategory="Oral", veg=True, ingredient_tags=["toothpaste", "ayurveda"],
      search=["dant kanti", "patanjali"], image_queries=["patanjali dant kanti pack"],
      related=["Colgate Strong Teeth", "Pepsodent Germicheck"]),
    P("Toothbrush Medium", "Colgate", "Personal Care", [("3 pcs", 75, 30, "g")],
      "Medium-bristle toothbrush, pack of 3.",
      subcategory="Oral", ingredient_tags=["toothbrush", "oral"],
      search=["toothbrush"], image_queries=["colgate toothbrush pack"],
      related=["Colgate Strong Teeth", "Pepsodent Germicheck"]),
    P("Dettol Handwash", "Reckitt", "Personal Care", [("200 ml", 99, 200, "ml")],
      "Antibacterial liquid handwash.",
      subcategory="Handwash", ingredient_tags=["handwash", "hand"],
      search=["dettol handwash"], image_queries=["dettol handwash pack"],
      related=["Savlon Handwash", "Lifebuoy Total 10 Soap"]),
    P("Savlon Handwash", "ITC", "Personal Care", [("200 ml", 99, 200, "ml")],
      "Gentle antibacterial handwash.",
      subcategory="Handwash", ingredient_tags=["handwash", "hand"],
      search=["savlon handwash"], image_queries=["savlon handwash pack"],
      related=["Dettol Handwash", "Savlon Soap"]),
    P("Sanitary Pads", "Whisper", "Personal Care", [("20 pads", 120, 80, "g")],
      "Ultra-thin with wings, 20 pads.",
      subcategory="Feminine", ingredient_tags=["pads", "hygiene"],
      search=["whisper", "sanitary pads"], image_queries=["whisper pads pack"],
      related=["Stayfree", "Dettol Handwash"]),
    P("Stayfree Secure", "J&J", "Personal Care", [("18 pads", 110, 72, "g")],
      "Dry-max sanitary napkins.",
      subcategory="Feminine", ingredient_tags=["sanitary", "pads"],
      search=["stayfree", "sanitary pads"], image_queries=["stayfree pads pack"],
      related=["Sanitary Pads", "Whisper"]),
    P("Hair Oil Almond", "Dabur", "Personal Care", [("200 ml", 130, 200, "ml")],
      "Almond hair oil for strong hair.",
      subcategory="Hair Oil", ingredient_tags=["hair oil", "almond"],
      search=["almond hair oil", "dabur"], image_queries=["dabur almond oil pack"],
      related=["Coconut Hair Oil", "Amla Hair Oil"]),
    P("Coconut Hair Oil", "Parachute", "Personal Care", [("200 ml", 110, 200, "ml")],
      "100% pure coconut hair oil.",
      subcategory="Hair Oil", ingredient_tags=["hair oil", "coconut"],
      search=["parachute coconut oil", "hair oil"], image_queries=["parachute coconut oil pack"],
      related=["Hair Oil Almond", "Amla Hair Oil"]),
    P("Amla Hair Oil", "Dabur", "Personal Care", [("200 ml", 120, 200, "ml")],
      "Amla-enriched hair oil.",
      subcategory="Hair Oil", ingredient_tags=["hair oil", "amla"],
      search=["amla hair oil"], image_queries=["dabur amla oil pack"],
      related=["Coconut Hair Oil", "Hair Oil Almond"]),
    P("Body Spray", "Fogg", "Personal Care", [("120 ml", 200, 120, "ml")],
      "Long-lasting deodorant body spray.",
      subcategory="Deo", ingredient_tags=["deo", "fragrance"],
      search=["fogg", "deo", "body spray"], image_queries=["fogg body spray pack"],
      related=["Deodorant Roll-On", "Moisturising Lotion"]),
    P("Deodorant Roll-On", "Nivea", "Personal Care", [("50 ml", 180, 50, "ml")],
      "Fresh roll-on deodorant.",
      subcategory="Deo", ingredient_tags=["deo", "roll on"],
      search=["deodorant roll on", "nivea"], image_queries=["nivea roll on pack"],
      related=["Body Spray", "Moisturising Lotion"]),
    P("Shaving Cream", "Gillette", "Personal Care", [("70 g", 90, 70, "g")],
      "Rich lather shaving cream.",
      subcategory="Shaving", ingredient_tags=["shaving", "cream"],
      search=["shaving cream", "gillette"], image_queries=["gillette shaving cream pack"],
      related=["Razor Blades", "After Shave"]),
    P("Razor Blades", "Gillette", "Personal Care", [("5 pcs", 110, 20, "g")],
      "5-blade razor cartridge pack.",
      subcategory="Shaving", ingredient_tags=["razor", "blades"],
      search=["razor blades", "gillette"], image_queries=["gillette blades pack"],
      related=["Shaving Cream", "After Shave"]),
    P("After Shave", "Old Spice", "Personal Care", [("50 ml", 150, 50, "ml")],
      "Soothing aftershave lotion.",
      subcategory="Shaving", ingredient_tags=["after shave"],
      search=["after shave", "old spice"], image_queries=["old spice after shave pack"],
      related=["Shaving Cream", "Razor Blades"]),
    P("Baby Soap", "Johnson's", "Personal Care", [("100 g", 50, 100, "g")],
      "Mild baby soap, no tears.",
      subcategory="Baby", ingredient_tags=["baby", "soap"],
      search=["baby soap", "johnsons"], image_queries=["johnsons baby soap pack"],
      related=["Baby Shampoo", "Baby Lotion"]),
    P("Baby Shampoo", "Johnson's", "Personal Care", [("200 ml", 140, 200, "ml")],
      "No-more-tears baby shampoo.",
      subcategory="Baby", ingredient_tags=["baby", "shampoo"],
      search=["baby shampoo"], image_queries=["johnsons baby shampoo pack"],
      related=["Baby Soap", "Baby Lotion"]),
    P("Baby Lotion", "Johnson's", "Personal Care", [("200 ml", 150, 200, "ml")],
      "24h moisture baby lotion.",
      subcategory="Baby", ingredient_tags=["baby", "lotion"],
      search=["baby lotion"], image_queries=["johnsons baby lotion pack"],
      related=["Baby Soap", "Baby Shampoo"]),
    P("Baby Powder", "Johnson's", "Personal Care", [("200 g", 130, 200, "g")],
      "Talc-free baby powder.",
      subcategory="Baby", ingredient_tags=["baby", "powder"],
      search=["baby powder"], image_queries=["johnsons baby powder pack"],
      related=["Baby Lotion", "Baby Soap"]),
    P("Wet Wipes", "Mamaearth", "Personal Care", [("72 pcs", 120, 200, "g")],
      "Aloe-based baby wet wipes.",
      subcategory="Baby", veg=True, ingredient_tags=["wipes", "baby"],
      search=["baby wipes", "mamaearth"], image_queries=["mamaearth wipes pack"],
      related=["Baby Soap", "Baby Lotion"]),
    P("Multani Mitti", "Banjara's", "Personal Care", [("200 g", 90, 200, "g")],
      "Fuller's earth face pack.",
      subcategory="Skin", veg=True, ingredient_tags=["multani mitti", "face pack"],
      search=["multani mitti"], image_queries=["multani mitti pack"],
      related=["Aloe Vera Gel", "Rose Water"]),
    P("Hair Conditioner", "Dove", "Personal Care", [("175 ml", 200, 175, "ml")],
      "Damage-repair conditioner.",
      subcategory="Hair", ingredient_tags=["conditioner", "hair"],
      search=["hair conditioner", "dove"], image_queries=["dove conditioner pack"],
      related=["Dove Shampoo", "Coconut Hair Oil"]),
    P("Beard Oil", "Man Matters", "Personal Care", [("30 ml", 250, 30, "ml")],
      "Growth-promoting beard oil.",
      subcategory="Hair", ingredient_tags=["beard oil", "hair"],
      search=["beard oil"], image_queries=["beard oil pack"],
      related=["Hair Oil Almond", "Coconut Hair Oil"]),
    P("Lip Balm", "Nivea", "Personal Care", [("4.8 g", 99, 4.8, "g")],
      "Fruity moisturising lip balm.",
      subcategory="Skin", ingredient_tags=["lip balm", "lips"],
      search=["lip balm", "nivea"], image_queries=["nivea lip balm pack"],
      related=["Moisturising Lotion", "Sunscreen SPF 50"]),
]

# Home Care ------------------------------------------------------------------- #
HOME = [
    P("Surf Excel Easy Wash", "HUL", "Home Care",
      [("1 kg", 150, 1000, "g"), ("2 kg", 290, 2000, "g")],
      "Liquid detergent for hand wash.",
      subcategory="Detergent", ingredient_tags=["detergent", "wash"],
      search=["surf excel", "detergent"], image_queries=["surf excel easy wash pack"],
      related=["Tide Plus", "Ariel"]),
    P("Tide Plus Detergent", "P&G", "Home Care", [("1 kg", 160, 1000, "g")],
      "Antibacterial detergent powder.",
      subcategory="Detergent", ingredient_tags=["detergent", "wash"],
      search=["tide", "detergent"], image_queries=["tide detergent pack"],
      related=["Surf Excel Easy Wash", "Ariel"]),
    P("Ariel Matic Top", "P&G", "Home Care", [("1 kg", 180, 1000, "g")],
      "Front/top-load machine detergent.",
      subcategory="Detergent", ingredient_tags=["detergent", "machine"],
      search=["ariel", "detergent"], image_queries=["ariel matic pack"],
      related=["Tide Plus Detergent", "Surf Excel Easy Wash"]),
    P("Vim Dishwash Bar", "HUL", "Home Care", [("5 pcs", 60, 250, "g")],
      "Lemon dishwash bar for utensils.",
      subcategory="Dishwash", ingredient_tags=["dishwash", "utensils"],
      search=["vim", "dishwash"], image_queries=["vim bar pack"],
      related=["Vim Gel", "Dettol Handwash"]),
    P("Vim Gel", "HUL", "Home Care", [("250 ml", 80, 250, "ml")],
      "Lemon dishwash gel for utensils.",
      subcategory="Dishwash", ingredient_tags=["dishwash", "utensils"],
      search=["vim gel", "dishwash gel"], image_queries=["vim gel pack"],
      related=["Vim Dishwash Bar", "Pril Dishwash Liquid"]),
    P("Pril Dishwash Liquid", "Reckitt", "Home Care", [("250 ml", 85, 250, "ml")],
      "Concentrated lime dishwash liquid.",
      subcategory="Dishwash", ingredient_tags=["dishwash", "utensils"],
      search=["pril", "dishwash liquid"], image_queries=["pril liquid pack"],
      related=["Vim Gel", "Vim Dishwash Bar"]),
    P("Harpic Toilet Cleaner", "Reckitt", "Home Care", [("500 ml", 110, 500, "ml")],
      "Thick bleach toilet cleaner.",
      subcategory="Cleaner", ingredient_tags=["toilet", "cleaner"],
      search=["harpic", "toilet cleaner"], image_queries=["harpic toilet cleaner pack"],
      related=["Lizol Disinfectant", "Dettol Handwash"]),
    P("Lizol Disinfectant", "Reckitt", "Home Care", [("500 ml", 150, 500, "ml")],
      "Floor and surface disinfectant.",
      subcategory="Cleaner", ingredient_tags=["disinfectant", "floor"],
      search=["lizol", "disinfectant"], image_queries=["lizol pack"],
      related=["Harpic Toilet Cleaner", "Dettol Handwash"]),
    P("Glass Cleaner", "Colin", "Home Care", [("500 ml", 120, 500, "ml")],
      "Streak-free glass cleaner.",
      subcategory="Cleaner", ingredient_tags=["glass", "cleaner"],
      search=["colin", "glass cleaner"], image_queries=["colin glass cleaner pack"],
      related=["Lizol Disinfectant", "Vim Gel"]),
    P("Floor Cleaner", "Harpic", "Home Care", [("500 ml", 110, 500, "ml")],
      "Pine-scented floor cleaner.",
      subcategory="Cleaner", ingredient_tags=["floor", "cleaner"],
      search=["floor cleaner", "harpic"], image_queries=["harpic floor cleaner pack"],
      related=["Lizol Disinfectant", "Colin Glass Cleaner"]),
    P("Detergent Cake", "Wheel", "Home Care", [("6 pcs", 50, 300, "g")],
      "Economy washing soap cake.",
      subcategory="Detergent", ingredient_tags=["detergent", "cake"],
      search=["wheel", "detergent cake"], image_queries=["wheel detergent cake pack"],
      related=["Surf Excel Easy Wash", "Tide Plus Detergent"]),
    P("Laundry Liquid", "Ezee", "Home Care", [("500 ml", 130, 500, "ml")],
      "Gentle liquid for woolens.",
      subcategory="Detergent", ingredient_tags=["detergent", "liquid"],
      search=["ezee", "laundry liquid"], image_queries=["ezee liquid pack"],
      related=["Surf Excel Easy Wash", "Ariel Matic Top"]),
    P("Fabric Conditioner", "Comfort", "Home Care", [("500 ml", 130, 500, "ml")],
      "Softener for clothes.",
      subcategory="Detergent", ingredient_tags=["fabric", "conditioner"],
      search=["comfort", "fabric conditioner"], image_queries=["comfort fabric conditioner pack"],
      related=["Surf Excel Easy Wash", "Ariel Matic Top"]),
    P("Dishwash Scrub", "Scotch-Brite", "Home Care", [("3 pcs", 60, 30, "g")],
      "Steel-wool scrub pads.",
      subcategory="Dishwash", ingredient_tags=["scrub", "utensils"],
      search=["scotch brite", "scrub"], image_queries=["scotch brite scrub pack"],
      related=["Vim Dishwash Bar", "Vim Gel"]),
    P("Air Freshener", "Godrej", "Home Care", [("300 ml", 150, 300, "ml")],
      "Room spray air freshener.",
      subcategory="Freshener", ingredient_tags=["air freshener", "room"],
      search=["air freshener", "godrej"], image_queries=["godrej aer pack"],
      related=["Floor Cleaner", "Lizol Disinfectant"]),
    P("Garbage Bags", "Origami", "Home Care", [("120 pcs", 90, 400, "g")],
      "Medium dustbin bags, pack of 120.",
      subcategory="Bags", ingredient_tags=["garbage bags"],
      search=["garbage bags", "dustbin bags"], image_queries=["garbage bags pack"],
      related=["Floor Cleaner", "Air Freshener"]),
    P("Mosaic Cleaner", "Harpic", "Home Care", [("500 ml", 120, 500, "ml")],
      "Bathroom and tile cleaner.",
      subcategory="Cleaner", ingredient_tags=["bathroom", "cleaner"],
      search=["mosaic cleaner", "harpic"], image_queries=["harpic mosaic pack"],
      related=["Harpic Toilet Cleaner", "Lizol Disinfectant"]),
    P("Hand Sanitizer", "Dettol", "Home Care", [("200 ml", 80, 200, "ml")],
      "70% alcoholgel sanitizer.",
      subcategory="Sanitizer", ingredient_tags=["sanitizer", "hand"],
      search=["hand sanitizer", "dettol"], image_queries=["dettol sanitizer pack"],
      related=["Dettol Handwash", "Lizol Disinfectant"]),
    P("Dishwash Brush", "Scotch-Brite", "Home Care", [("1 pc", 70, 50, "g")],
      "Long-handle dish brush.",
      subcategory="Dishwash", ingredient_tags=["brush", "utensils"],
      search=["dish brush", "scotch brite"], image_queries=["scotch brite brush pack"],
      related=["Dishwash Scrub", "Vim Gel"]),
    P("Toilet Brush", "Gala", "Home Care", [("1 pc", 90, 60, "g")],
      "Bowl toilet brush with holder.",
      subcategory="Cleaner", ingredient_tags=["toilet", "brush"],
      search=["toilet brush"], image_queries=["toilet brush pack"],
      related=["Harpic Toilet Cleaner", "Mosaic Cleaner"]),
    P("Phenyl", "Margo", "Home Care", [("750 ml", 120, 750, "ml")],
      "Black phenyl floor disinfectant.",
      subcategory="Cleaner", ingredient_tags=["phenyl", "floor"],
      search=["phenyl", "floor cleaner"], image_queries=["phenyl pack"],
      related=["Lizol Disinfectant", "Floor Cleaner"]),
    P("Washing Machine Cleaner", "Affresh", "Home Care", [("6 pcs", 250, 120, "g")],
      "Descaler tablets for washers.",
      subcategory="Cleaner", ingredient_tags=["washing machine", "cleaner"],
      search=["washing machine cleaner"], image_queries=["washing machine cleaner pack"],
      related=["Ariel Matic Top", "Fabric Conditioner"]),
    P("Cockroach Repellent", "Hit", "Home Care", [("200 ml", 90, 200, "ml")],
      "Insect spray repellent.",
      subcategory="Repellent", ingredient_tags=["repellent", "insect"],
      search=["hit spray", "cockroach"], image_queries=["hit spray pack"],
      related=["Air Freshener", "Floor Cleaner"]),
    P("Mosquito Coil", "Goodknight", "Home Care", [("10 pcs", 70, 200, "g")],
      "Repellent mosquito coils.",
      subcategory="Repellent", ingredient_tags=["mosquito", "coil"],
      search=["goodknight", "mosquito coil"], image_queries=["goodknight coil pack"],
      related=["Cockroach Repellent", "Air Freshener"]),
    P("All-Out Refill", "Godrej", "Home Care", [("4 pcs", 110, 40, "g")],
      "Liquid vapouriser refill.",
      subcategory="Repellent", ingredient_tags=["mosquito", "refill"],
      search=["all out", "mosquito"], image_queries=["all out refill pack"],
      related=["Mosquito Coil", "Cockroach Repellent"]),
    P("Room Freshener Spray", "Odonil", "Home Care", [("300 ml", 130, 300, "ml")],
      "Bathroom air freshener spray.",
      subcategory="Freshener", ingredient_tags=["air freshener", "room"],
      search=["odonil", "air freshener"], image_queries=["odonil spray pack"],
      related=["Air Freshener", "Floor Cleaner"]),
    P("Bleach", "Harpic", "Home Care", [("500 ml", 95, 500, "ml")],
      "Laundry and surface bleach.",
      subcategory="Cleaner", ingredient_tags=["bleach", "cleaner"],
      search=["bleach"], image_queries=["bleach pack"],
      related=["Lizol Disinfectant", "Surf Excel Easy Wash"]),
    P("Stain Remover", "Harpic", "Home Care", [("250 ml", 90, 250, "ml")],
      "Pre-wash stain remover.",
      subcategory="Detergent", ingredient_tags=["stain", "remover"],
      search=["stain remover"], image_queries=["stain remover pack"],
      related=["Surf Excel Easy Wash", "Ariel Matic Top"]),
    P("Sponge Wipe", "Scotch-Brite", "Home Care", [("3 pcs", 60, 30, "g")],
      "Absorbent cleaning sponge.",
      subcategory="Dishwash", ingredient_tags=["sponge", "utensils"],
      search=["sponge", "scotch brite"], image_queries=["scotch brite sponge pack"],
      related=["Dishwash Scrub", "Vim Dishwash Bar"]),
    P("Liquid Detergent", "Surf Excel", "Home Care", [("1 L", 220, 1000, "ml")],
      "Top-load liquid detergent.",
      subcategory="Detergent", ingredient_tags=["detergent", "liquid"],
      search=["liquid detergent", "surf excel"], image_queries=["surf excel liquid pack"],
      related=["Surf Excel Easy Wash", "Ariel Matic Top"]),
    P("Toilet Rim Block", "Harpic", "Home Care", [("1 pc", 110, 50, "g")],
      "In-cistern toilet freshener block.",
      subcategory="Cleaner", ingredient_tags=["toilet", "block"],
      search=["toilet rim block", "harpic"], image_queries=["harpic rim block pack"],
      related=["Harpic Toilet Cleaner", "Mosaic Cleaner"]),
    P("Drain Cleaner", "Harpic", "Home Care", [("500 ml", 130, 500, "ml")],
      "Pipe and drain unclogger.",
      subcategory="Cleaner", ingredient_tags=["drain", "cleaner"],
      search=["drain cleaner"], image_queries=["drain cleaner pack"],
      related=["Harpic Toilet Cleaner", "Lizol Disinfectant"]),
    P("Car Wash Shampoo", "3M", "Home Care", [("500 ml", 250, 500, "ml")],
      "Foaming car wash liquid.",
      subcategory="Cleaner", ingredient_tags=["car", "wash"],
      search=["car wash", "3m"], image_queries=["car wash shampoo pack"],
      related=["Floor Cleaner", "Liquid Detergent"]),
    P("Shoe Cleaner", "Kiwi", "Home Care", [("50 ml", 80, 50, "ml")],
      "Instant shoe polish spray.",
      subcategory="Cleaner", ingredient_tags=["shoe", "polish"],
      search=["shoe polish", "kiwi"], image_queries=["kiwi shoe polish pack"],
      related=["Fabric Conditioner", "Bleach"]),
    P("Multipurpose Cleaner", "Mr. Muscle", "Home Care", [("500 ml", 150, 500, "ml")],
      "All-surface kitchen cleaner.",
      subcategory="Cleaner", ingredient_tags=["kitchen", "cleaner"],
      search=["mr muscle", "kitchen cleaner"], image_queries=["mr muscle pack"],
      related=["Glass Cleaner", "Vim Gel"]),
    P("Stainless Steel Cleaner", "Cif", "Home Care", [("500 ml", 140, 500, "ml")],
      "Cream cleaner for steel and countertops.",
      subcategory="Cleaner", ingredient_tags=["steel", "cleaner"],
      search=["cif", "steel cleaner"], image_queries=["cif cleaner pack"],
      related=["Multipurpose Cleaner", "Glass Cleaner"]),
    P("Toilet Tissue", "Origami", "Home Care", [("6 rolls", 140, 600, "g")],
      "Soft 3-ply toilet rolls, pack of 6.",
      subcategory="Tissue", ingredient_tags=["tissue", "toilet"],
      search=["toilet paper", "tissue"], image_queries=["toilet tissue pack"],
      related=["Kitchen Towel", "Garbage Bags"]),
    P("Kitchen Towel", "Origami", "Home Care", [("2 rolls", 90, 200, "g")],
      "Absorbent kitchen paper rolls.",
      subcategory="Tissue", ingredient_tags=["kitchen", "towel"],
      search=["kitchen towel", "paper"], image_queries=["kitchen towel pack"],
      related=["Toilet Tissue", "Garbage Bags"]),
]
