"""Indian recipes for the AI copilot, and the coverage gate they enforce.

Each recipe lists canonical ingredient tags.  `build.validate_catalog` asserts
that **every ingredient of every recipe resolves to at least one catalog
product**; a recipe referencing an unstocked ingredient fails the build.

This inverts the usual approach: instead of scraping a catalog and hoping the
copilot finds matches, the catalog is obliged to satisfy the recipes.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Recipe:
    name: str
    cuisine: str            # North Indian | South Indian | Street Food | ...
    ingredients: list[str]  # canonical ingredient tags (match Product.ingredient_tags)
    serves: int = 4
    minutes: int = 30
    veg: bool = True
    description: str = ""
    tags: list[str] = field(default_factory=list)


def R(name, cuisine, ingredients, **kw) -> Recipe:
    return Recipe(name=name, cuisine=cuisine, ingredients=ingredients, **kw)


RECIPES: list[Recipe] = [
    # ---------------- North Indian mains ---------------- #
    R("Paneer Butter Masala", "North Indian",
      ["paneer", "tomato", "onion", "butter", "cream", "ginger", "garlic",
       "kashmiri chilli", "garam masala", "kasuri methi", "turmeric", "salt"],
      minutes=40, description="Restaurant-style paneer in a silky tomato-butter gravy.",
      tags=["popular", "dinner", "rich"]),
    R("Palak Paneer", "North Indian",
      ["spinach", "paneer", "onion", "tomato", "garlic", "ginger", "green chilli",
       "cumin seeds", "garam masala", "cream", "salt"],
      minutes=35, description="Soft paneer cubes in a smooth spiced spinach gravy.",
      tags=["healthy", "dinner"]),
    R("Dal Makhani", "North Indian",
      ["urad dal", "rajma", "butter", "cream", "tomato", "onion", "ginger",
       "garlic", "garam masala", "red chilli powder", "salt"],
      minutes=60, description="Slow-simmered black lentils finished with butter and cream.",
      tags=["popular", "rich", "dinner"]),
    R("Chole Masala", "North Indian",
      ["chickpeas", "onion", "tomato", "ginger", "garlic", "chole masala",
       "amchur", "cumin seeds", "turmeric", "oil", "salt"],
      minutes=45, description="Tangy Punjabi chickpea curry, best with bhature or rice.",
      tags=["popular", "protein"]),
    R("Rajma Chawal", "North Indian",
      ["rajma", "rice", "onion", "tomato", "ginger", "garlic", "garam masala",
       "cumin seeds", "turmeric", "oil", "salt"],
      minutes=50, description="Comforting kidney bean curry served over steamed rice.",
      tags=["comfort", "protein"]),
    R("Aloo Gobi", "North Indian",
      ["potato", "cauliflower", "onion", "tomato", "turmeric", "cumin seeds",
       "coriander powder", "green chilli", "coriander leaves", "oil", "salt"],
      minutes=30, description="Everyday dry sabzi of potato and cauliflower.",
      tags=["everyday", "lunch"]),
    R("Jeera Aloo", "North Indian",
      ["potato", "cumin seeds", "turmeric", "green chilli", "coriander leaves",
       "amchur", "oil", "salt"],
      minutes=20, description="Quick cumin-tempered potatoes, a reliable side dish.",
      tags=["quick", "side"]),
    R("Baingan Bharta", "North Indian",
      ["brinjal", "onion", "tomato", "garlic", "ginger", "green chilli",
       "cumin seeds", "turmeric", "coriander leaves", "mustard oil", "salt"],
      minutes=40, description="Smoky roasted aubergine mash with onions and tomato.",
      tags=["smoky", "dinner"]),
    R("Matar Paneer", "North Indian",
      ["paneer", "green peas", "tomato", "onion", "ginger", "garlic",
       "garam masala", "turmeric", "cream", "oil", "salt"],
      minutes=35, description="Paneer and green peas in a mildly spiced tomato gravy.",
      tags=["everyday", "dinner"]),
    R("Kadhi Pakora", "North Indian",
      ["besan", "curd", "turmeric", "mustard seeds", "fenugreek seeds",
       "asafoetida", "dry red chilli", "onion", "oil", "salt"],
      minutes=45, description="Tangy yogurt-gram flour curry with soft besan fritters.",
      tags=["comfort", "traditional"]),
    R("Bhindi Masala", "North Indian",
      ["okra", "onion", "tomato", "turmeric", "coriander powder",
       "red chilli powder", "amchur", "oil", "salt"],
      minutes=30, description="Stir-fried okra with onions and dry spices.",
      tags=["everyday", "dry"]),
    R("Aloo Methi", "North Indian",
      ["potato", "methi", "garlic", "green chilli", "turmeric",
       "cumin seeds", "oil", "salt"],
      minutes=25, description="Potatoes tossed with fresh fenugreek greens.",
      tags=["winter", "healthy"]),
    R("Lauki Kofta", "North Indian",
      ["bottle gourd", "besan", "onion", "tomato", "ginger", "garam masala",
       "cream", "turmeric", "oil", "salt"],
      minutes=50, description="Soft bottle gourd dumplings in a spiced gravy.",
      tags=["traditional"]),
    R("Gajar Halwa", "North Indian",
      ["carrot", "milk", "sugar", "ghee", "cardamom", "cashew", "raisins"],
      minutes=60, description="Classic winter dessert of slow-cooked carrots and milk.",
      tags=["dessert", "festive"]),

    # ---------------- Rice & breads ---------------- #
    R("Veg Biryani", "North Indian",
      ["basmati rice", "carrot", "green peas", "cauliflower", "onion", "curd",
       "biryani masala", "mint", "coriander leaves", "ghee", "cardamom",
       "cinnamon", "bay leaf", "salt"],
      minutes=60, description="Fragrant layered rice with vegetables and whole spices.",
      tags=["popular", "festive", "one-pot"]),
    R("Jeera Rice", "North Indian",
      ["basmati rice", "cumin seeds", "ghee", "bay leaf", "salt"],
      minutes=20, description="Simple cumin-tempered basmati, the default rice side.",
      tags=["quick", "side"]),
    R("Vegetable Pulao", "North Indian",
      ["basmati rice", "carrot", "green peas", "onion", "cinnamon", "cardamom",
       "bay leaf", "ghee", "salt"],
      minutes=35, description="One-pot spiced rice with mixed vegetables.",
      tags=["one-pot", "lunch"]),
    R("Roti", "North Indian", ["wheat flour", "salt", "ghee"],
      minutes=20, description="Everyday whole wheat flatbread.",
      tags=["staple", "bread"]),
    R("Aloo Paratha", "North Indian",
      ["wheat flour", "potato", "green chilli", "coriander leaves", "ajwain",
       "amchur", "ghee", "salt"],
      minutes=40, description="Stuffed potato flatbread, best with curd and pickle.",
      tags=["breakfast", "popular"]),
    R("Bhature", "North Indian",
      ["maida", "curd", "sugar", "oil", "salt"],
      minutes=120, description="Puffy fried bread, the partner to chole.",
      tags=["festive", "fried"]),

    # ---------------- South Indian ---------------- #
    R("Masala Dosa", "South Indian",
      ["rice", "urad dal", "fenugreek seeds", "potato", "onion", "mustard seeds",
       "curry leaves", "turmeric", "green chilli", "oil", "salt"],
      minutes=45, description="Crisp fermented crepe with a spiced potato filling.",
      tags=["popular", "breakfast"]),
    R("Idli", "South Indian",
      ["idli rava", "urad dal", "fenugreek seeds", "salt"],
      minutes=30, description="Steamed rice cakes, light and fermented.",
      tags=["breakfast", "healthy", "steamed"]),
    R("Sambar", "South Indian",
      ["toor dal", "sambar masala", "tamarind", "drumstick", "onion", "tomato",
       "mustard seeds", "curry leaves", "asafoetida", "turmeric", "oil", "salt"],
      minutes=40, description="Tangy lentil stew with vegetables and tamarind.",
      tags=["staple", "everyday"]),
    R("Rasam", "South Indian",
      ["tomato", "tamarind", "rasam powder", "black pepper", "cumin seeds",
       "curry leaves", "asafoetida", "coriander leaves", "ghee", "salt"],
      minutes=25, description="Peppery tamarind soup, soothing and digestive.",
      tags=["soup", "comfort"]),
    R("Coconut Chutney", "South Indian",
      ["coconut", "chana dal", "green chilli", "ginger", "mustard seeds",
       "curry leaves", "oil", "salt"],
      minutes=15, description="The default accompaniment to idli and dosa.",
      tags=["quick", "side"]),
    R("Upma", "South Indian",
      ["sooji", "onion", "mustard seeds", "curry leaves", "green chilli",
       "chana dal", "ginger", "oil", "salt"],
      minutes=25, description="Savoury semolina breakfast, quick and filling.",
      tags=["breakfast", "quick"]),
    R("Lemon Rice", "South Indian",
      ["rice", "lemon", "mustard seeds", "curry leaves", "turmeric",
       "chana dal", "dry red chilli", "groundnut oil", "salt"],
      minutes=20, description="Bright tangy rice, a classic lunchbox dish.",
      tags=["quick", "lunchbox"]),
    R("Curd Rice", "South Indian",
      ["rice", "curd", "mustard seeds", "curry leaves", "ginger",
       "green chilli", "asafoetida", "oil", "salt"],
      minutes=15, description="Cooling yogurt rice, the traditional end to a South Indian meal.",
      tags=["quick", "comfort", "summer"]),
    R("Medu Vada", "South Indian",
      ["urad dal", "green chilli", "ginger", "curry leaves", "black pepper",
       "oil", "salt"],
      minutes=40, description="Crisp savoury lentil doughnuts.",
      tags=["breakfast", "fried"]),

    # ---------------- Street food & snacks ---------------- #
    R("Pav Bhaji", "Street Food",
      ["potato", "green peas", "cauliflower", "capsicum", "onion", "tomato",
       "pav bhaji masala", "butter", "lemon", "coriander leaves", "salt"],
      minutes=45, description="Mumbai's buttery mashed vegetable curry with soft pav.",
      tags=["popular", "street", "dinner"]),
    R("Poha", "Street Food",
      ["poha", "onion", "potato", "mustard seeds", "curry leaves", "turmeric",
       "green chilli", "lemon", "coriander leaves", "oil", "salt"],
      minutes=20, description="Light flattened-rice breakfast from Maharashtra.",
      tags=["breakfast", "quick"]),
    R("Vegetable Pakora", "Street Food",
      ["besan", "onion", "potato", "spinach", "green chilli", "ajwain",
       "red chilli powder", "oil", "salt"],
      minutes=25, description="Crisp monsoon fritters in spiced gram flour batter.",
      tags=["snack", "fried", "monsoon"]),
    R("Masala Chai", "Street Food",
      ["tea", "milk", "sugar", "ginger", "cardamom", "cloves"],
      minutes=10, serves=2, description="Strong spiced Indian tea, brewed with milk.",
      tags=["beverage", "everyday", "quick"]),
    R("Bread Butter Toast", "Street Food",
      ["bread", "butter"],
      minutes=5, serves=2, description="The simplest breakfast: toasted bread with butter.",
      tags=["breakfast", "quick"]),
    R("Veg Sandwich", "Street Food",
      ["bread", "butter", "cucumber", "tomato", "onion", "potato",
       "chaat masala", "cheese"],
      minutes=15, serves=2, description="Layered vegetable sandwich with chaat masala.",
      tags=["snack", "quick", "lunchbox"]),
    R("Fruit Chaat", "Street Food",
      ["apple", "banana", "pomegranate", "guava", "chaat masala", "lemon", "black salt"],
      minutes=10, description="Fresh fruit tossed with tangy chaat masala.",
      tags=["healthy", "quick", "summer"]),
    R("Cucumber Raita", "North Indian",
      ["curd", "cucumber", "cumin powder", "black salt", "coriander leaves", "salt"],
      minutes=10, description="Cooling yogurt side dish with grated cucumber.",
      tags=["side", "quick", "summer"]),
    R("Boondi Raita", "North Indian",
      ["curd", "cumin powder", "black salt", "red chilli powder", "salt"],
      minutes=10, description="Yogurt raita with crisp gram flour pearls.",
      tags=["side", "quick"]),
    R("Sweet Lassi", "North Indian",
      ["curd", "sugar", "cardamom", "milk"],
      minutes=10, serves=2, description="Thick sweet yogurt drink, a Punjabi summer staple.",
      tags=["beverage", "summer", "quick"]),
    R("Mango Milkshake", "Street Food",
      ["mango", "milk", "sugar"],
      minutes=10, serves=2, description="Creamy summer shake with ripe Alphonso mango.",
      tags=["beverage", "summer", "quick"]),

    # ---------------- Eggs & non-veg ---------------- #
    R("Egg Bhurji", "North Indian",
      ["egg", "onion", "tomato", "green chilli", "turmeric", "coriander leaves",
       "oil", "salt"],
      minutes=15, veg=False, description="Spiced scrambled eggs, a fast protein-rich meal.",
      tags=["quick", "protein", "breakfast"]),
    R("Egg Curry", "North Indian",
      ["egg", "onion", "tomato", "ginger", "garlic", "garam masala",
       "turmeric", "red chilli powder", "oil", "salt"],
      minutes=35, veg=False, description="Boiled eggs simmered in a spiced onion-tomato gravy.",
      tags=["protein", "dinner"]),
]


def all_ingredients() -> set[str]:
    """Every distinct ingredient tag referenced by the recipe set."""
    return {i for r in RECIPES for i in r.ingredients}
